const string VERSION="1.3.1";const string DATAREV="15";const String pamTag="[PAM]";const String controllerTag="[PAM-Controller]";const int gyroSpeedSmall=15;const int gyroSpeedLarge=5;const int generalSpeedLimit=100;const float dockingSpeed=0.5f;const float dockDist=0.6f;const float followPathDock=2f;
const float followPathJob=1f;const float useDockDirectionDist=1f;const float useJobDirectionDist=0f;const float wpReachedDist=2f;const float drillRadius=1.4f;const float sensorRange=2f;const float fastSpeed=10f;const float minAccelerationSmall=0.2f;const float minAccelerationLarge=0.1f;
const float minEjection=25f;const bool setLCDFontAndSize=true;const bool checkConveyorSystem=false;public enum Κ{Ȗ,ŵ,ǐ,с,ΰ}public enum Β{ш,Ć,Ź,Ȣ,ď,ǜ,Э,
ě,ŕ,ȓ,Ÿ,Ţ,Ĕ,
Βγ,Ȃ,ȫ,Ġ,ΒΖ,ΑΨ,
Απ,Ʀ,Ƌ,ΒЊ,ȥ}public enum Ξ{й,ΓΖ,Њ,ΒΤ,Ə,Ɠ,ƭ,ĥ,ŀ}public enum г{None,Ġ,ш,ΔЈ}public enum Τ{Main,Γϋ,ż,Œ,ΑЇ,ΑΜ,
Αφ,ΓΝ,ΓΫ,ΓΟ,ΓΠ,Ηα,
Ηΰ,ΒΪ,ΔΜ,Ɛ,ΗΨ}public enum У{Ɖ,Ŝ,ΕЏ,ΓΤ,ΰ}public enum ǘ{Ǌ,Γψ}public enum Ы{ƃ,Αν,Γέ,ź}public enum ϊ{Αϋ,ΓΜ,Βό,Βς,Ƒ,ΑΡ,Ɗ}public enum ѓ{ΒЌ,Βά,Αθ}public enum А{į,ΕΕ,Ȯ}public enum δ{ΑЅ,Αώ,Αή,ΓІ,Γε,
Βδ,Ǝ,Ƙ,Αί,
ΑЎ,ΑΤ}public enum ά{ǩ,Ȍ,ǯ,ΑΒ,Βψ,ΒЉ}public enum ȍ{ΑЂ,ΓΔ,ΖЊ}public enum Ȇ{ΔА,ΔЂ,Ζο,Δζ}public enum Ǹ{None,ΒΞ,ΖΞ,Ζέ}public enum ο{Ų,ƹ,Ƽ,ź,ΑЋ,ƥ,ΑЃ,Εφ,ΓΓ}public enum ђ{Ȗ,Ζε,Ηά,Ζϊ,ΖЎ,ΕЅ,Γλ}class Ω{public bool α=false;public Vector3 Δ=new Vector3();
public Vector3 β=new Vector3();public Vector3 ί=new Vector3();public Vector3 φ=new Vector3();public Vector3 ς=new Vector3();public Vector3 д=new Vector3();public float О=0;public float Ηι=0;public float[]ј=null;public Ω(){}public Ω(Ω ǲ){α=ǲ.α;Δ=ǲ.Δ;β=ǲ.β;ί=ǲ.ί;φ=ǲ.φ;ς=ǲ.ς;
д=ǲ.д;ј=ǲ.ј;}public Ω(Vector3 Δ,Vector3 ί,Vector3 β,Vector3 φ,Vector3 ς){this.Δ=Δ;this.β=β;this.ί=ί;this.φ=φ;this.О=0;this.ς=ς;}public void ΕЋ(List<IMyThrust>ƙ,List<string>ǫ){ј=new float[ǫ.Count];for(int i=0;i<ј.Length;i++)
ј[i]=-1;for(int i=0;i<ƙ.Count;i++){string з=ΓΥ(ƙ[i]);int Α=ǫ.IndexOf(з);if(Α!=-1)
ј[Α]=І(ƙ[i].MaxEffectiveThrust,ƙ[i].MaxThrust);}}}class Βώ{public Ω Е=null;public List<Vector3>ļ=new List<Vector3>();public float ť=0;public float ΒЎ=0;public float Ń=0;public float Αι=0;public Vector3 ƶ=new Vector3();}class Ļ{public δ Ѕ=δ.ΑЅ;public float ѝ=0;public float ȟ=0;
public string Ǐ="";public string ў="";DateTime ΓΘ;public bool ΒЃ=false;private bool ΒΙ=false;public bool Ββ(bool ќ){if(ќ){ȟ=0;ΒΙ=false;return false;}ΒΙ=true;return ȟ>ѝ;}public void Εη(){Ββ(true);ΒЃ=false;}public void ΖΗ(){if(ΒΙ)
if((DateTime.Now-ΓΘ).TotalSeconds>1){ȟ++;ΓΘ=DateTime.Now;}}public bool ΑΟ(){switch(Ѕ){case δ.Αώ:return true;case δ.Αή:return true;}return false;}}class и{public String έ="";public String ν="";public int ώ=0;public А Ĭ=А.Ȯ;public и(String έ,String ν,int ώ,А Ĭ){this.έ=έ;this.ν=ν;
this.ώ=ώ;this.Ĭ=Ĭ;}}class ΖІ{public ΖІ(Vector3 Ќ,float Є){this.Ќ=Ќ;this.Є=Є;}public Vector3 Ќ;public float Є;}class ǎ{public DateTime Δτ;public DateTime ΔΟ;public String ǵ="";public String έ="";public String Δβ="";public String Ρ="";public String Εε="";public String ΗΗ="";public String ΑЌ="";
public Vector3 Δ=new Vector3();public List<и>Ћ=new List<и>();public Κ Μ=Κ.Ȗ;public Ǹ ȕ;public float Ȝ;public float Ȧ;public int Љ;public int ΖΛ=0;public int Γη=0;public bool Ηέ(){return(DateTime.Now-Δτ).TotalSeconds>10;}public bool Εϋ(){if(ȕ!=Ǹ.ΒΞ) return false;return(DateTime.Now-ΔΟ).TotalSeconds>=4;
}public ǎ(String ǵ){this.ǵ=ǵ;}public Ǹ Αω(String К,bool ΕΞ,bool Γβ,bool Ζς){if(К==""&&!Γβ) return Ǹ.None;if(ȕ==Ǹ.ΒΞ&&Εϋ())
ȕ=Ǹ.Ζέ;if(ΕΞ){ΑЌ=К;ȕ=Ǹ.ΒΞ;ΔΟ=DateTime.Now;return ȕ;}else if(Γβ){ΑЌ="";ȕ=Ǹ.None;}else if(ΑЌ==К){if(Ζς) ȕ=Ǹ.ΖΞ;return ȕ;}return Ǹ.None;}}public String Ηβ(String ΕΪ){switch(ΕΪ){case "IRON":return "Fe";case "NICKEL":return "Ni";case "COBALT":return "Co";case "MAGNESIUM":return "Mg";
case "SILICON":return "Si";case "SILVER":return "Ag";case "GOLD":return "Au";case "PLATINUM":return "Pt";case "URANIUM":return "U";default:return "";}}IMyGridTerminalSystem ψ;Vector3 ΑΔ=new Vector3();Vector3 κ=new Vector3();Vector3 ƚ=new Vector3();Vector3 Ʊ=new Vector3();Vector3 ƺ=new Vector3();
DateTime Βα=new DateTime();bool ȝ=true;int ΒБ=0;bool ȏ=false;bool Ƶ=false;bool ǅ=true;bool ΔЉ=false;bool Ķ=false;bool Ɵ=false;float ć=0;float ă=0;int ȯ=0;int ō=0;int Ő=0;int ΒЅ=0;float ŉ=0;float ī=0;double ΑЏ=0;float Ŕ=0;List<int>Ň=new List<int>();List<int>ġ=new List<int>();
Κ Μ=Κ.Ȗ;int Ѐ=0;float ȋ=0;float Ǵ=0;float σ=0;IMyRemoteControl Υ;IMySensorBlock λ;List<IMyTimerBlock>Βφ=new List<IMyTimerBlock>();List<IMyShipConnector>е=new List<IMyShipConnector>();List<IMyThrust>Ǻ=new List<IMyThrust>();List<IMyGyro>Ƥ=new List<IMyGyro>();List<IMyTerminalBlock>ξ=new List<IMyTerminalBlock>();
List<IMyLandingGear>Ǳ=new List<IMyLandingGear>();List<IMyReactor>Ȥ=new List<IMyReactor>();List<IMyConveyorSorter>ǋ=new List<IMyConveyorSorter>();List<IMyGasTank>р=new List<IMyGasTank>();List<IMyTerminalBlock>Ž=new List<IMyTerminalBlock>();List<IMyTerminalBlock>ğ=new List<IMyTerminalBlock>();
List<IMyTerminalBlock>Ȳ=new List<IMyTerminalBlock>();List<IMyBatteryBlock>ț=new List<IMyBatteryBlock>();List<IMyTextPanel>Ў=new List<IMyTextPanel>();List<IMyTextSurface>Ǣ=new List<IMyTextSurface>();List<IMyTextPanel>Ċ=new List<IMyTextPanel>();IMyTerminalBlock ф=null;Ω Θ=new Ω();Ω ΑЉ=new Ω();
Ω Αξ=new Ω();bool Ƿ=false;bool ħ=false;bool Ĥ=false;bool ƣ=false;List<String>ǫ=new List<string>();List<Ω>Φ=new List<Ω>();List<Ω>Ż=new List<Ω>();int ΑΪ=0;double ΔΛ=0;Ω Ε=new Ω();Vector3 ǭ;Vector3 ą;Ξ γ=Ξ.й;ǘ ΑΙ=ǘ.Ǌ;int Р=0;int в=0;double ū=0;bool ǌ=false;Ļ χ=new Ļ();
Ļ τ=new Ļ();Ы а=Ы.ƃ;bool ȧ=true;ǘ Ȋ=ǘ.Ǌ;int ы=3;int я=3;int Ш=30;ѓ Ǔ=ѓ.ΒЌ;bool ǿ=true;bool Ŀ=true;bool Ł=true;bool č=false;ϊ Й=ϊ.Αϋ;bool ȑ=true;float Ǡ=90;float н=20;float П=5;float м=20;float ǥ=0.70f;float ń=1.50f;float ņ=2.50f;float Ŧ=0f;float ĝ=0f;Β Ψ;
Ξ э;Β ŷ;Βώ η=null;int ρ=0;int π=0;int к=0;int Ț=0;int đ=30;int ѕ=0;bool Ђ=true;Vector3 ж;double З=0;bool Ʃ=false;int Βν=0;int ύ=0;int Αλ=0;int ĕ=0;int Γτ=0;Vector3 ŧ=new Vector3();float Ь=0;float Т=0;int Ę=0;float Βλ=0;float Ɔ=0;float Н=0;float ı=0;bool Αά=false;
bool Ė=false;bool Ř=false;bool Ȅ=false;bool Ȉ=false;DateTime ΖΕ=new DateTime();Ω Ǚ=null;Ω Γμ=null;float ǳ=0;г ǝ;float ǽ=0;float Ą=0;String Αα="";float ƻ=0;float Ȧ=0;float Ȝ=0;List<и>Ǖ=new List<и>();float Ж=0;bool œ=false;bool ΓЇ=false;bool ΔІ=false;bool Ƣ=false;
bool Δή=false;float ΑЄ=0;float ΒЍ=0;Vector3 Δμ=new Vector3();Vector3 ϋ=new Vector3();Vector3 ƕ=new Vector3(1,1,1);float ΑΧ=1;Vector3 Ũ=new Vector3();bool ƌ=false;bool Βύ=false;bool ΑБ=false;bool Γς=false;float Ʋ=0;float ΑΘ=2;Vector3 ΓΙ;Vector3 ΒЏ;Vector3 Αβ;float[,]џ=new float[3,2];
Dictionary<String,float[,]>х=new Dictionary<string,float[,]>();Dictionary<String,float>ΓЍ=new Dictionary<String,float>();int ΑϏ=0;Dictionary<String,float[]>Ȁ=new Dictionary<string,float[]>();float Αζ;bool ΑΓ=false;int ΑΕ=0;int ȣ=0;int ƅ=0;int Ȱ=0;String Ρ="";int[]ΓЁ=new int[Enum.GetValues(typeof(Τ)).Length];
bool Δκ=false;int ƾ=0;int Љ=0;Τ Ј=Τ.Main;int ΗΕ=0,ΗΜ=0,Εδ=0,ΖЌ=0;int ΕΗ=0,ΖΑ=0;bool Ħ=false;bool Γά=false;String ĭ="";String Βχ="";IMyBroadcastListener њ=null;bool Δϊ=true;List<ǎ>ё=null;ǎ Č=null;int ΗΥ=0,Ηλ=0;int ΗΤ=0,Ηγ=0;int Ημ=0,Ηθ=0,Ηη=0;
String ΖϏ="";Exception ȗ=null;bool Ɨ=false;Ξ Ŋ=Ξ.й;bool ΔΞ=true;String ΔΧ="";bool Ŭ=false;bool ΑΩ=true;int ǁ=0;int[]ч=null;Vector3 ΒЄ=new Vector3();bool Δγ=false;bool у(IMyTerminalBlock Σ)=>Σ.CubeGrid==Me.CubeGrid;Program(){ψ=GridTerminalSystem;Runtime.UpdateFrequency=UpdateFrequency.Update10;
if(Βκ(Me,controllerTag,true))
Μ=Κ.с;μ(Τ.Main);if(Μ!=Κ.с){Ρ="Welcome to [PAM]!";Ȇ Βξ=Επ();if(Μ==Κ.Ȗ){List<IMyShipDrill>ΔΫ=new List<IMyShipDrill>();List<IMyShipGrinder>Γώ=new List<IMyShipGrinder>();ψ.GetBlocksOfType(ΔΫ,q=>q.CubeGrid==Me.CubeGrid);ψ.GetBlocksOfType(Γώ,q=>q.CubeGrid==Me.CubeGrid);if(ΔΫ.Count>0)
{Μ=Κ.ŵ;Ρ="Miner mode enabled!";}else if(Γώ.Count>0){Μ=Κ.ǐ;Ρ="Grinder mode enabled!";}else{Μ=Κ.ΰ;ǰ(У.ΰ);}}if(Βξ==Ȇ.ΔА) ǅ=false;if(Βξ==Ȇ.ΔЂ) Ρ="Data restore failed!";if(Βξ==Ȇ.Δζ) Ρ="New version, wipe data";}}void Main(string И,UpdateType ΖΦ){try{if(ȗ!=null){ΕΥ();Γο();return;}
Ƶ=(ΖΦ&UpdateType.Update10)!=0;if(Ƶ) ΒБ++;ȏ=ΒБ>=10;if(ȏ) ΒБ=0;if(Ƶ){ΑΕ++;if(ΑΕ>4) ΑΕ=0;Ő=Math.Max(0,10-(DateTime.Now-Βα).Seconds);}if(И!="") ΖϏ=И;if(Μ!=Κ.с)
ΕΚ(И);else
Ζη(И);Δκ=false;try{int ΔЄ=Runtime.CurrentInstructionCount;float ĉ=І(ΔЄ,Runtime.MaxInstructionCount);if(ĉ>0.90) Ρ="Max. instructions >90%";if(ĉ>ŉ) ŉ=ĉ;if(ΑΓ){Ň.Add(ΔЄ);while(Ň.Count>10) Ň.RemoveAt(0);ī=0;for(int i=0;i<Ň.Count;i++) ī+=Ň[i];ī=І(І(ī,Ň.Count),Runtime.MaxInstructionCount);
double Αμ=Runtime.LastRunTimeMs;if(Ɵ&&Αμ>ΑЏ) ΑЏ=Αμ;ġ.Add((int)(Αμ*1000f));while(ġ.Count>10) ġ.RemoveAt(0);Ŕ=0;for(int i=0;i<ġ.Count;i++) Ŕ+=ġ[i];Ŕ=І(Ŕ,ġ.Count)/1000f;}}catch{ŉ=0;}}catch(Exception e){ȗ=e;}}void ΕΚ(string И){bool Ƹ=false;String ΓЀ="";if(Ѐ<=1&&!ΑЀ(И))
Δέ(И);if(њ!=null&&њ.HasPendingMessage){MyIGCMessage θ=њ.AcceptMessage();String ε=(string) θ.Data;String ǣ="";if(Ѐ<=1&&ΔΓ(ref ε,out ǣ,out ΓЀ)&&ǣ==BROADCAST_SELF_ID){Δέ(ε);Ƹ=true;}}bool ΓϏ=Ɵ&&Ψ==Β.ш&&!Ķ&&!Ƹ&&ȯ==0&&!ƣ;if(ȏ&&Ψ!=Β.ш) Ƹ=true;if((Ƶ&&!ΓϏ)||(ȏ&&ΓϏ))
{if(ȯ==0&&(Ő<=0||ȝ)){ΔЉ=Ѐ>0;Ѐ=0;ȯ=1;Ǩ();ΕЌ();ΓΣ();Ǧ("Scan 1");}else if(ȯ==1){ȯ=2;Ǩ();ΕЄ();Ǧ("Scan 2");}else if(ȯ==2){ȯ=0;Ǩ();Εΰ();Ǧ("Scan 3");Βα=DateTime.Now;if(Ѐ<=1&&ǅ)
ΑΔ=Βθ(Υ,Υ.CenterOfMass);ǅ=false;if(ȝ){ȝ=false;υ();}if(ΔЉ&&Ѐ==0) Ρ="Setup complete";}else{if(γ==Ξ.Њ&&Μ!=Κ.ΰ){Ǩ();ΗΖ();Ǧ("Inv balance");}Ǩ();switch(ō){case 0:ΗΣ();break;case 1:Ζϋ();break;case 2:ΖЉ();break;case 3:ΖΣ();break;case 4:ΖЀ();break;case 5:ΖЃ();break;case 6:Ζχ(Υ);break;
}Ǧ("Update: "+ō);ō++;if(ō>6){ō=0;Ɵ=true;if(Ŋ!=Ξ.й){switch(Ŋ){case Ξ.ĥ:ċ();break;case Ξ.ŀ:ċ();break;case Ξ.Њ:ċ();break;case Ξ.Ɠ:ư();break;case Ξ.ƭ:Ă();break;}Ŋ=Ξ.й;}}}if(!ȝ){if(!Ǭ(Υ,true)){Υ=null;ǅ=true;Ѐ=2;}if(Ѐ>=2&&Ψ!=Β.ш)
υ();if(Ѐ<=1){ă=Υ.CalculateShipMass().PhysicalMass;ć=(float) Υ.GetShipSpeed();κ=Εψ(Υ,ΑΔ);ƚ=Υ.WorldMatrix.Forward;Ʊ=Υ.WorldMatrix.Left;ƺ=Υ.WorldMatrix.Down;ΗΓ();if(Ψ!=Β.ш){Ķ=false;Γϊ(false);Γό(false);String ΗΚ=Αό(Ψ)+" "+(int) Ψ;Ǩ();ΖΖ();ΑІ(false);Ǧ(ΗΚ);Ǩ();ΗΔ();Ǧ("Thruster");Ǩ();
Γδ();Ǧ("Gyroscope");}else{if(Ķ){if(ƛ()){Х(ƺ,ƚ,Ʊ,0.25f,true);Γδ();Ρ="Aligning to planet: "+Math.Round(Ʋ-0.25f,2)+"°";if(ƌ) ΑЊ(true,true);}else ΑЊ(true,true);}}Ŭ=false;}}}Ǩ();Γο();Ǧ("Print");if(Ƹ||ΒЅ<=0){Ǩ();Ζμ(ΓЀ);Ǧ("Broadcast");ΒЅ=4;}else if(ȏ) ΒЅ--;}void Δέ(string И){if(И=="") return;
var ι=И.ToUpper().Split(' ');ι.DefaultIfEmpty("");var К=ι.ElementAtOrDefault(0);var Ȟ=ι.ElementAtOrDefault(1);var Ŏ=ι.ElementAtOrDefault(2);var ΓЌ=ι.ElementAtOrDefault(3);String ǹ="Invalid argument: "+И;bool ΑΦ=false;switch(К){case "UP":this.Αε(false);break;case "DOWN":this.ΑΣ(false);break;
case "UPLOOP":this.Αε(true);break;case "DOWNLOOP":this.ΑΣ(true);break;case "APPLY":this.Γγ(true);break;case "MRES":Љ=0;break;case "STOP":this.υ();break;case "PATHHOME":{this.υ();this.ΒΕ();}break;case "PATH":{this.υ();this.ΒΕ();Θ.α=true;}break;case "START":{this.υ();Βω();}break;
case "ALIGN":{ΑЊ(!Ķ,false);}break;case "CONT":{this.υ();this.ċ();}break;case "JOBPOS":{this.υ();this.Ă();}break;case "HOMEPOS":{this.υ();this.ư();}break;case "FULL":{œ=true;}break;case "RESET":{Ɨ=true;Ѐ=2;}break;default:ΑΦ=true;break;}if(Μ!=Κ.ΰ){switch(К){case "SHUTTLE":{Ζν();}break;
case "CFGS":{if(!ΖΥ(Ȟ,Ŏ,ΓЌ)) Ρ=ǹ;}break;case "CFGB":{if(!ΖА(Ȟ,Ŏ)) Ρ=ǹ;}break;case "CFGL":{if(!ę(ref Ǡ,true,ο.Ƽ,Ȟ,"")||!ΕΤ(Ŏ))
Ρ=ǹ;}break;case "CFGE":{if(!ę(ref П,true,ο.ƥ,Ȟ,"IG")||
!ę(ref н,true,ο.ΑЋ,Ŏ,"IG")||
!ę(ref м,true,ο.ΑЃ,ΓЌ,"IG"))
Ρ=ǹ;}break;case "CFGA":{if(!ę(ref ǥ,false,ο.ƹ,Ȟ,"")) Ρ=ǹ;}break;case "CFGW":{if(!ę(ref ń,false,ο.Ų,Ȟ,"")||
!ę(ref ņ,false,ο.Ų,Ŏ,""))
Ρ=ǹ;}break;case "NEXT":{ΑΥ(false);}break;case "PREV":{ΑΥ(true);}break;default:if(ΑΦ) Ρ=ǹ;break;}}else{switch(К){case "UNDOCK":{Ŭ=true;}break;default:if(ΑΦ) Ρ=ǹ;break;}}}String Ζω(){String Γ="\n\n"+"Run-arguments: (Type without:[ ])\n"+"———————————————\n"+
"[UP] Menu navigation up\n"+"[DOWN] Menu navigation down\n"+"[APPLY] Apply menu point\n\n"+
"[UPLOOP] \"UP\" + looping\n"+"[DOWNLOOP] \"DOWN\" + looping\n"+
"[PATHHOME] Record path, set home\n"+"[PATH] Record path, use old home\n"+
"[START] Start job\n"+"[STOP] Stop every process\n"+"[CONT] Continue last job\n"+
"[JOBPOS] Move to job position\n"+"[HOMEPOS] Move to home position\n\n"+
"[FULL] Simulate ship is full\n"+"[ALIGN] Align the ship to planet\n"+"[RESET] Reset all data\n";if(Μ!=Κ.ΰ)
Γ+="[SHUTTLE] Enable shuttle mode\n"+"[NEXT] Next hole\n"+"[PREV] Previous hole\n\n"+
"[CFGS width height depth]*\n"+"[CFGB done damage]*\n"+"[CFGL maxload weightLimit]*\n"+
"[CFGE minUr minBat minHyd]*\n"+"[CFGW forward backward]*\n"+"[CFGA acceleration]*\n"+
"———————————————\n"+
"*[CFGS] = Config Size:\n"+" e.g.: \"CFGS 5 3 20\"\n\n"+
"*[CFGB] = Config Behaviour:\n"+" When done: [HOME,STOP]\n"+" On Damage: [HOME,JOB,STOP,IG]\n"+
" e.g.: \"CFGB HOME IG\"\n\n"+
"*[CFGL] = Config max load:\n"+" maxload: [10..95]\n"+" weight limit: [On/Off]\n"+
" e.g.: \"CFGL 70 on\"\n\n"+
"*[CFGE] = Config energy:\n"+" minUr (Uranium): [1..25, IG]\n"+" minBat (Battery): [5..30, IG]\n"+
" minHyd (Hydrogen): [10..90, IG]\n"+" e.g.: \"CFGE 20 10 IG\"\n\n"+
"*[CFGW] = Config work speed:\n"+" fwd: [0.5..10]\n"+" bwd: [0.5..10]\n"+
" e.g.: \"CFGW 1.5 2\"\n\n"+
"*[CFGA] = Config acceleration:\n"+" acceleration: [10..100]\n"+" e.g.: \"CFGA 80\"\n";else
Γ+="[UNDOCK] Leave current connector\n\n";return Γ;}void Ζν(){υ();Μ=Κ.ΰ;ǰ(У.ΰ);Ε.α=false;Θ.α=false;λ=null;ξ.Clear();γ=Ξ.й;}void ΑЊ(bool Ё,bool ǚ){if(!Ё) Ρ="Aligning canceled";if(ǚ) Ρ="Aligning done";if(ǚ||!Ё){Ķ=false;Γρ();ΑΑ(false,0,0,0,0);return;}if(ƛ()) Ķ=true;}bool ΖΥ(String Ζζ,String ΕІ,String ΕЃ)
{bool Εξ=γ==Ξ.Њ;int w,h,d;if(int.TryParse(Ζζ,out w)&&int.TryParse(ΕІ,out h)&&int.TryParse(ΕЃ,out d)){this.υ();ы=w;я=h;Ш=d;ȳ(false);Ƨ(false,false);if(Εξ) ċ();return true;}return false;}bool ΕΤ(String ő){if(ő=="ON"){ǿ=true;return true;}if(ő=="OFF"){ǿ=false;return true;}
return false;}bool ΖА(String ΔΣ,String ƨ){bool ȭ=true;if(ΔΣ=="HOME") ȧ=true;else if(ΔΣ=="STOP") ȧ=false;else ȭ=false;if(ƨ=="HOME") а=Ы.ƃ;else if(ƨ=="STOP") а=Ы.Γέ;else if(ƨ=="JOB") а=Ы.Αν;else if(ƨ=="IG") а=Ы.ź;else ȭ=false;return ȭ;}void μ(Τ Ĝ){ΓЁ[(int) Ј]=Љ;Љ=ΓЁ[(int) Ĝ];
if(Ĝ==Τ.ΓΠ) Љ=0;Ј=Ĝ;if(Μ!=Κ.с)
Ě(Ј==Τ.ż,false,0,0);Δκ=true;}void Αε(bool Ακ){if(Љ>0) Љ--;else if(Ακ) Љ=ƾ-1;}void ΑΣ(bool Ακ){if(Љ<ƾ-1) Љ++;else if(Ακ) Љ=0;}String ǰ(У θ){switch(θ){case У.Ɖ:Ρ="Job is running";break;case У.Ŝ:Ρ="Connector not ready!";break;case У.ΕЏ:Ρ="Ship modified, path outdated!";break;
case У.ΓΤ:Ρ="Interrupted by player!";break;case У.ΰ:Ρ="Shuttle mode enabled!";break;}return "";}String ΖЄ(ǘ Ќ){switch(Ќ){case ǘ.Ǌ:return "Top-Left";case ǘ.Γψ:return "Center";default:return "";}}String ΕΛ(ѓ С){switch(С){case ѓ.Βά:return "Auto"+(Μ==Κ.ŵ?" (Ore)":"");case ѓ.Αθ:return "Auto (+Stone)";
case ѓ.ΒЌ:return "Default";default:return "";}}String ΒΫ(Ξ М){switch(М){case Ξ.й:return "No job";case Ξ.ΓΖ:return "Job paused";case Ξ.Њ:return "Job active";case Ξ.ĥ:return "Job active";case Ξ.ŀ:return "Job active";case Ξ.ΒΤ:return "Job done";case Ξ.Ə:return "Job changed";case Ξ.Ɠ:return "Move home";
case Ξ.ƭ:return "Move to job";}return "";}String Δα(Ы ΖЋ){switch(ΖЋ){case Ы.ƃ:return "Return home";case Ы.Αν:return "Fly to job pos";case Ы.Γέ:return "Stop";case Ы.ź:return "Ignore";}return "";}String Ζσ(ϊ С){switch(С){case ϊ.Αϋ:return "Off";case ϊ.Βς:return "Drop pos (Stone) ";case ϊ.Ƒ:return "Drop pos (Sto.+Ice)";
case ϊ.ΓΜ:return "Cur. pos (Stone)";case ϊ.Βό:return "Cur. pos (Sto.+Ice)";case ϊ.ΑΡ:return "In motion (Stone)";case ϊ.Ɗ:return "In motion (Sto.+Ice)";}return "";}String Δθ(г М){switch(М){case г.None:return "No batteries";case г.Ġ:return "Charging";case г.ΔЈ:return "Discharging";}return "";}String Αό(Β М)
{String ΗΦ=Μ==Κ.ΰ?"target":"job";switch(М){case Β.ш:return "Idle";case Β.Ć:return "Flying to XY position";case Β.Ź:return Μ==Κ.ǐ?"Grinding":"Mining";case Β.Ȣ:return "Returning";case Β.Ƌ:return "Flying to drop pos";case Β.ď:return "Returning to dock";case Β.ǜ:return "Flying to dock area";
case Β.Э:return "Flying to job area";case Β.ě:return "Flying to path";case Β.ŕ:return "Flying to job position";case Β.ȓ:return "Approaching dock";case Β.Ÿ:return "Docking";case Β.Ţ:return "Aligning";case Β.Ĕ:return "Aligning";case Β.Βγ:return "Retry docking";case Β.Ȃ:return "Unloading";case Β.ȥ:return ΔΧ;
case Β.ȫ:return "Undocking";case Β.Ġ:return "Charging batteries";case Β.ΒΖ:return "Waiting for uranium";case Β.ΑΨ:return "Filling up hydrogen";case Β.Απ:return "Waiting for ejection";case Β.Ʀ:return "Waiting for ejection";case Β.ΒЊ:return "Flying to drop pos";}return "";}String ΓЋ(δ Ѕ){switch(Ѕ)
{case δ.ΑЅ:return "On \"Undock\" command";case δ.Αώ:return "On player entered cockpit";case δ.ΓІ:return "On ship is full";case δ.Γε:return "On ship is empty";case δ.Αή:return "On time delay";case δ.Ǝ:return "On batteries empty(<25%)";case δ.Ƙ:return "On batteries empty(=0%)";case δ.Βδ:return "On batteries full";
case δ.ΑЎ:return "On hydrogen empty(<25%)";case δ.ΑΤ:return "On hydrogen empty(=0%)";case δ.Αί:return "On hydrogen full";}return "";}bool Ν(ref String Γ,int ΔЅ,int Ƞ,bool Η,String ē){ƾ+=1;if(ΔЅ==Ƞ) ē=">"+ē+(ΑΕ>=2?" .":"");else ē=" "+ē;Γ+=ē+"\n";return ΔЅ==Ƞ&&Η;}String Γγ(bool Η)
{int Α=0;int Λ=Љ;ƾ=0;String ΔЇ="———————————————\n";String ĸ="--------------------------------------------\n";String Γ="";Γ+=ΒΫ(γ)+" | "+(Θ.α?"Ready to dock":"No dock")+"\n";Γ+=ΔЇ;double ţ=Math.Max(Math.Round(this.З),0);if(Ј==Τ.Main){bool Ȭ=Μ==Κ.ΰ;if(Ν(ref Γ,Λ,Α++,Η," Record path & set home")) ΒΕ();
if(Μ==Κ.ŵ)
if(Ν(ref Γ,Λ,Α++,Η," Setup mining job")) μ(Τ.ż);if(Μ==Κ.ǐ)
if(Ν(ref Γ,Λ,Α++,Η," Setup grinding job")) μ(Τ.ż);if(Μ==Κ.ΰ)
if(Ν(ref Γ,Λ,Α++,Η," Setup shuttle job")) μ(Τ.ΒΪ);if(Ν(ref Γ,Λ,Α++,Η," Continue job")) ċ();if(Ν(ref Γ,Λ,Α++,Η," Fly to home position")) ư();if(Ν(ref Γ,Λ,Α++,Η," Fly to job position")) Ă();if(Ν(ref Γ,Λ,Α++,Η," Behavior settings"))
if(Ȭ) μ(Τ.Ɛ);else μ(Τ.ΑΜ);if(Ν(ref Γ,Λ,Α++,Η," Info")) μ(Τ.ΓΝ);if(Μ!=Κ.ΰ)
if(Ν(ref Γ,Λ,Α++,Η," Help")) μ(Τ.ΓΟ);}else if(Ј==Τ.ż){double ΖΘ=Math.Round(ы*ȋ,1);double ΕΖ=Math.Round(я*Ǵ,1);String ό="";if(Ν(ref ό,Λ,Α++,Η," Start new job!")) Βω();if(Ν(ref ό,Λ,Α++,Η," Change current job")){Ƨ(false,false);μ(Τ.Main);}if(Ν(ref ό,Λ,Α++,Η," Width + (Width: "+ы+" = "+ΖΘ+"m)")){ň(ref ы,5,20,1);ȳ(true);}
if(Ν(ref ό,Λ,Α++,Η," Width -")){ň(ref ы,-5,20,-1);ȳ(true);}if(Ν(ref ό,Λ,Α++,Η," Height + (Height: "+я+" = "+ΕΖ+"m)")){ň(ref я,5,20,1);ȳ(true);}if(Ν(ref ό,Λ,Α++,Η," Height -")){ň(ref я,-5,20,-1);ȳ(true);}if(Ν(ref ό,Λ,Α++,Η," Depth + ("+(Ǔ==ѓ.ΒЌ?"Depth":"Min")+": "+Ш+"m)")){ň(ref Ш,5,50,2);ȳ(true);}
if(Ν(ref ό,Λ,Α++,Η," Depth -")){ň(ref Ш,-5,50,-2);ȳ(true);}if(Ν(ref ό,Λ,Α++,Η," Depth mode: "+ΕΛ(Ǔ))){Ǔ=Ȕ(Ǔ);}if(Ν(ref ό,Λ,Α++,Η," Start pos: "+ΖЄ(Ȋ))){Ȋ=Ȕ(Ȋ);}if(Μ==Κ.ǐ&&Ǔ==ѓ.Αθ) Ǔ=Ȕ(Ǔ);Γ+=Γξ(8,ό,Λ,ref ΕΗ);}else if(Ј==Τ.ΒΪ){float[]ΔЏ=new float[]{0,3,10,30,60,300,600,1200,1800};
if(Ν(ref Γ,Λ,Α++,Η," Next")) μ(Τ.ΔΜ);if(Ν(ref Γ,Λ,Α++,Η," Back")) μ(Τ.Main);Γ+=" Leave connector 1:\n";if(Ν(ref Γ,Λ,Α++,Η," - "+ΓЋ(χ.Ѕ))) χ.Ѕ=Ȕ(χ.Ѕ);if(!χ.ΑΟ()) Γ+="\n";else if(Ν(ref Γ,Λ,Α++,Η," - Delay: "+ΒϏ((int) χ.ѝ))) χ.ѝ=Γχ(χ.ѝ,ΔЏ);Γ+=" Leave connector 2:\n";if(Ν(ref Γ,Λ,Α++,Η," - "+ΓЋ(τ.Ѕ))) τ.Ѕ=Ȕ(τ.Ѕ);
if(!τ.ΑΟ()) Γ+="\n";else if(Ν(ref Γ,Λ,Α++,Η," - Delay: "+ΒϏ((int) τ.ѝ))) τ.ѝ=Γχ(τ.ѝ,ΔЏ);}else if(Ј==Τ.ΔΜ){if(Ν(ref Γ,Λ,Α++,Η," Start job!")) Βω();if(Ν(ref Γ,Λ,Α++,Η," Back")) μ(Τ.ΒΪ);Γ+=" Timer: \"Docking connector 1\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(χ.Ǐ!=""?χ.Ǐ:"-"))) χ.Ǐ=ƫ(ref ΗΕ);
Γ+=" Timer: \"Leaving connector 1\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(χ.ў!=""?χ.ў:"-"))) χ.ў=ƫ(ref Εδ);Γ+=" Timer: \"Docking connector 2\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(τ.Ǐ!=""?τ.Ǐ:"-"))) τ.Ǐ=ƫ(ref ΗΜ);Γ+=" Timer: \"Leaving connector 2\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(τ.ў!=""?τ.ў:"-"))) τ.ў=ƫ(ref ΖЌ);
}else if(Ј==Τ.Œ){String Δϋ=Ǡ+" %";if(ȏ) ȣ++;if(ȣ>1){ȣ=0;ƅ++;if(ƅ>1) ƅ=0;}bool[]ΒΠ=new bool[]{Ȥ.Count==0,ǝ==г.None,р.Count==0};int ΓΛ=0;while(true){ΓΛ++;Ȱ++;if(Ȱ>ΒΠ.Length-1) Ȱ=0;if(ΓΛ>=ΒΠ.Length) break;if(!ΒΠ[Ȱ]) break;}bool Ȭ=Μ==Κ.ΰ;if(!Ȭ&&ǿ&&Ж!=-1&&ƅ==0)
Δϋ=Ж<1000000?Math.Round(Ж)+" Kg":Math.Round(Ж/1000)+" t";if(Ν(ref Γ,Λ,Α++,Η," Stop!")){υ();μ(Τ.Main);}if(Ν(ref Γ,Λ,Α++,Η," Behavior settings"))
if(!Ȭ) μ(Τ.ΑΜ);else μ(Τ.Ɛ);if(!Ȭ){if(Ν(ref Γ,Λ,Α++,Η," Next hole")) ΑΥ(false);}else if(Ν(ref Γ,Λ,Α++,Η," Undock")) Ŭ=true;Γ+=ĸ;if(!Ȭ) Γ+="Progress: "+Math.Round(ū,1)+" %\n";Γ+="State: "+Αό(Ψ)+" "+ţ+"m \n";Γ+="Load: "+ƻ+" % Max: "+Δϋ+" \n";if(Ȱ==0) Γ+="Uranium: "+(Ȥ.Count==0?"No reactors":Math.Round(Ą,1)+"Kg "+(П==-1?"":" Min: "+П+" Kg"))+"\n";
if(Ȱ==1) Γ+="Battery: "+(ǝ==г.None?Δθ(ǝ):ǳ+"% "+(н==-1||Ȭ?"":" Min: "+н+" %"))+"\n";if(Ȱ==2) Γ+="Hydrogen: "+(р.Count==0?"No tanks":Math.Round(ǽ,1)+"% "+(м==-1||Ȭ?"":" Min: "+м+" %"))+"\n";}else if(Ј==Τ.ΑΜ){String ό="";if(Ν(ref ό,Λ,Α++,Η," Back")){if(γ==Ξ.Њ) μ(Τ.Œ);else μ(Τ.Main);}
if(Ν(ref ό,Λ,Α++,Η," Max load: "+Ǡ+"%")) Ъ(ref Ǡ,Ǡ<=80?-10:-5,ο.Ƽ,false);if(Ν(ref ό,Λ,Α++,Η," Weight limit: "+(ǿ?"On":"Off"))) ǿ=!ǿ;if(Ν(ref ό,Λ,Α++,Η," Ejection: "+Ζσ(Й))) Й=Ȕ(Й);if(Ν(ref ό,Λ,Α++,Η," Toggle sorters: "+(č?"On":"Off"))){č=!č;if(č) ǟ(ΑΩ);}
if(Ν(ref ό,Λ,Α++,Η," Unload ice: "+(ȑ?"On":"Off"))) ȑ=!ȑ;if(Ν(ref ό,Λ,Α++,Η," Uranium: "+(П==-1?"Ignore":"Min "+П+"Kg"))) Ъ(ref П,(П>5?-5:-1),ο.ƥ,true);if(Ν(ref ό,Λ,Α++,Η," Battery: "+(н==-1?"Ignore":"Min "+н+"%"))) Ъ(ref н,-5,ο.ΑЋ,true);if(Ν(ref ό,Λ,Α++,Η," Hydrogen: "+(м==-1?"Ignore":"Min "+м+"%"))) Ъ(ref м,-10,ο.ΑЃ,true);
if(Ν(ref ό,Λ,Α++,Η," When done: "+(ȧ?"Return home":"Stop"))) ȧ=!ȧ;if(Ν(ref ό,Λ,Α++,Η," On damage: "+Δα(а))) а=Ȕ(а);if(Ν(ref ό,Λ,Α++,Η," Advanced...")) μ(Τ.Αφ);Γ+=Γξ(8,ό,Λ,ref ΖΑ);}else if(Ј==Τ.Αφ){if(Ν(ref Γ,Λ,Α++,Η," Back")){if(γ==Ξ.Њ) μ(Τ.Œ);else μ(Τ.Main);}
if(Ν(ref Γ,Λ,Α++,Η,(Μ==Κ.ǐ?" Grinder":" Drill")+" inv. balancing: "+(Ŀ?"On":"Off"))) Ŀ=!Ŀ;if(Ν(ref Γ,Λ,Α++,Η," Enable"+(Μ==Κ.ǐ?" grinders":" drills")+": "+(Ł?"Fwd + Bwd":"Fwd"))) Ł=!Ł;if(Ν(ref Γ,Λ,Α++,Η," Work speed fwd.: "+ń+"m/s")) Ъ(ref ń,0.5f,ο.Ų,false);
if(Ν(ref Γ,Λ,Α++,Η," Work speed bwd.: "+ņ+"m/s")) Ъ(ref ņ,0.5f,ο.Ų,false);if(Ν(ref Γ,Λ,Α++,Η," Acceleration: "+Math.Round(ǥ*100f)+"%"+(ǥ>0.80f?" (risky)":""))) Ъ(ref ǥ,0.1f,ο.ƹ,false);if(Ν(ref Γ,Λ,Α++,Η," Width overlap: "+Ŧ*100f+"%")) ΔЌ(true,0.05f);if(Ν(ref Γ,Λ,Α++,Η," Height overlap: "+ĝ*100f+"%")) ΔЌ(false,0.05f);
}else if(Ј==Τ.Ɛ){if(Ν(ref Γ,Λ,Α++,Η," Back")){if(γ==Ξ.Њ) μ(Τ.Œ);else μ(Τ.Main);}if(Ν(ref Γ,Λ,Α++,Η," Max load: "+Ǡ+"%")) Ъ(ref Ǡ,Ǡ<=80?-10:-5,ο.Ƽ,false);if(Ν(ref Γ,Λ,Α++,Η," Unload ice: "+(ȑ?"On":"Off"))) ȑ=!ȑ;if(Ν(ref Γ,Λ,Α++,Η," Uranium: "+(П==-1?"Ignore":"Min "+П+"Kg"))) Ъ(ref П,(П>5?-5:-1),ο.ƥ,true);
if(Ν(ref Γ,Λ,Α++,Η," Battery: "+(н==-1?"Ignore":"Charge up"))) н=(н==-1?1:-1);if(Ν(ref Γ,Λ,Α++,Η," Hydrogen: "+(м==-1?"Ignore":"Fill up"))) м=(м==-1?1:-1);if(Ν(ref Γ,Λ,Α++,Η," On damage: "+Δα(а))) а=Ȕ(а);if(Ν(ref Γ,Λ,Α++,Η," Acceleration: "+Math.Round(ǥ*100f)+"%"+(ǥ>0.80f?" (risky)":""))) Ъ(ref ǥ,0.1f,ο.ƹ,false);
}else if(Ј==Τ.Γϋ){double Εώ=0;if(Φ.Count>0) Εώ=Vector3.Distance(Φ.Last().Δ,κ);if(Ν(ref Γ,Λ,Α++,Η," Stop path recording")) ΓΦ();if(Μ!=Κ.ΰ){if(Ν(ref Γ,Λ,Α++,Η," Home: "+(Ƿ?"Use old home":(Θ.α?"Was set! ":"none ")))) Ƿ=!Ƿ;}else{if(Ν(ref Γ,Λ,Α++,Η," Connector 1: "+(Ƿ?"Use old connector":(Θ.α?"Was set! ":"none ")))) Ƿ=!Ƿ;
if(Ν(ref Γ,Λ,Α++,Η," Connector 2: "+(ħ?"Use old connector":(Ε.α?"Was set! ":"none ")))) ħ=!ħ;}if(Ν(ref Γ,Λ,Α++,Η," Path: "+(Ĥ?"Use old path":(Φ.Count>1?"Count: "+Φ.Count:"none ")))) Ĥ=!Ĥ;Γ+=ĸ;Γ+="Wp spacing: "+Math.Round(ΔΛ)+"m\n";}else if(Ј==Τ.ΑЇ){if(Ν(ref Γ,Λ,Α++,Η," Stop")){υ();μ(Τ.Main);}
Γ+=ĸ;Γ+="State: "+Αό(Ψ)+" \n";Γ+="Speed: "+Math.Round(ć,1)+"m/s\n";Γ+="Target dist: "+ţ+"m\n";Γ+="Wp count: "+Φ.Count+"\n";Γ+="Wp left: "+Βν+"\n";}else if(Ј==Τ.ΓΝ){List<IMyTerminalBlock>Ď=Δύ();if(ȏ) ȣ++;if(ȣ>=Ď.Count) ȣ=0;if(Ν(ref Γ,Λ,Α++,Η," Next")) μ(Τ.ΓΫ);
Γ+=ĸ;Γ+="Version: "+VERSION+"\n";Γ+="Ship load: "+Math.Round(ƻ,1)+"% "+Math.Round(Ȧ,1)+" / "+Math.Round(Ȝ,1)+"\n";Γ+="Uranium: "+(Ȥ.Count==0?"No reactors":Math.Round(Ą,1)+"Kg "+Αα)+"\n";Γ+="Battery: "+(ǝ==г.None?"":ǳ+"% ")+Δθ(ǝ)+"\n";Γ+="Hydrogen: "+(р.Count==0?"No tanks":Math.Round(ǽ,1)+"% ")+"\n";
Γ+="Damage: "+(Ď.Count==0?"None":""+(ȣ+1)+"/"+Ď.Count+" "+Ď[ȣ].CustomName)+"\n";}else if(Ј==Τ.ΓΫ){if(Ν(ref Γ,Λ,Α++,Η," Back")) μ(Τ.Main);Γ+=ĸ;Γ+="Next scan: "+Ő+"s\n";Γ+="Ship size: "+Math.Round(ȋ,1)+"m "+Math.Round(Ǵ,1)+"m "+Math.Round(σ,1)+"m \n";
Γ+="Broadcast: "+(Ħ?"Online - "+ĭ:"Offline")+"\n";Γ+="Max Instructions: "+Math.Round(ŉ*100f,1)+"% \n";}else if(Ј==Τ.ΓΟ){if(Ν(ref Γ,Λ,Α++,Η," Back")) μ(Τ.Main);Γ+=ĸ;Γ+="1. Dock to your docking station\n";Γ+="2. Select Record path & set home\n";Γ+="3. Fly the path to the ores\n";
Γ+="4. Select stop path recording\n";Γ+="5. Align ship in mining direction\n";Γ+="6. Select Setup job and start\n";}if(Ѐ==2) Γ="Fatal setup error\nNext scan: "+Ő+"s\n";if(Ɨ) Γ="Recompile script now";int ΕА=Γ.Split('\n').Length;for(int i=ΕА;i<=10;i++) Γ+="\n";Γ+=ΔЇ;Γ+="Last: "+Ρ+"\n";
return Γ;}void ΔЌ(bool ΖΚ,float щ){υ();Ƨ(true,false);if(ΖΚ) Ъ(ref Ŧ,щ,ο.ΓΓ,false);else Ъ(ref ĝ,щ,ο.ΓΓ,false);Δφ();Ě(true,true,0,0);}float Γχ(float ζ,float[]Ʒ){float Ϊ=Ʒ[0];for(int i=Ʒ.Length-1;i>=0;i--)
if(ζ<Ʒ[i]) Ϊ=Ʒ[i];return Ϊ;}String ƫ(ref int Ƞ){String Ϊ="";if(Ƞ>=Βφ.Count) Ƞ=-1;if(Ƞ>=0) Ϊ=Βφ[Ƞ].CustomName;Ƞ++;return Ϊ;}void ΑΗ(string έ){if(γ!=Ξ.Њ) return;if(έ=="") return;IMyTerminalBlock Σ=ψ.GetBlockWithName(έ);if(Σ==null||!(Σ is IMyTimerBlock)){Ρ="Timerblock "+έ+" not found!";
return;}((IMyTimerBlock) Σ).Trigger();}void ň(ref int value,int Ű,int Ǽ,int Βί){if(Ű==0) return;if(value<Ǽ&&Βί>0||value<=Ǽ&&Βί<0){value+=Βί;return;}int ΕЍ=Math.Abs(Ű);int ΒΣ=0;int Αϊ=1;while(true){ΒΣ+=Αϊ*ΕЍ*10;if(Ű<0&&value-Ǽ<=ΒΣ) break;if(Ű>0&&value-Ǽ<ΒΣ) break;
Αϊ++;}value+=Αϊ*Ű;}void ȳ(bool Ηί){ы=Math.Max(ы,1);я=Math.Max(я,1);Ш=Math.Max(Ш,0);Ě(Ј==Τ.ż,false,0,0);}bool ę(ref float value,bool Ζφ,ο ν,String ā,String ΖЇ){if(ā=="") return false;float Ĺ=-1;bool Γί=false;if(ā.ToUpper()==ΖЇ) Γί=true;else if(!float.TryParse(ā,out Ĺ)) return false;
else Ĺ=Math.Max(0,Ĺ);if(Ζφ) Ĺ=(float) Math.Round(Ĺ);Ъ(ref value,Ĺ,ν,Γί,false);return true;}void Ъ(ref float value,float щ,ο ν,bool š){Ъ(ref value,value+щ,ν,š,true);}void Ъ(ref float value,float Ģ,ο ν,bool š,bool ΕΦ){float Ǒ=0,і=0;if(ν==ο.Ų){Ǒ=0.5f;і=10f;}if(ν==ο.ƹ){Ǒ=0.1f;і=1f;}
if(ν==ο.ź){Ǒ=50f;і=100f;}if(ν==ο.ΑЋ){Ǒ=5f;і=30f;}if(ν==ο.ƥ){Ǒ=1f;і=25f;}if(ν==ο.Ƽ){Ǒ=10f;і=95f;}if(ν==ο.ΑЃ){Ǒ=10f;і=90f;}if(ν==ο.Εφ){Ǒ=10f;і=1800;}if(ν==ο.ΓΓ){Ǒ=0.0f;і=0.75f;}if(Ģ==-1&&š){value=-1;return;}if(value==-1) š=false;
bool ΓΧ=Ģ<Ǒ||Ģ>і;if(ΓΧ&&ΕΦ){if(Ģ<value) value=і;else if(Ģ>value) value=Ǒ;}else value=Ģ;if(ΓΧ&&š) value=-1;else value=Math.Max(Ǒ,Math.Min(value,і));value=(float) Math.Round(value,2);}void ΑΥ(bool ΕЀ){if(ΕЀ) к=Math.Max(0,к-1);else к++;ΑІ(true);}T Ȕ<T>(T ζ){int Α=Array.IndexOf(Enum.GetValues(ζ.GetType()),ζ);
Α++;if(Α>=ΕΡ(ζ)) Α=0;return(T) Enum.GetValues(ζ.GetType()).GetValue(Α);}int ΕΡ<T>(T value){return Enum.GetValues(value.GetType()).Length;}void ΒΕ(){Ż.Clear();for(int i=0;i<Φ.Count;i++) Ż.Add(Φ[i]);Φ.Clear();ƣ=true;ΑЉ=new Ω(Θ);Αξ=new Ω(Ε);Θ.α=false;if(Μ==Κ.ΰ) Ε.α=false;for(int i=0;i<х.Count;i++)
if(!ǫ.Contains(х.Keys.ElementAt(i)))
ǫ.Add(х.Keys.ElementAt(i));Ƿ=false;ħ=false;Ĥ=false;μ(Τ.Γϋ);}void ΓΦ(){if(Ƿ) Θ=ΑЉ;if(ħ) Ε=Αξ;if(Ĥ){Φ.Clear();for(int i=0;i<Ż.Count;i++) Φ.Add(Ż[i]);}ƣ=false;υ();μ(Τ.Main);}void ΗΓ(){if(!ƣ) return;if(Ψ!=Β.ш){ΓΦ();return;}if(!ΑЉ.α) Ƿ=false;if(!Αξ.α) ħ=false;if(Ż.Count<=1) Ĥ=false;
IMyShipConnector ǒ=Ч(MyShipConnectorStatus.Connectable);if(ǒ==null) ǒ=Ч(MyShipConnectorStatus.Connected);if(ǒ!=null){if(Math.Round(ć,2)<=0.20) ΑΪ++;else ΑΪ=0;if(ΑΪ>=5){if(Μ==Κ.ΰ&&(Θ.α||Ƿ)&&Vector3.Distance(Θ.Δ,ǒ.GetPosition())>5){Ε.ί=Υ.WorldMatrix.Forward;Ε.φ=Υ.WorldMatrix.Left;
Ε.β=Υ.WorldMatrix.Down;Ε.ς=Υ.GetNaturalGravity();Ε.Δ=ǒ.GetPosition();Ε.α=true;Ε.д=ǒ.Position;}else{Θ.ί=Υ.WorldMatrix.Forward;Θ.φ=Υ.WorldMatrix.Left;Θ.β=Υ.WorldMatrix.Down;Θ.ς=Υ.GetNaturalGravity();Θ.Δ=ǒ.GetPosition();Θ.α=true;Θ.д=ǒ.Position;}}}double Βϋ=-1;if(Φ.Count>0) Βϋ=Vector3.Distance(κ,Φ.Last().Δ);
double ΕБ=Math.Max(1.5,Math.Pow(ć/100.0,2));double Γω=Math.Max(ć*ΕБ,2);ΔΛ=Γω;if((Βϋ==-1)||Βϋ>=Γω){Ω Χ=new Ω(κ,ƚ,ƺ,Ʊ,Υ.GetNaturalGravity());Χ.ΕЋ(Ǻ,ǫ);Φ.Add(Χ);}}Ω ȃ(){if(Μ!=Κ.ΰ) return Θ;return Γμ;}void ĺ(Ω Ϋ,Ξ М){Γμ=Ϋ;if(γ==Ξ.Њ) э=М;}bool Ǫ(Ω Ϋ,float Є,bool ΕΝ,out Vector3 Ќ)
{if(ΕΝ){Vector3I ΑЈ=new Vector3I((int) Ϋ.д.X,(int) Ϋ.д.Y,(int) Ϋ.д.Z);IMySlimBlock Σ=Me.CubeGrid.GetCubeBlock(ΑЈ);if(Σ==null||!(Σ.FatBlock is IMyShipConnector)){Ќ=new Vector3();return false;}Vector3 Εγ=Ф(Υ,Σ.FatBlock.GetPosition()-κ);Vector3 Εμ=Ф(Υ,Σ.FatBlock.WorldMatrix.Forward);Ќ=Ϋ.Δ-ΒΨ(Ϋ.ί,Ϋ.β*-1,Εγ)-ΒΨ(Ϋ.ί,Ϋ.β*-1,Εμ)*Є;
return true;}else{Ќ=Ϋ.Δ;return true;}}Vector3 Ȓ(int Εύ,int ΖΫ,bool ΖЈ){if(!ΖЈ&&Δγ) return ΒЄ;float ΕΨ=((Р-1f)/2f)-Εύ;float ΕЈ=((в-1f)/2f)-ΖΫ;ΒЄ=Ε.Δ+Ε.φ*ΕΨ*ȋ+ą*-1*ΕЈ*Ǵ;Δγ=true;return ΒЄ;}Vector3 Βέ(Vector3 ΕΘ,float ΖБ){return ΕΘ+(ǭ*ΖБ);}ά Βτ(){float Џ=-1;
ά Ϊ=ά.ǩ;if(Μ!=Κ.ΰ){if(γ!=Ξ.й){Vector3 Ѓ=Ē(ǭ,ą*-1,κ-Ε.Δ);if(Math.Abs(Ѓ.X)<=(float)(Р*ȋ)/2f&&Math.Abs(Ѓ.Y)<=(float)(в*Ǵ)/2f){if(Ѓ.Z<=-1&&Ѓ.Z>=-đ*2) return ά.ΑΒ;if(Ѓ.Z>-1&&Ѓ.Z<σ*2) return ά.ǩ;}if(ȡ(Ε.Δ,ref Џ)) Ϊ=ά.ǩ;}if(Θ.α){if(ȡ(Θ.Δ,ref Џ)) Ϊ=ά.ǯ;
for(int i=0;i<Φ.Count;i++)
if(ȡ(Φ[i].Δ,ref Џ)) Ϊ=ά.Ȍ;if(Vector3.Distance(κ,Θ.Δ)<dockDist*σ) Ϊ=ά.ǯ;if(Ч(MyShipConnectorStatus.Connectable)!=null||Ч(MyShipConnectorStatus.Connected)!=null)
Ϊ=ά.ǯ;}}else{Vector3 Ќ=new Vector3();IMyShipConnector Ǯ=Ч(MyShipConnectorStatus.Connected);if(Θ.α){if(ȡ(Θ.Δ,ref Џ)) Ϊ=ά.ǯ;if(Ǫ(Θ,dockDist,true,out Ќ))
if(ȡ(Ќ,ref Џ)) Ϊ=ά.ǯ;if(Ǯ!=null&&Vector3.Distance(Ǯ.GetPosition(),Θ.Δ)<5)
return ά.Βψ;}for(int i=0;i<Φ.Count;i++)
if(Vector3.Distance(Φ[i].Δ,Θ.Δ)>dockDist*σ&&Vector3.Distance(Φ[i].Δ,Ε.Δ)>dockDist*σ)
if(ȡ(Φ[i].Δ,ref Џ)) Ϊ=ά.Ȍ;if(Ε.α){if(ȡ(Ε.Δ,ref Џ)) Ϊ=ά.ǩ;if(Ǫ(Ε,dockDist,true,out Ќ))
if(ȡ(Ќ,ref Џ)) Ϊ=ά.ǩ;if(Ǯ!=null&&Vector3.Distance(Ǯ.GetPosition(),Ε.Δ)<5)
return ά.ΒЉ;}}return Ϊ;}bool ȡ(Vector3 Ќ,ref float Џ){float Є=Vector3.Distance(Ќ,κ);if(Є<Џ||Џ==-1){Џ=Є;return true;}return false;}void Βω(){if(Ѐ>0){Ρ="Setup error! Can't start";return;}if(Μ==Κ.ΰ){ċ();return;}Ε.Δ=κ;Ε.ς=Υ.GetNaturalGravity();Ε.ί=ƚ;Ε.β=ƺ;Ε.φ=Ʊ;
ǭ=ф.WorldMatrix.Forward;ą=Ε.β;if(ǭ==Υ.WorldMatrix.Down) ą=Υ.WorldMatrix.Backward;Ƨ(true,true);Ο(Β.Ć);ΒЀ();}void Ƨ(bool ǔ,bool Ζλ){if(γ==Ξ.й&&!ǔ) return;bool ΖΡ=ǔ||γ==Ξ.ΒΤ||Р!=ы||в!=я||ΑΙ!=Ȋ;if(ΖΡ){if(γ!=Ξ.й){γ=Ξ.Ə;Ȓ(ρ,π,Ζλ);Ρ="Job changed, lost progress";}ΑΙ=Ȋ;
Р=ы;в=я;π=0;ρ=0;ı=0;Ț=0;Н=0;к=0;ΑІ(true);}}void ΓΕ(){о(κ,0);ц(Ǻ,true);}void ΒЀ(){ǰ(У.Ɖ);ΓΕ();Ƃ(Ǳ,false);ǟ(ΑΩ);γ=Ξ.Њ;Γό(true);э=γ;μ(Τ.Œ);Ζβ();ǌ=true;ǁ=0;for(int i=Ž.Count-1;i>=0;i--)
if(Ŷ(Ž[i],false)) ǁ++;if(ǁ>0) Ρ="Started with damage";}void υ(){if(γ==Ξ.Њ){γ=Ξ.ΓΖ;Ρ="Job paused";}Ο(Β.ш);э=γ;ΑΑ(false,0,0,0,0);ΒΗ();ΔΕ(new Vector3(),false);Γρ();Αη(ChargeMode.Auto);Αύ(false);Γϊ(true);Ȏ(Β.ш);Ě(false,false,0,0);ц(ξ,false);ц(е,true);ǟ(true);Ʃ=false;ǌ=false;
œ=false;Ŭ=false;if(Ј!=Τ.Main&&Ј!=Τ.ΑΜ&&Ј!=Τ.Αφ&&Ј!=Τ.Ɛ)
μ(Τ.Main);}void ċ(){ά Г=Βτ();if(Μ==Κ.ΰ){if(!Ε.α||!Θ.α) return;ΒЀ();bool ΒЇ=Vector3.Distance(κ,Θ.Δ)<Vector3.Distance(κ,Ε.Δ);if(Ŋ==Ξ.ĥ) ΒЇ=true;if(Ŋ==Ξ.ŀ) ΒЇ=false;if(ΒЇ){ĺ(Θ,Ξ.ĥ);switch(Г){case ά.Βψ:Ο(Β.ȥ);break;case ά.Ȍ:Ο(Β.Э);break;case ά.ǯ:Ο(Β.ȓ);break;default:Ο(Β.ȫ);break;
}}else{ĺ(Ε,Ξ.ŀ);switch(Г){case ά.ΒЉ:Ο(Β.ȥ);break;case ά.ǩ:Ο(Β.ȓ);break;case ά.Ȍ:Ο(Β.Э);break;default:Ο(Β.ȫ);break;}}}else{if(γ!=Ξ.ΓΖ&&γ!=Ξ.Ə) return;bool ΕЉ=γ==Ξ.Ə;ΒЀ();bool ΒΔ=Ŵ(false)&&Θ.α;switch(Г){case ά.ǩ:Ο(ΒΔ?Β.ě:Β.Ć);break;case ά.Ȍ:Ο(ΒΔ?Β.ǜ:Β.Э);break;case ά.ǯ:Ο(ΒΔ?Β.ȓ:Β.Ȃ);break;
case ά.ΑΒ:{if(Ț!=к||ΕЉ) Ο(Β.Ȣ);else Ο(Β.Ź);}break;default:break;}}}void Ă(){if(γ==Ξ.й&&!Θ.α) return;if(Μ==Κ.ΰ&&(!Ε.α||!Θ.α)) return;Ρ="Move to job";ά Г=Βτ();if(Μ==Κ.ΰ){ĺ(Ε,Ξ.ŀ);switch(Г){case ά.ǩ:Ο(Β.ȓ);break;case ά.Ȍ:Ο(Β.Э);break;case ά.ΒЉ:return;default:Ο(Β.ȫ);break;
}Ȏ(Β.ȥ);}else{switch(Г){case ά.ǩ:Ο(Β.Э);break;case ά.Ȍ:Ο(Β.Э);break;case ά.ǯ:Ο(Β.Ȃ);break;case ά.ΑΒ:Ο(Β.Ȣ);break;default:break;}if(γ==Ξ.й) Ȏ(Β.Э);else Ȏ(Β.Ĕ);Ʃ=true;}ΓΕ();μ(Τ.ΑЇ);Ƃ(Ǳ,false);э=Ξ.ƭ;}void ư(){if(!Θ.α) return;Ρ="Move home";ά Г=Βτ();if(Μ==Κ.ΰ){ĺ(Θ,Ξ.ĥ);switch(Г)
{case ά.Ȍ:Ο(Β.ǜ);break;case ά.ǯ:Ο(Β.ȓ);break;case ά.Βψ:return;default:Ο(Β.ȫ);break;}Ȏ(Β.ȥ);}else{if(Ч(MyShipConnectorStatus.Connected)!=null) return;if(Ч(MyShipConnectorStatus.Connectable)!=null){Ο(Β.Ÿ);Ȏ(Β.Ȃ);return;}switch(Г){case ά.ǩ:Ο(Β.ě);break;case ά.Ȍ:Ο(Β.ǜ);break;case ά.ǯ:Ο(Β.ǜ);break;
case ά.ΑΒ:Ο(Β.ď);break;default:break;}Ȏ(Β.Ȃ);}ΓΕ();μ(Τ.ΑЇ);Ƃ(Ǳ,false);э=Ξ.Ɠ;}void Ο(Β Βυ){if(Βυ==Β.ш) ŷ=Β.ш;if(ŷ!=Β.ш&&Ψ==ŷ&&Βυ!=ŷ){υ();return;}Ђ=true;Ψ=Βυ;}void Ȏ(Β М){this.ŷ=М;}ȍ Εθ(int ƀ,bool ќ){if(ќ){ч=null;ρ=0;π=0;}if(Ȋ==ǘ.Ǌ){int Δω=ƀ+1;π=(int) Math.Floor(І(ƀ,Р));
if(π%2==0) ρ=ƀ-(π*Р);else ρ=Р-1-(ƀ-(π*Р));if(π>=в) return ȍ.ΓΔ;else return ȍ.ΑЂ;}else if(Ȋ==ǘ.Γψ){if(ч==null) ч=new int[]{0,-1,0,0};int ΔЎ=(int) Math.Ceiling(Р/2f);int ΔΪ=(int) Math.Ceiling(в/2f);int ΖΝ=(int) Math.Floor(Р/2f);int Ζρ=(int) Math.Floor(в/2f);
int ś=0;while(ч[2]<Math.Pow(Math.Max(Р,в),2)){if(ś>200) return ȍ.ΖЊ;ś++;ч[2]++;if(-ΔЎ<ρ&&ρ<=ΖΝ&&-ΔΪ<π&&π<=Ζρ){if(ч[3]==ƀ){this.ρ=ρ-1+ΔЎ;this.π=π-1+ΔΪ;return ȍ.ΑЂ;}ч[3]++;}if(ρ==π||(ρ<0&&ρ==-π)||(ρ>0&&ρ==1-π)){int Ζπ=ч[0];ч[0]=-ч[1];ч[1]=Ζπ;
}ρ+=ч[0];π+=ч[1];}}return ȍ.ΓΔ;}void ΖΖ(){if(Ψ==Β.Ć){if(Ђ){ύ=0;if(Ț!=к) ı=0;Ț=к;}if(ύ==0){ȍ Ϊ=Εθ(к,Ђ);if(Ϊ==ȍ.ΓΔ){γ=Ξ.ΒΤ;Ρ="Job done";if(ȧ&&Θ.α){Ο(Β.ě);Ȏ(Β.Ȃ);э=Ξ.Ɠ;}else{Ο(Β.ŕ);Ȏ(Β.Ĕ);э=Ξ.ƭ;}return;}if(Ϊ==ȍ.ΑЂ){ύ=1;ц(ξ,true);ж=Ȓ(ρ,π,true);о(ж,10);
Х(Ε.β,Ε.ί,Ε.φ,false);}}else{if(З<wpReachedDist){Ο(Β.Ź);return;}}}if(Ψ==Β.Ź){if(Ђ){ц(ξ,true);ǟ(false);ж=Ȓ(ρ,π,false);о(Βέ(ж,0),0);Х(Ε.β,Ε.ί,Ε.φ,false);ύ=1;Ь=0;Т=0;Ɔ=0;Βλ=-1;đ=Ш;Αά=true;}if(!Ασ()){Ο(Β.ď);return;}if(Ŵ(true)){Γτ=Ȑ("","ORE",А.Ȯ);if((Й==ϊ.Βς||Й==ϊ.Ƒ||
Й==ϊ.ΑΡ||Й==ϊ.Ɗ)&&Μ!=Κ.ǐ)
Ο(Β.Ƌ);else if((Й==ϊ.ΓΜ||Й==ϊ.Βό)&&Μ!=Κ.ǐ)
Ο(Β.Απ);else
Ο(Β.ď);return;}Н=Vector3.Distance(κ,ж);if(Н>ı){ı=Н;Αά=false;}if(Μ==Κ.ǐ&&ΓΨ()==MyDetectedEntityType.SmallGrid)
Т+=2;else Т-=2;Т=Math.Max(100,Math.Min(400,Т));if(ύ>0&&ύ<Т){if(Н>Ь){if(Т>150) Ь=Н;else Ь=(float) Math.Ceiling(Н);ύ=1;}else ύ++;}else{if(ύ>0){Ρ="Ship stuck! Retrying";Ь=Н;ύ=0;Ě(false,true,0,σ*sensorRange);}о(Βέ(ж,Math.Max(0,Ь-σ)),ΒΥ(false));if(З<=wpReachedDist/2){ύ=1;Ь=0;}
return;}Ě(false,true,σ*sensorRange,0);Vector3 ΕΜ=ж+ǭ*Н;bool Γή=false;if(Vector3.Distance(ΕΜ,κ)>0.3f){Vector3 Εή=ж+ǭ*(Н+0.1f);о(Εή,4);Γή=true;}else{float ї=ΒΥ(true);Vector3 ΓЎ=Βέ(ж,Math.Max(Ш+1,Н+1));Ǘ(true,false,false,ΓЎ,ΓЎ-ж,ї,ї);}bool ΒΧ=false;if(Ǔ==ѓ.Αθ||Ǔ==ѓ.Βά)
{if(!Γή){float ΒЈ=0;foreach(IMyTerminalBlock Ǟ in ξ)
ΒЈ+=ΕΩ(Ǟ,"","",Ǔ==ѓ.Βά?new string[]{"STONE"}:null);if(ΒЈ>Βλ||Н<Ш||Αά){Αλ=0;Ɔ=Н;đ=(int)(Math.Max(đ,Ɔ)+σ/2);}else{ΒΧ=Н-Ɔ>2&&Αλ>=20;Αλ++;}Βλ=ΒЈ;}}else ΒΧ=Н>=đ;if(Ț!=к){Ο(Β.Ȣ);Н=0;return;}if(ΒΧ){к++;Ο(Β.Ȣ);Н=0;return;}}if(Ψ==Β.Ȣ||Ψ==Β.ď||Ψ==Β.Ƌ)
{if(Ђ){ж=Ȓ(ρ,π,false);Х(Ε.β,Ε.ί,Ε.φ,false);ц(ξ,Ł);ǟ(false);Ь=Vector3.Distance(κ,ж);Ě(false,true,0,σ*sensorRange);}о(ж,ΒΥ(false));if(Vector3.Distance(κ,ж)>=Ь+5){ц(ξ,false);ǟ(true);Ρ="Can´t return!";}if(З<wpReachedDist){if(Ψ==Β.Ȣ&&Ʃ) Ο(Β.ŕ);if(Ψ==Β.Ȣ) Ο(Β.Ć);if(Ψ==Β.Ƌ) Ο(Β.ΒЊ);
if(Ψ==Β.ď){if(Θ.α) Ο(Β.ě);else{υ();Ă();Ρ="Can´t return, no dock found";}}return;}}if(Ψ==Β.ǜ||Ψ==Β.Э){if(Ψ==Β.Э&&γ==Ξ.Њ&&Μ!=Κ.ΰ){if(!Ασ()||Ŵ(true)){Ο(Β.ǜ);return;}}bool ΒΑ=false;bool ΒΓ=false;bool ΔΥ=false;float Ń=0;bool ΓΡ=false;Ω Χ=null;if(Ђ){if(Ψ==Β.ǜ||Μ==Κ.ΰ)
{Ω Ϋ=ȃ();η=new Βώ();η.Е=Ϋ;η.ť=followPathDock*σ;η.ΒЎ=useDockDirectionDist*σ;η.Ń=10;η.ļ.Add(Ϋ.Δ);Vector3 Ĵ=new Vector3();if(Ǫ(Ϋ,dockDist*σ,true,out Ĵ))
η.ļ.Add(Ĵ);else η.ť*=1.5f;if(Μ==Κ.ΰ){if(Ϋ==Θ) η.ƶ=Ε.Δ;if(Ϋ==Ε) η.ƶ=Θ.Δ;η.Αι=dockDist*σ*1.1f;}}else if(Ψ==Β.Э){η=new Βώ();η.Е=Ε;η.ť=followPathJob*σ;η.ΒЎ=useJobDirectionDist*σ;η.Ń=10;η.ƶ=Θ.Δ;η.Αι=dockDist*σ*1.1f;η.ļ.Add(Ε.Δ);if(γ==Ξ.й){if(!Θ.α||Φ.Count==0){υ();return;}
float ΖΔ=Vector3.Distance(Φ.First().Δ,Θ.Δ);float ΕΧ=Vector3.Distance(Φ.Last().Δ,Θ.Δ);if(ΖΔ<ΕΧ) η.Е=Φ.Last();else η.Е=Φ.First();}}ŧ=new Vector3();ΓΡ=!ΗΡ(κ);ц(ξ,false);ǟ(true);ѕ=-1;double ǡ=-1;for(int i=Φ.Count-1;i>=0;i--){if(Vector3.Distance(Φ[i].Δ,η.ƶ)<=η.Αι) continue;
double Є=Vector3.Distance(Φ[i].Δ,κ);if(ǡ==-1||Є<ǡ){ѕ=i;ǡ=Є;}}ĕ=Ζό(η.Е.Δ,ѕ);Ǚ=null;}ΖЍ(Φ,ĕ,η.ļ,η.ť,Ђ,ref ύ);for(int i=0;i<η.ļ.Count;i++){float Є=Vector3.Distance(κ,η.ļ[i]);if(Є<=η.ť) ΒΑ=true;if(Є<=η.ΒЎ) ΒΓ=true;}if(ΒΓ) Ń=η.Ń;float ΗΧ=Ǚ!=null?Ǚ.О:ć;
float Ζξ=(float) Math.Max(ć*0.1f*σ,wpReachedDist);if((З<Ζξ)||Ђ){if(!Ђ) ѕ+=ĕ;if(ĕ==0||ѕ>Φ.Count-1||ѕ<0)
ΒΑ=true;else{Βν=ĕ>0?Φ.Count-1-ѕ:ѕ;Χ=Φ[ѕ];Ǚ=Χ;if(ѕ>=1&&ѕ<Φ.Count-1)
ŧ=Χ.Δ-Φ[ѕ-ĕ].Δ;else Ǚ=null;ϋ=Χ.Δ;ΔΥ=true;}}if(ΒΓ)
Х(η.Е.β,η.Е.ί,η.Е.φ,false);else if(ΓΡ)
Αψ(η.Е.β,10,true);else if(ΔΥ&&Χ!=null){if(ĕ>0) Х(Χ.β,Χ.ί,Χ.φ,90,false);else Х(Χ.β,-Χ.ί,-Χ.φ,90,false);}Ǘ(true,false,true,ϋ,ŧ,Ǚ==null?0:Ǚ.О,Ń);if(ΒΑ){Βν=0;if(Ψ==Β.ǜ||Μ==Κ.ΰ){Ο(Β.ȓ);return;}if(Ψ==Β.Э&&Ʃ){Ο(Β.ŕ);return;}if(Ψ==Β.Э){Ο(Β.Ć);return;}
}}if(Ψ==Β.ȓ||Ψ==Β.Βγ){Ω Ϋ=ȃ();if(Ђ){if(!Ǫ(Ϋ,dockDist*σ,true,out ϋ)){ǰ(У.Ŝ);υ();return;}о(ϋ,0);Αψ(Ϋ.β,90,true);}if(З<followPathDock*σ&&З!=-1){о(ϋ,10);Х(Ϋ.β,Ϋ.ί,Ϋ.φ,false);}if(Ч(MyShipConnectorStatus.Connectable)!=null||Ч(MyShipConnectorStatus.Connected)!=null)
{Ο(Β.Ÿ);return;}if(З<wpReachedDist/2&&З!=-1){Ο(Β.Ţ);return;}}if(Ψ==Β.Ţ||Ψ==Β.Ĕ){if(Ђ){if(Ψ==Β.Ţ){Ω Ϋ=ȃ();if(!Ǫ(Ϋ,dockDist*σ,true,out ϋ)){ǰ(У.Ŝ);υ();return;}Ǘ(true,true,false,ϋ,0);Х(Ϋ.β,Ϋ.ί,Ϋ.φ,10,false);}if(Ψ==Β.Ĕ){Х(Ε.β,Ε.ί,Ε.φ,0.5f,false);ϋ=Ε.Δ;
Ǘ(true,true,false,ϋ,0);}}if(ƌ){ΑΑ(false,0,0,0,0);if(Ψ==Β.Ţ) Ο(Β.Ÿ);if(Ψ==Β.Ĕ) υ();return;}}if(Ψ==Β.Ÿ){if(Ч(MyShipConnectorStatus.Connected)!=null){if(Μ==Κ.ΰ) Ο(Β.ȥ);else Ο(Β.Ȃ);return;}Ω Ϋ=ȃ();if(Ђ){Т=0;ΖΕ=DateTime.Now;ύ=0;Х(Ϋ.β,Ϋ.ί,Ϋ.φ,false);}Vector3I ΑЈ=new Vector3I((int) Ϋ.д.X,(int) Ϋ.д.Y,(int) Ϋ.д.Z);
IMySlimBlock ΓЈ=Me.CubeGrid.GetCubeBlock(ΑЈ);float ΓА=dockingSpeed;float Ει=dockingSpeed*5;float Δρ=Math.Max(1.5f,Math.Min(5f,σ*0.15f));if(!Ǫ(Ϋ,0,true,out ϋ)||!Ǫ(Ϋ,Δρ,true,out ŧ)||
ΓЈ==null||!ΓЈ.FatBlock.IsFunctional){ǰ(У.Ŝ);υ();return;}if(Т==1||(Vector3.Distance(κ,ϋ)<=Δρ*1.1f&&!Ђ))
Т=1;else{Vector3 Εο=Ф(Υ,ŧ-κ);Vector3 ΒΛ=Ф(Υ,Υ.GetNaturalGravity());float Ζτ=ƿ(Εο,ΒΛ,null);ΓА=Math.Min(Ει,Ζτ);}Ǘ(true,false,false,ϋ,ϋ-κ,dockingSpeed,ΓА);if(Ђ) Ь=(float) З;IMyShipConnector ΒΚ=Ч(MyShipConnectorStatus.Connectable);if(ΒΚ!=null){Ǘ(false,false,false,ϋ,0);
if(ύ>0) ύ=0;ύ--;if(ύ<-5){ΒΚ.Connect();if(ΒΚ.Status==MyShipConnectorStatus.Connected){if(Μ==Κ.ΰ) Ο(Β.ȥ);else Ο(Β.Ȃ);ΒΗ();Ƃ(Ǳ,true);return;}}}else{float Γθ=(float) Math.Round(З,1);if(Γθ<Ь){ύ=-1;Ь=Γθ;}else ύ++;if(ύ>20){Ο(Β.Βγ);return;}}}if(Ψ==Β.Ȃ||Ψ==Β.ȥ||
Ψ==Β.ΒΖ||Ψ==Β.ΑΨ||Ψ==Β.Ġ){bool Βπ=false,ΑЁ=false;if(Μ==Κ.ΰ){if(ȃ()==Θ) Βπ=true;else if(ȃ()==Ε) ΑЁ=true;}if(Ђ){œ=false;if(Ч(MyShipConnectorStatus.Connected)==null){Ο(Β.ȫ);return;}ΒΗ();if(Βπ) ΑΗ(χ.Ǐ);if(ΑЁ) ΑΗ(τ.Ǐ);Ė=false;Ȉ=false;Ȅ=false;Ř=false;}if(Ч(MyShipConnectorStatus.Connected)==null){υ();ǰ(У.ΓΤ);return;}
if(γ!=Ξ.Њ||н==-1||ǝ==г.None) Ȉ=true;else if(ǳ>=100f) Ȉ=true;else if(ǳ<=99f) Ȉ=false;if(γ!=Ξ.Њ||м==-1||р.Count==0) Ȅ=true;else if(ǽ>=100f) Ȅ=true;else if(ǽ<=99) Ȅ=false;if(γ!=Ξ.Њ||П==-1||Ȥ.Count==0) Ř=true;else Ř=Ą>=П;Ļ Ю=null;if(Βπ) Ю=χ;
if(ΑЁ) Ю=τ;if(Ю!=null&&(Ю.Ѕ==δ.Ǝ||Ю.Ѕ==δ.Ƙ)) Ȉ=true;if(Ю!=null&&(Ю.Ѕ==δ.Βδ)) if(!Ė) Ȉ=false;if(Ю!=null&&(Ю.Ѕ==δ.ΑЎ||Ю.Ѕ==δ.ΑΤ)) Ȅ=true;if(Ю!=null&&(Ю.Ѕ==δ.Αί)) if(!Ė) Ȅ=false;if(ȏ){ChargeMode Δΰ=Ȉ?ChargeMode.Auto:ChargeMode.Recharge;if(Ю!=null&&(Ю.Ѕ==δ.Ƙ||Ю.Ѕ==δ.Ǝ))
Δΰ=ChargeMode.Discharge;Αη(Δΰ);Αύ(!Ȅ);}if(!Ė){if(Μ==Κ.ΰ)
Ė=γ!=Ξ.Њ||ΖΓ(Ђ,true)||Ŭ;else
Ė=γ!=Ξ.Њ||Γφ();}else{if(!Ȉ) Ο(Β.Ġ);if(!Ȅ) Ο(Β.ΑΨ);if(!Ř) Ο(Β.ΒΖ);Ђ=false;}if(Ė&&Ȉ&&Ȅ&&Ř){Αη(ChargeMode.Auto);Αύ(false);if(γ==Ξ.Њ){if(Μ==Κ.ΰ){if(ȃ()==Θ) ΑΗ(χ.ў);else if(ȃ()==Ε) ΑΗ(τ.ў);if(ȃ()==Θ) ĺ(Ε,Ξ.ŀ);else ĺ(Θ,Ξ.ĥ);}}Ο(Β.ȫ);return;}}if(Ψ==Β.ȫ){if(Ђ){IMyShipConnector Ǯ=Ч(MyShipConnectorStatus.Connected);
if(Ǯ==null){Ο(Β.Э);return;}IMyShipConnector ǲ=Ǯ.OtherConnector;ΔΦ(Ǯ,false);Ƃ(Ǳ,false);Ω Ϋ=null;if(Vector3.Distance(Ǯ.GetPosition(),Θ.Δ)<5f&&Θ.α) Ϋ=Θ;if(Vector3.Distance(Ǯ.GetPosition(),Ε.Δ)<5f&&Ε.α) Ϋ=Ε;if(Ϋ!=null){if(!Ǫ(Ϋ,dockDist*σ,true,out ϋ)){ǰ(У.Ŝ);υ();return;}
о(ϋ,5);Х(Ϋ.β,Ϋ.ί,Ϋ.φ,false);}else о(κ+ǲ.WorldMatrix.Forward*dockDist*σ,5);if(γ==Ξ.Њ) ǰ(У.Ɖ);}if(З<wpReachedDist){ц(е,true);Ο(Β.Э);return;}}if(Ψ==Β.ŕ){if(Ђ){ǟ(true);ц(ξ,false);ϋ=Ε.Δ;о(ϋ,20);Х(Ε.β,Ε.ί,Ε.φ,false);}if(З<wpReachedDist/2){Ο(Β.Ĕ);return;}}if(Ψ==Β.ě){
if(Ђ){ǟ(true);ц(ξ,false);int Џ=-1;double ǡ=-1;for(int i=Φ.Count-1;i>=0;i--){double Є=Vector3.Distance(Φ[i].Δ,κ);if(ǡ==-1||Є<ǡ){Џ=i;ǡ=Є;}}if(Џ==-1){Ο(Β.ǜ);return;}ϋ=Φ[Џ].Δ;о(ϋ,10);Х(Ε.β,Ε.ί,Ε.φ,false);}if(З<wpReachedDist){Ο(Β.ǜ);return;}}if(Ψ==Β.ΒЊ)
{bool ǚ=false;if(Ђ){ǟ(true);if((Й==ϊ.Βς||Й==ϊ.Ƒ)&&ƛ()&&
İ(ǭ,Υ.GetNaturalGravity())<25&&Р>=2&&в>=2){Vector3 ŗ=κ;if(ρ>0&&π<в-1) ŗ=Ȓ(ρ-1,π+1,true);else if(ρ<Р-1&&π<в-1) ŗ=Ȓ(ρ+1,π+1,true);else if(ρ<Р-1&&π>0) ŗ=Ȓ(ρ+1,π-1,true);else if(ρ>0&&π>0) ŗ=Ȓ(ρ-1,π-1,true);else ǚ=true;if(!ǚ) о(ŗ,10);
}else ǚ=true;}if(З<wpReachedDist/2) ǚ=true;if(ǚ){Ο(Β.Ʀ);return;}}if(Ψ==Β.Απ||Ψ==Β.Ʀ){if(Ђ){Ǘ(true,true,false,κ,0);ц(ξ,false);ǟ(true);ύ=-1;Т=Й==ϊ.ΑΡ||Й==ϊ.Ɗ?0:-1;}bool ė=!Ασ();int Ɯ=Ȑ("STONE","ORE",А.Ȯ);if(Й==ϊ.Βό||Й==ϊ.Ɗ||Й==ϊ.Ƒ)
Ɯ+=Ȑ("ICE","ORE",А.Ȯ);bool ΕΠ=Ɯ>0;bool ΒΟ=false;if(Т>=0){float Ğ=(float) Math.Sin(ΓЊ(Т))*ȋ/3f;float Εχ=(float) Math.Cos(ΓЊ(Т))*Ǵ/3f;Vector3 ΕΙ=Ȓ(ρ,π,true)+ΒΨ(ǭ,ą*-1,new Vector3(Ğ,Εχ,0));о(ΕΙ,0.3f);if(З<Math.Min(ȋ,Ǵ)/10f) Т+=5f;if(Т>=360) Т=0;}if(ύ==-1||Ɯ<ύ){ύ=Ɯ;Ь=0;}
else{Ь++;if(Ь>50) ΒΟ=true;}if(!ΕΠ||ė||ΒΟ){if(!ė){int Ζύ=Ȑ("","ORE",А.Ȯ);if(Ŵ(true)) ė=true;else if(100-(І(Ζύ,Γτ)*100)<minEjection) ė=true;else ǰ(У.Ɖ);}if(ΒΟ&&ė) Ρ="Ejection failed";if(Ψ==Β.Ʀ){if(ė){if(Θ.α) Ο(Β.ě);else{υ();Ă();Ρ="Can´t return, no dock found";}}
else Ο(Β.Ć);}else if(ė) Ο(Β.ď);else Ο(Β.Ź);return;}}Ђ=false;}void ΖЍ(List<Ω>ȩ,int ω,List<Vector3>Ť,float ţ,bool ќ,ref int є){if(ќ){for(int i=0;i<ȩ.Count;i++) ȩ[i].О=0;є=-1;return;}if(ω==0) return;int щ=ω*-1;if(є==-1) є=щ>0?1:ȩ.Count-2;int ś=0;while(є>=1&&є<ȩ.Count-1)
{if(ś>50) return;ś++;try{if((щ<0&&є>=1)||(щ>0&&є<=ȩ.Count-2)){Ω ζ=ȩ[є];bool ΔΚ=false;for(int j=0;j<Ť.Count;j++)
if(Vector3.Distance(ζ.Δ,Ť[j])<=ţ){ΔΚ=true;break;}if(!ΔΚ){Ω Ƭ=ȩ[є-щ];Ω Δω=ȩ[є+щ];Vector3 ΗΛ=ζ.Δ-Δω.Δ;Vector3 ΓΑ=Ƭ.Δ-ζ.Δ;Vector3 ΕΟ=ζ.Δ+Vector3.Normalize(ΗΛ)*ΓΑ.Length();Vector3 Εϊ=Ƭ.Δ-ΕΟ;Vector3 ƒ=Ē(ω>0?ζ.ί:ζ.ί*-1,ζ.β*-1,Εϊ);Vector3 Ζκ=Ē(ω>0?ζ.ί:ζ.ί*-1,ζ.β*-1,ΓΑ);
Vector3 Ǆ=Ē(ω>0?ζ.ί:ζ.ί*-1,ζ.β*-1,ζ.ς);ζ.О=(float) Math.Sqrt(Math.Pow(Ƭ.О,2)+Math.Pow(ƿ(-Ζκ,Ǆ,ζ),2));for(int j=0;j<Ť.Count;j++)
if(Vector3.Distance(Ƭ.Δ,Ť[j])<=ţ){Vector3 ǂ=Ē(ω>0?ζ.ί:ζ.ί*-1,ζ.β*-1,Ť[j]-ζ.Δ);float ΕϏ=ƿ(-ǂ,Ǆ,ζ);ζ.О=Math.Min(ζ.О,ΕϏ)/2f;}if(ƒ.Length()==0) ƒ=new Vector3(0,0,1);Vector3 Ζί=Ē(ζ.ί,ζ.β*-1,ζ.ς);float ΖЏ=Ŗ(-ƒ,Ζί,ζ);float ΑΛ=І(ΖЏ,ă);float Ατ=(float) Math.Sqrt(І(ƒ.Length()*1.0f,0.5f*ΑΛ));
ζ.О=Math.Min(ζ.О,(ΓΑ.Length()/Ατ)*ǥ);}}}catch{return;}є+=щ;}є=-1;}void ΑІ(bool ќ){if(ќ){ū=0;return;}if(Μ==Κ.ΰ) return;float ǚ=к*Math.Max(1,Ш);if(Ț==к) ǚ+=Math.Min(Ш,Н);float Εζ=Р*в*Math.Max(1,Ш);ū=Math.Max(ū,(float) Math.Min(ǚ/Εζ*100.0,100));}MyDetectedEntityType ΓΨ()
{try{if(Ǭ(λ,true)&&!λ.LastDetectedEntity.IsEmpty()) return λ.LastDetectedEntity.Type;}catch{}return MyDetectedEntityType.None;}float ΒΥ(bool Ǥ){if(Μ==Κ.ǐ&&ΓΨ()==MyDetectedEntityType.None&&!Ŷ(λ,true))
return fastSpeed;else return Ǥ?ń:ņ;}void ΖЉ(){float ΔЋ=0,ΔЃ=0,ā=0,ΑЍ=0;for(int i=0;i<ț.Count;i++){IMyBatteryBlock ž=ț[i];if(!Ǭ(ž,true)) continue;ΔЋ+=ž.MaxStoredPower;ΔЃ+=ž.CurrentStoredPower;ā+=ž.CurrentInput;ΑЍ+=ž.CurrentOutput;}ǳ=(float) Math.Round(І(ΔЃ,ΔЋ)*100,1);
if(ā>=ΑЍ) ǝ=г.Ġ;else ǝ=г.ΔЈ;if(ā==0&&ΑЍ==0||ǳ==100.0) ǝ=г.ш;if(ț.Count==0) ǝ=г.None;}void ΖЀ(){float Δο=0;for(int i=0;i<р.Count;i++){IMyGasTank Δυ=р[i];if(!Ǭ(Δυ,true)) continue;Δο+=(float) Δυ.FilledRatio;}ǽ=І(Δο,р.Count)*100f;}void ΖΣ(){Ą=0;try{for(int i=0;i<Ȥ.Count;i++)
{IMyReactor ΑΠ=Ȥ[i];if(!Ǭ(ΑΠ,true)) continue;List<MyInventoryItem>Ћ=new List<MyInventoryItem>();ΑΠ.GetInventory(0).GetItems(Ћ);float ώ=0;for(int j=0;j<Ћ.Count;j++){MyInventoryItem Ѝ=Ћ[j];if(Ѝ.Type.SubtypeId.ToUpper()=="URANIUM"&&Ѝ.Type.TypeId.ToUpper().Contains("_INGOT"))
ώ+=(float) Ѝ.Amount;}if(ώ<Ą||i==0){Ą=ώ;Αα=ΑΠ.CustomName;}}}catch(Exception e){ȗ=e;}}void ΗΣ(){Ȝ=0;Ȧ=0;try{for(int i=0;i<ğ.Count;i++){IMyTerminalBlock Σ=ğ[i];if(!Ǭ(Σ,true)) continue;Ȧ+=(float) Σ.GetInventory(0).CurrentVolume;Ȝ+=(float) Σ.GetInventory(0).MaxVolume;
}ƻ=(float) Math.Min(Math.Round(І(Ȧ,Ȝ)*100,1),100.0);}catch(Exception e){ȗ=e;}}void Ζϋ(){try{Ǖ.Clear();for(int i=0;i<ğ.Count;i++){IMyTerminalBlock Σ=ğ[i];if(!Ǭ(Σ,true)) continue;Δσ(Σ,А.į);}if(Й!=ϊ.Αϋ){for(int i=0;i<Ȳ.Count;i++){IMyTerminalBlock Σ=Ȳ[i];if(!Ǭ(Σ,true)) continue;
Δσ(Σ,А.ΕΕ);}}ΖΠ(Ǖ);}catch(Exception e){ȗ=e;}}void ΖЃ(){if(ǌ){if(Δύ().Count>ǁ){ǌ=false;if(а!=Ы.ź){υ();if(а==Ы.Αν) Ă();if(а==Ы.ƃ)
if(Θ.α) ư();else Ă();}Ρ="Damage detected";}}}bool Ασ(){if(!Ɵ) return true;if(γ==Ξ.Њ){if(н>0&&ǝ!=г.None)
if(ǳ<=н){Ρ="Low energy! Move home";return false;}if(П>0&&Ȥ.Count>0)
if(Ą<=П){Ρ="Low fuel: "+Αα;return false;}if(м>0&&р.Count>0)
if(ǽ<=м){Ρ="Low hydrogen";return false;}}return true;}List<IMyTerminalBlock>Δύ(){List<IMyTerminalBlock>Ď=new List<IMyTerminalBlock>();for(int i=0;i<Ž.Count;i++){IMyTerminalBlock Σ=Ž[i];if(Ŷ(Σ,false)) Ď.Add(Σ);}return Ď;}bool Ŷ(IMyTerminalBlock Σ,bool Αχ){return(!Ǭ(Σ,Αχ)||!Σ.IsFunctional);
}bool Ǭ(IMyTerminalBlock Σ,bool Αχ){if(Σ==null) return false;try{IMyCubeBlock ΔЀ=Me.CubeGrid.GetCubeBlock(Σ.Position).FatBlock;if(Αχ) return ΔЀ==Σ;else return ΔЀ.GetType()==Σ.GetType();}catch{return false;}}float ΕΩ(IMyTerminalBlock Σ,String з,String ΓЏ,String[]Ǜ){float Ƕ=0;for(int i=0;i<Σ.InventoryCount;i++)
{IMyInventory Ζψ=Σ.GetInventory(i);List<MyInventoryItem>Ћ=new List<MyInventoryItem>();Ζψ.GetItems(Ћ);foreach(MyInventoryItem Ѝ in Ћ){if(Ǜ!=null&&(Ǜ.Contains(Ѝ.Type.TypeId.ToUpper())||Ǜ.Contains(Ѝ.Type.SubtypeId.ToUpper())))
continue;if((з==""||Ѝ.Type.TypeId.ToUpper()==з)&&(ΓЏ==""||Ѝ.Type.SubtypeId.ToUpper()==ΓЏ))
Ƕ+=(float) Ѝ.Amount;}}return Ƕ;}и ΗΟ(String έ,String ν,А Г,bool Ζή){έ=έ.ToUpper();ν=ν.ToUpper();for(int i=0;i<Ǖ.Count;i++){и Ѝ=Ǖ[i];if(Ѝ.έ.ToUpper()==έ&&Ѝ.ν.ToUpper()==ν&&(Ѝ.Ĭ==Г||Г==А.Ȯ))
return Ѝ;}и Ϊ=null;if(Ζή){Ϊ=new и(έ,ν,0,Г);Ǖ.Add(Ϊ);}return Ϊ;}int Ȑ(String έ,String ν,А Г){return Ȑ(έ,ν,Г,null);}int Ȑ(String έ,String ν,А Г,String[]Ǜ){int Ƕ=0;έ=έ.ToUpper();ν=ν.ToUpper();for(int i=0;i<Ǖ.Count;i++){и Ѝ=Ǖ[i];if(Ǜ!=null&&Ǜ.Contains(Ѝ.έ.ToUpper())) continue;
if((έ==""||Ѝ.έ.ToUpper()==έ)&&(ν==""||Ѝ.ν.ToUpper()==ν)&&(Ѝ.Ĭ==Г||Г==А.Ȯ))
Ƕ+=Ѝ.ώ;}return Ƕ;}void Δσ(IMyTerminalBlock Σ,А Г){for(int i=0;i<Σ.InventoryCount;i++){List<MyInventoryItem>Ћ=new List<MyInventoryItem>();Σ.GetInventory(i).GetItems(Ћ);for(int j=0;j<Ћ.Count;j++)
ΗΟ(Ћ[j].Type.SubtypeId,Ћ[j].Type.TypeId.Replace("MyObjectBuilder_",""),Г,true).ώ+=(int) Ћ[j].Amount;}}void ΖΠ(List<и>Я){for(int i=Я.Count-1;i>0;i--)
for(int j=0;j<i;j++){и a=Я[j];и b=Я[j+1];if(a.ώ<b.ώ) Я.Move(j,j+1);}}bool Ŵ(bool Ηζ){if(ǿ&&Μ!=Κ.ΰ)
if(Ж!=-1&&ă>=Ж){Ρ="Ship too heavy";return true;}if(ƻ>=Ǡ||œ){œ=false;Ρ="Ship is full";return true;}return false;}bool Γφ(){String[]Ǜ=null;if(!ȑ) Ǜ=new string[]{"ICE"};if(Μ==Κ.ŵ) return Ȑ("","ORE",А.į,Ǜ)==0;if(Μ==Κ.ǐ) return Ȑ("","COMPONENT",А.į,Ǜ)==0;else return Ȑ("","",А.į,Ǜ)==0;
}bool ΖΧ(){List<IMyCockpit>Αγ=new List<IMyCockpit>();ψ.GetBlocksOfType(Αγ,q=>q.CubeGrid==Me.CubeGrid);for(int i=0;i<Αγ.Count;i++)
if(Αγ[i].IsUnderControl) return true;return false;}bool ΖΓ(bool ќ,bool ơ){IMyShipConnector ǒ=Ч(MyShipConnectorStatus.Connected);if(ǒ==null) return false;if(Vector3.Distance(Θ.Δ,ǒ.GetPosition())<5)
return ΔΖ(χ,ќ,ơ);if(Vector3.Distance(Ε.Δ,ǒ.GetPosition())<5)
return ΔΖ(τ,ќ,ơ);return false;}bool ΔΖ(Ļ ǻ,bool ќ,bool ơ){if(ќ) ǻ.Εη();ǻ.ΖΗ();bool Щ=false;String б="";switch(ǻ.Ѕ){case δ.ΑЅ:{б="Waiting for command";Щ=false;break;}case δ.ΓІ:{б="Waiting for cargo";Щ=Ŵ(true);break;}case δ.Γε:{б="Unloading";Щ=Γφ();break;}case δ.Αή:{Щ=true;break;}
case δ.Βδ:{б="Charging batteries";Щ=ǳ>=100f;break;}case δ.Ǝ:{б="Discharging batteries";Щ=ǳ<=25f;break;}case δ.Ƙ:{б="Discharging batteries";Щ=ǳ<=0f;break;}case δ.Αί:{б="Filling up hydrogen";Щ=ǽ>=100f;break;}case δ.ΑЎ:{б="Unloading hydrogen";Щ=ǽ<=25f;break;}
case δ.ΑΤ:{б="Unloading hydrogen";Щ=ǽ<=0f;break;}case δ.Αώ:{bool Δψ=ΖΧ();if(!Δψ) ǻ.ΒЃ=true;Щ=ǻ.ΒЃ&&Δψ;б="Waiting for passengers";break;}}if(!Щ) ǻ.Ββ(true);if(Щ&&ǻ.ΑΟ()){Щ=ǻ.Ββ(false);б="Undocking in: "+ΒϏ((int) Math.Max(0,ǻ.ѝ-ǻ.ȟ));}if(ơ) ΔΧ=б;return Щ;}void ΗΖ(){
if(!Ŀ) return;if(ξ.Count<=1) return;float Γι=0,Δώ=0;for(int i=0;i<ξ.Count;i++){IMyTerminalBlock Ǟ=ξ[i];if(Ŷ(Ǟ,true)) continue;Γι+=(float) Ǟ.GetInventory(0).MaxVolume;Δώ+=(float) Ǟ.GetInventory(0).CurrentVolume;}float ΔΡ=(float) Math.Round(І(Δώ,Γι),5);for(int ΓЄ=0;ΓЄ<Math.Max(1,Math.Floor(ξ.Count/10f));ΓЄ++)
{float ΑΝ=0,Αΰ=0;float ΔΒ=0,ΔЍ=0;IMyTerminalBlock ȅ=null,ș=null;for(int i=0;i<ξ.Count;i++){IMyTerminalBlock Ǟ=ξ[i];if(Ŷ(Ǟ,true)) continue;float ΒЋ=(float) Ǟ.GetInventory(0).MaxVolume;float Ư=І((float) Ǟ.GetInventory(0).CurrentVolume,ΒЋ);if(ȅ==null||Ư>ΑΝ){ȅ=Ǟ;ΑΝ=Ư;ΔΒ=ΒЋ;}
if(ș==null||Ư<Αΰ){ș=Ǟ;Αΰ=Ư;ΔЍ=ΒЋ;}}if(ȅ==null||ș==null||ȅ==ș) return;if(checkConveyorSystem&&!ȅ.GetInventory(0).IsConnectedTo(ș.GetInventory(0))){if(ΑϏ>20) Ρ="Inventory balancing failed";else ΑϏ++;return;}ΑϏ=0;List<MyInventoryItem>Ћ=new List<MyInventoryItem>();
ȅ.GetInventory(0).GetItems(Ћ);float ş=0;if(Ћ.Count==0) continue;MyInventoryItem ƴ=Ћ[0];String Δπ=ƴ.Type.TypeId+ƴ.Type.SubtypeId;if(!ΓЍ.TryGetValue(Δπ,out ş)){if(ΕΓ(ȅ.GetInventory(0),0,ș.GetInventory(0),out ş))
ΓЍ.Add(Δπ,ş);else return;}float ΖΒ=((ΑΝ-ΔΡ)*ΔΒ/ş);float Εκ=((ΔΡ-Αΰ)*ΔЍ/ş);int Αέ=(int) Math.Min(Εκ,ΖΒ);if(Αέ<=0) return;if((float) ƴ.Amount<Αέ)
ȅ.GetInventory(0).TransferItemTo(ș.GetInventory(0),0,null,null,ƴ.Amount);else
ȅ.GetInventory(0).TransferItemTo(ș.GetInventory(0),0,null,null,Αέ);}}bool ΕΓ(IMyInventory Ū,int Α,IMyInventory ΖΟ,out float Δε){Δε=0;float Ζδ=(float) Ū.CurrentVolume;List<MyInventoryItem>Βη=new List<MyInventoryItem>();Ū.GetItems(Βη);float Δδ=0;for(int i=0;i<Βη.Count;i++) Δδ+=(float) Βη[i].Amount;
Ū.TransferItemTo(ΖΟ,Α,null,null,1);float ΔΨ=Ζδ-(float) Ū.CurrentVolume;List<MyInventoryItem>ΓΒ=new List<MyInventoryItem>();Ū.GetItems(ΓΒ);float ΔΙ=0;for(int i=0;i<ΓΒ.Count;i++) ΔΙ+=(float) ΓΒ[i].Amount;if(ΔΨ==0f||!ΒІ(0.9999,Δδ-ΔΙ,1.0001))
return false;Δε=ΔΨ;return true;}void ΗΔ(){Vector3 ŋ=ϋ-κ;if(ŋ.Length()==0) ŋ=new Vector3(0,0,-1);Vector3 ǂ=Ф(Υ,ŋ);Vector3 Γσ=Vector3.Normalize(ǂ);Vector3 Į=Ф(Υ,Υ.GetNaturalGravity());float ΕЇ=ΒЍ>0?Math.Max(0,1-İ(ŋ,Δμ)/5):0;float О=(float) Math.Min((ΑЄ>0?ΑЄ:1000f),Math.Max(ƿ(-ǂ,Į,null),ΒЍ*ΕЇ));
if(!ΓЇ) О=0;if(ΔІ) О=Math.Max(0,1-Ʋ/ΑΘ)*О;if(generalSpeedLimit>0) О=Math.Min(generalSpeedLimit,О);if(Δή) О*=(float) Math.Min(1,І(ŋ.Length(),wpReachedDist)/2);Vector3 Δν=Ф(Υ,Υ.GetShipVelocities().LinearVelocity);float Ζγ=(float)(Math.Max(0,15-İ(-Γσ,-Δν))/15)*0.85f+0.15f;
ΑΧ+=Math.Sign(Ζγ-ΑΧ)/10f;Vector3 Ș=Γσ*О*ΑΧ-(Δν);Vector3 Βϊ=Βΰ(Ș,null);if(Ƣ&&З>0.1f){Ș.X*=ΒΝ(Ș.X,ref ƕ.X,1f,Βϊ.X,20);Ș.Y*=ΒΝ(Ș.Y,ref ƕ.Y,1f,Βϊ.Y,20);Ș.Z*=ΒΝ(Ș.Z,ref ƕ.Z,1f,Βϊ.Z,20);}else ƕ=new Vector3(1,1,1);Ũ=ă*Ș-Į*ă;ΔΕ(Ũ,Ƣ);З=Vector3.Distance(κ,ϋ);
}float ΒΝ(float value,ref float М,float щ,float ȇ,float ΒЁ){value=Math.Sign(Math.Round(value,2));if(value==Math.Sign(М)) М+=Math.Sign(М)*щ;else М=value;if(value==0) М=1;float Ϊ=Math.Abs(М);if(Ϊ<ΒЁ||ȇ==0) return Ϊ;М=Math.Min(ΒЁ,Math.Max(-ΒЁ,М));Ϊ=Math.Abs(ȇ);return Ϊ;
}void Γδ(){float л=90,ь=90,ю=90;float ї=(float)(Me.CubeGrid.GridSizeEnum==MyCubeSize.Small?gyroSpeedSmall:gyroSpeedLarge)/100f;Vector3 Ǥ,ѐ,Ů,Ας;if(ΑБ){Ǥ=Vector3.Normalize(ϋ-κ);Ů=Ф(Υ,Ǥ);ѐ=Ф(Υ,Αβ);л=İ(Ů,new Vector3(0,-1,0))-90;ь=Ĉ(ѐ,new Vector3(-1,0,0),ѐ.Y);
ю=Ĉ(Ů,new Vector3(-1,0,0),Ů.Z);}else{Ǥ=ΒЏ;ѐ=Ф(Υ,Αβ);Ů=Ф(Υ,ΒЏ);Ας=Ф(Υ,ΓΙ);л=Ĉ(ѐ,new Vector3(0,0,1),ѐ.Y);ь=Ĉ(ѐ,new Vector3(-1,0,0),ѐ.Y);ю=Ĉ(Ας,new Vector3(0,0,1),Ας.X);}if(Γς&&ƛ()){Vector3 ΒΛ=Υ.GetNaturalGravity();ѐ=Ф(Υ,ΒΛ);л=Ĉ(ѐ,new Vector3(0,0,1),ѐ.Y);
ь=Ĉ(ѐ,new Vector3(-1,0,0),ѐ.Y);}if(!ΒІ(-45,ь,45)){л=0;ю=0;}if(!ΒІ(-45,ю,45)) л=0;ΑΑ(Βύ,1,(-л)*ї,(-ю)*ї,(-ь)*ї);Ʋ=Math.Max(Math.Abs(л),Math.Max(Math.Abs(ь),Math.Abs(ю)));ƌ=Ʋ<=ΑΘ;}void Ζχ(IMyTerminalBlock ǉ){if(ǉ==null) return;џ=new float[3,2];х=new Dictionary<string,float[,]>();
for(int i=0;i<Ǻ.Count;i++){IMyThrust Ц=Ǻ[i];if(!Ц.IsFunctional) continue;Vector3 ω=Ф(ǉ,Ц.WorldMatrix.Backward);float Ȫ=Ц.MaxEffectiveThrust;if(Math.Round(ω.X,2)!=0.0)
if(ω.X>=0) џ[0,0]+=Ȫ;else џ[0,1]-=Ȫ;if(Math.Round(ω.Y,2)!=0.0)
if(ω.Y>=0) џ[1,0]+=Ȫ;else џ[1,1]-=Ȫ;if(Math.Round(ω.Z,2)!=0.0)
if(ω.Z>=0) џ[2,0]+=Ȫ;else џ[2,1]-=Ȫ;String з=ΓΥ(Ц);float[,]т=null;if(х.ContainsKey(з)) т=х[з];else{т=new float[3,2];х.Add(з,т);}float ȇ=Ц.MaxThrust;if(Math.Round(ω.X,2)!=0.0)
if(ω.X>=0) т[0,0]+=ȇ;else т[0,1]-=ȇ;if(Math.Round(ω.Y,2)!=0.0)
if(ω.Y>=0) т[1,0]+=ȇ;else т[1,1]-=ȇ;if(Math.Round(ω.Z,2)!=0.0)
if(ω.Z>=0) т[2,0]+=ȇ;else т[2,1]-=ȇ;}}static String ΓΥ(IMyThrust Ц){return Ц.BlockDefinition.SubtypeId;}Vector3 Βρ(Vector3 ъ,float[,]ł){return new Vector3(
ъ.X>=0?ł[0,0]:ł[0,1],
ъ.Y>=0?ł[1,0]:ł[1,1],
ъ.Z>=0?ł[2,0]:ł[2,1]);}bool Δά(Ω Χ,String з,out float Βή){Βή=0;int Α=ǫ.IndexOf(з);if(Α==-1||Χ.ј==null||Α>=Χ.ј.Length)
return false;Βή=Χ.ј[Α];if(Βή==-1) return false;return true;}Vector3 Βΰ(Vector3 ъ,Ω Χ){if(Χ!=null){Vector3 Ϊ=new Vector3();for(int i=0;i<х.Keys.Count;i++){String з=х.Keys.ElementAt(i);float ű=0;if(!Δά(Χ,з,out ű))
return Βρ(ъ,џ);Ϊ+=Βρ(ъ,х.Values.ElementAt(i))*ű;}return Ϊ;}return Βρ(ъ,џ);}float Ŗ(Vector3 ъ,Ω Χ){return Ŗ(ъ,new Vector3(),Χ);}float Ŗ(Vector3 ъ,Vector3 ς,Ω Χ){Vector3 ΖΩ=Βΰ(ъ,Χ);Vector3 Ȫ=ΖΩ+ς*ă;float ĉ=(Ȫ/ъ).AbsMin();return(float)(ъ*ĉ).Length();}float ƿ(Vector3 Ƴ,Vector3 Į,Ω Χ)
{if(Ƴ.Length()==0) return 0;float ΓЂ=1;if(Į.Length()>0) ΓЂ=Math.Min(1,İ(-Į,Ƴ)/90)*0.4f+0.6f;float Ũ=Ŗ(Ƴ,Į,Χ);if(Ũ==0) return 0.1f;float ΑΛ=І(Ũ,ă);float Ατ=(float) Math.Sqrt(І(Ƴ.Length(),ΑΛ*0.5f));return ΑΛ*Ατ*ΓЂ*ǥ;}float Ǉ(Vector3 Ǥ,Vector3 ћ,Vector3 ς,Ω Χ){if(ς.Length()==0f) return 0;
Vector3 Ǆ=Ē(Ǥ,ћ,Vector3.Normalize(ς));float ǔ=Ŗ(-Ǆ,Χ);return ǔ/ς.Length();}void Γό(bool ΕΔ){float п=0;float ΑΞ=0.9f;if(ΕΔ){Ж=-1;Ę=0;Ǚ=null;if(γ!=Ξ.й&&Ε.ς.Length()!=0){п=ΑΞ*Ǉ(Ε.ί,Ε.β*-1,Ε.ς,null);if(п<Ж||Ж==-1) Ж=п;}if(Θ.α&&Θ.ς.Length()!=0){п=ΑΞ*Ǉ(Θ.ί,Θ.β*-1,Θ.ς,null);
if(п<Ж||Ж==-1) Ж=п;}return;}if(Ę==-1) return;if(Ę>=0){int Δι=0;while(Ę<Φ.Count){if(Δι>100) return;Δι++;Ω Χ=Φ[Ę];if(Χ.ς.Length()!=0f){п=ΑΞ*Math.Min(
Ǉ(Χ.ί,Χ.β*-1,Χ.ς,Χ),
Ǉ(Χ.ί*-1,Χ.β*-1,Χ.ς,Χ));if(п<Ж||Ж==-1) Ж=п;}else Ǚ=Χ;Ę++;}Ę=-1;}bool ΒΘ=true;float Ȩ=0;if(Ǚ!=null){for(int i=0;i<х.Count;i++){String з=х.Keys.ElementAt(i);float[,]т=х.Values.ElementAt(i);float ű=0;if(!Δά(Ǚ,з,out ű)){ΒΘ=false;break;}for(int a=0;a<т.GetLength(0);a++)
for(int b=0;b<т.GetLength(1);b++){float ȱ=Math.Abs(т[a,b]*ű);if(ȱ==0) continue;ΒΘ=true;if(Ȩ==0||ȱ<Ȩ) Ȩ=ȱ;}}}if(!ΒΘ){for(int a=0;a<џ.GetLength(0);a++)
for(int b=0;b<џ.GetLength(1);b++){float ȱ=Math.Abs(џ[a,b]);if(ȱ==0) continue;if(Ȩ==0||ȱ<Ȩ) Ȩ=ȱ;}}if(Ȩ>0){float ΖΤ=Me.CubeGrid.GridSizeEnum==MyCubeSize.Small?minAccelerationSmall:minAccelerationLarge;п=І(Ȩ,ΖΤ);if(п>0)
if(п<Ж||Ж==-1) Ж=п;}}void ΔΕ(Vector3 ǔ,bool Ё){if(!Ё){for(int i=0;i<Ǻ.Count;i++)
Ǻ[i].SetValueFloat("Override",0.0f);return;}Vector3 Βσ=Βΰ(ǔ,null);float ΗΑ=Math.Min(1,Math.Abs(І(ǔ.X,Βσ.X)));float Ζά=Math.Min(1,Math.Abs(І(ǔ.Y,Βσ.Y)));float ΕΒ=Math.Min(1,Math.Abs(І(ǔ.Z,Βσ.Z)));for(int i=0;i<Ǻ.Count;i++){IMyThrust Ц=Ǻ[i];Vector3 ω=Εα(Ф(Υ,Ц.WorldMatrix.Backward),1);
if(ω.X!=0&&Math.Sign(ω.X)==Math.Sign(ǔ.X))
Ц.SetValueFloat("Override",Ц.MaxThrust*ΗΑ);else if(ω.Y!=0&&Math.Sign(ω.Y)==Math.Sign(ǔ.Y))
Ц.SetValueFloat("Override",Ц.MaxThrust*Ζά);else if(ω.Z!=0&&Math.Sign(ω.Z)==Math.Sign(ǔ.Z))
Ц.SetValueFloat("Override",Ц.MaxThrust*ΕΒ);else
Ц.SetValueFloat("Override",0.0f);}}void ΑΑ(bool Ё,float ΕΣ,float л,float ю,float ь){for(int i=0;i<Ƥ.Count;i++){IMyGyro Ϗ=Ƥ[i];Ϗ.GyroOverride=Ё;if(!Ё) Ϗ.GyroPower=100;else Ϗ.GyroPower=ΕΣ;if(!Ё) continue;Vector3 ǧ=Υ.WorldMatrix.Forward;Vector3 Ī=Υ.WorldMatrix.Right;Vector3 ћ=Υ.WorldMatrix.Up;
Vector3 ĵ=Ϗ.WorldMatrix.Forward;Vector3 ĳ=Ϗ.WorldMatrix.Up;Vector3 ģ=Ϗ.WorldMatrix.Left*-1;if(ĵ==ǧ) Ϗ.SetValueFloat("Roll",ь);else if(ĵ==(ǧ*-1)) Ϗ.SetValueFloat("Roll",ь*-1);else if(ĳ==(ǧ*-1)) Ϗ.SetValueFloat("Yaw",ь);else if(ĳ==ǧ) Ϗ.SetValueFloat("Yaw",ь*-1);else if(ģ==ǧ) Ϗ.SetValueFloat("Pitch",ь);
else if(ģ==(ǧ*-1)) Ϗ.SetValueFloat("Pitch",ь*-1);if(ģ==(Ī*-1)) Ϗ.SetValueFloat("Pitch",л);else if(ģ==Ī) Ϗ.SetValueFloat("Pitch",л*-1);else if(ĳ==Ī) Ϗ.SetValueFloat("Yaw",л);else if(ĳ==(Ī*-1)) Ϗ.SetValueFloat("Yaw",л*-1);else if(ĵ==(Ī*-1)) Ϗ.SetValueFloat("Roll",л);
else if(ĵ==Ī) Ϗ.SetValueFloat("Roll",л*-1);if(ĳ==(ћ*-1)) Ϗ.SetValueFloat("Yaw",ю);else if(ĳ==ћ) Ϗ.SetValueFloat("Yaw",ю*-1);else if(ģ==ћ) Ϗ.SetValueFloat("Pitch",ю);else if(ģ==(ћ*-1)) Ϗ.SetValueFloat("Pitch",ю*-1);else if(ĵ==ћ) Ϗ.SetValueFloat("Roll",ю);else if(ĵ==(ћ*-1)) Ϗ.SetValueFloat("Roll",ю*-1);
}}void Γρ(){this.Βύ=false;}void Х(Vector3 ſ,Vector3 ǧ,Vector3 Αυ,float Ǽ,bool Ś){Αψ(ſ,Ǽ,Ś);ΑΘ=Ǽ;ΑБ=false;this.ΒЏ=ǧ;this.ΓΙ=Αυ;}void Х(Vector3 ſ,Vector3 ǧ,Vector3 Αυ,bool Ś){Х(ſ,ǧ,Αυ,2f,Ś);}void Αψ(Vector3 ſ,float Ǽ,bool Ś){ΑΘ=Ǽ;this.Βύ=true;this.Γς=Ś;ΑБ=true;ƌ=false;
this.Αβ=ſ;}void ΒΗ(){Ǘ(false,false,false,ϋ,0);Ƣ=false;}void о(Vector3 Е,float ї){Ǘ(true,false,false,Е,ї);}void Ǘ(bool Ё,bool Αδ,bool ΑА,Vector3 Е,float ї){Ǘ(Ё,Αδ,ΑА,Е,Е-κ,0.0f,ї);}void Ǘ(bool Ё,bool Αδ,bool ΑА,Vector3 Е,Vector3 ΕЎ,float ΕЂ,float ї){Ƣ=true;this.ΓЇ=Ё;
ϋ=Е;this.ΑЄ=ї;this.ΒЍ=ΕЂ;this.Δή=Αδ;this.ΔІ=ΑА;this.Δμ=ΕЎ;З=Vector3.Distance(Е,κ);}void Ζβ(){ψ.GetBlocksOfType(Ž,у);}void ΕЌ(){if(Ɨ){Ѐ=2;return;}List<IMyRemoteControl>ų=new List<IMyRemoteControl>();List<IMySensorBlock>Δλ=new List<IMySensorBlock>();List<IMyTerminalBlock>Ş=new List<IMyTerminalBlock>();
ψ.GetBlocksOfType(ų,у);ψ.GetBlocksOfType(Ў,у);ψ.GetBlocksOfType(Δλ,у);ψ.SearchBlocksOfName(pamTag.Substring(0,pamTag.Length-1)+":",Ş,
q=>q.CubeGrid==Me.CubeGrid&&q is IMyTextSurfaceProvider);Ў=Ǎ(Ў,pamTag,true);Γζ();ΓΚ(Ş);Đ(Ў,setLCDFontAndSize,1.4f,false);Đ(Ǣ,setLCDFontAndSize,1.4f,true);List<IMySensorBlock>Γΰ=Ǎ(Δλ,pamTag,true);if(Γΰ.Count>0) λ=Γΰ[0];else λ=null;if(Μ==Κ.ŵ){ψ.GetBlocksOfType(ξ,q=>q.CubeGrid==Me.CubeGrid&&q is IMyShipDrill);
if(ξ.Count==0){Ѐ=1;Ρ="Drills are missing";}}else if(Μ==Κ.ǐ){ψ.GetBlocksOfType(ξ,q=>q.CubeGrid==Me.CubeGrid&&q is IMyShipGrinder);if(ξ.Count==0){Ѐ=1;Ρ="Grinders are missing";}if(λ==null){Ѐ=1;Ρ="Sensor is missing";}}else if(Μ==Κ.ΰ){ψ.GetBlocksOfType(Βφ,q=>q.CubeGrid==Me.CubeGrid);
}List<IMyRemoteControl>ΔΗ=Ǎ(ų,pamTag,true);if(ΔΗ.Count>0) ų=ΔΗ;if(ų.Count>0) Υ=ų[0];else{Υ=null;Ѐ=2;Ρ="Remote is missing";return;}σ=(float) Υ.CubeGrid.WorldVolume.Radius*2;ф=null;if(Μ!=Κ.ΰ){Δφ();if(ξ.Count>0&&ф!=null){if(λ!=null&&(ф.WorldMatrix.Forward!=λ.WorldMatrix.Forward||
!(Υ.WorldMatrix.Forward==λ.WorldMatrix.Up||Υ.WorldMatrix.Down==λ.WorldMatrix.Down))){Ѐ=1;Ρ="Wrong sensor direction";}if(ф.WorldMatrix.Forward!=Υ.WorldMatrix.Forward&&
ф.WorldMatrix.Forward!=Υ.WorldMatrix.Down){Ѐ=2;Ρ="Wrong remote direction";}}}}void ΕЄ(){ψ.GetBlocksOfType(Ǳ,у);ψ.GetBlocksOfType(е,у);ψ.GetBlocksOfType(Ǻ,у);ψ.GetBlocksOfType(Ƥ,у);ψ.GetBlocksOfType(ț,у);ψ.GetBlocksOfType(Ȥ,у);ψ.GetBlocksOfType(р,
q=>q.CubeGrid==Me.CubeGrid&&q.BlockDefinition.ToString().ToUpper().Contains("HYDROGEN"));ψ.GetBlocksOfType(ǋ,у);if(Me.CubeGrid.GridSizeEnum==MyCubeSize.Small)
е=Ǎ(е,"ConnectorMedium",false);else
е=Ǎ(е,"Connector",false);List<IMyShipConnector>ΔΑ=Ǎ(е,pamTag,true);if(ΔΑ.Count>0) е=ΔΑ;if(Ѐ<=1){if(е.Count==0){Ѐ=1;Ρ="Connector is missing";}if(Ƥ.Count==0){Ѐ=1;Ρ="Gyros are missing";}if(Ǻ.Count==0){Ѐ=1;Ρ="Thrusters are missing";}}List<IMyConveyorSorter>ΔЁ=Ǎ(ǋ,pamTag,true);
if(ΔЁ.Count>0) ǋ=ΔЁ;List<IMyLandingGear>ΔΝ=Ǎ(Ǳ,pamTag,true);if(ΔΝ.Count>0) Ǳ=ΔΝ;for(int i=0;i<Ǳ.Count;i++) Ǳ[i].AutoLock=false;List<IMyBatteryBlock>ΔΘ=Ǎ(ț,pamTag,true);if(ΔΘ.Count>0) ț=ΔΘ;List<IMyGasTank>ΓΗ=Ǎ(р,pamTag,true);if(ΓΗ.Count>0) р=ΓΗ;}void Εΰ(){ψ.GetBlocksOfType(Ȳ,q=>q.CubeGrid==Me.CubeGrid&&q.InventoryCount>0);
ğ.Clear();for(int i=Ȳ.Count-1;i>=0;i--){if(Ζα(Ȳ[i])){ğ.Add(Ȳ[i]);Ȳ.RemoveAt(i);}}}bool Ζα(IMyTerminalBlock Σ){if(Σ is IMyCargoContainer) return true;if(Σ is IMyShipDrill) return true;if(Σ is IMyShipGrinder) return true;if(Σ is IMyShipConnector){if(((IMyShipConnector) Σ).ThrowOut) return false;
if(Me.CubeGrid.GridSizeEnum!=MyCubeSize.Large&&Βκ(Σ,"ConnectorSmall",false))
return false;else return true;}return false;}void Δφ(){if(Υ==null) return;ф=null;float Ɣ=0,ǈ=0,ƞ=0,ǃ=0,Ƅ=0,ƈ=0;List<IMyTerminalBlock>ΒΡ=Ǎ(ξ,pamTag,true);bool ΗΠ=ΒΡ.Count==0;if(ΒΡ.Count>0) ф=ΒΡ[0];else if(ξ.Count>0) ф=ξ[0];int Ƕ=0;for(int i=0;i<ξ.Count;i++)
{if(ξ[i].WorldMatrix.Forward!=ф.WorldMatrix.Forward){if(ΗΠ){Ѐ=2;Ρ="Mining direction is unclear!";return;}continue;}Ƕ++;Vector3 Ѓ=Βθ(Υ,ξ[i].GetPosition());if(i==0){Ɣ=Ѓ.X;ǈ=Ѓ.X;ƞ=Ѓ.Y;ǃ=Ѓ.Y;Ƅ=Ѓ.Z;ƈ=Ѓ.Z;}ǈ=Math.Max(Ѓ.X,ǈ);Ɣ=Math.Min(Ѓ.X,Ɣ);ǃ=Math.Max(Ѓ.Y,ǃ);ƞ=Math.Min(Ѓ.Y,ƞ);
ƈ=Math.Max(Ѓ.Z,ƈ);Ƅ=Math.Min(Ѓ.Z,Ƅ);}ȋ=(ǈ-Ɣ)*(1-Ŧ)+drillRadius*2;Ǵ=(ǃ-ƞ)*(1-ĝ)+drillRadius*2;if(ф!=null&&ф.WorldMatrix.Forward==Υ.WorldMatrix.Down)
Ǵ=(ƈ-Ƅ)*(1-ĝ)+drillRadius*2;}List<T>Ǎ<T>(List<T>Я,String љ,bool ΑΖ){List<T>Ϊ=new List<T>();for(int i=0;i<Я.Count;i++)
if(Βκ(Я[i],љ,ΑΖ)) Ϊ.Add(Я[i]);return Ϊ;}bool Βκ<T>(T Σ,String љ,bool ΑΖ){IMyTerminalBlock b=(IMyTerminalBlock) Σ;if(ΑΖ&&b.CustomName.ToUpper().Contains(љ.ToUpper())) return true;if(!ΑΖ&&b.BlockDefinition.ToString().ToUpper().Contains(љ.ToUpper())) return true;return false;}void ц<T>(List<T>Я,bool Ё)
{for(int i=0;i<Я.Count;i++)
ΔΦ((IMyTerminalBlock) Я[i],Ё);}void ΔΦ(IMyTerminalBlock Σ,bool Ё){if(Σ==null) return;String Ζώ=Ё?"OnOff_On":"OnOff_Off";var a=Σ.GetActionWithName(Ζώ);a.Apply(Σ);}void ǟ(bool Ё){ΑΩ=Ё;if(!č) return;ц(ǋ,Ё);}void Αη(ChargeMode С){for(int i=0;i<ț.Count;i++) ț[i].ChargeMode=С;}void Αύ(bool ΖЁ)
{for(int i=0;i<р.Count;i++) р[i].Stockpile=ΖЁ;}void Ƃ(List<IMyLandingGear>ΑΫ,bool ΔΔ){for(int i=0;i<ΑΫ.Count;i++){if(ΔΔ) ΑΫ[i].Lock();if(!ΔΔ) ΑΫ[i].Unlock();}}void Γϊ(bool Ё){if(ΔΞ==Ё) return;List<IMyShipController>Ɲ=new List<IMyShipController>();ψ.GetBlocksOfType(Ɲ,у);if(Ɲ.Count==0) return;
for(int i=0;i<Ɲ.Count;i++)
Ɲ[i].DampenersOverride=Ё;ΔΞ=Ё;}IMyShipConnector Ч(MyShipConnectorStatus б){for(int i=0;i<е.Count;i++){if(!Ǭ(е[i],true)) continue;if(е[i].Status==б) return е[i];}return null;}void Ě(bool Βο,bool ΑΚ,float Εβ,float ΖΨ){if(λ==null||ξ.Count==0) return;Vector3 Ʈ=new Vector3();int Ƕ=0;
for(int i=0;i<ξ.Count;i++){if(ξ[i].WorldMatrix.Forward!=ф.WorldMatrix.Forward) continue;Ƕ++;Ʈ+=ξ[i].GetPosition();}Ʈ=Ʈ/Ƕ;Vector3 Ĳ=Βθ(λ,Ʈ);λ.Enabled=true;λ.ShowOnHUD=Βο;λ.LeftExtend=(ΑΚ?1:ы)/2f*ȋ-Ĳ.X;λ.RightExtend=(ΑΚ?1:ы)/2f*ȋ+Ĳ.X;λ.TopExtend=(ΑΚ?1:я)/2f*Ǵ+Ĳ.Y;
λ.BottomExtend=(ΑΚ?1:я)/2f*Ǵ-Ĳ.Y;λ.FrontExtend=(Βο?Ш:Εβ)-Ĳ.Z;λ.BackExtend=Βο?0:ΖΨ+σ*0.75f+Ĳ.Z;λ.DetectFloatingObjects=true;λ.DetectAsteroids=false;λ.DetectLargeShips=true;λ.DetectSmallShips=true;λ.DetectStations=true;λ.DetectOwner=true;λ.DetectSubgrids=false;
λ.DetectPlayers=false;λ.DetectEnemy=true;λ.DetectFriendly=true;λ.DetectNeutral=true;}void Đ<T>(List<T>Я,bool ΔБ,float ΕЊ,bool Εν){for(int i=0;i<Я.Count;i++){IMyTextSurface ř=null;if(Я[i]is IMyTextSurface) ř=(IMyTextSurface) Я[i];if(ř!=null){ř.ContentType=ContentType.TEXT_AND_IMAGE;
if(!ΔБ) continue;ř.Font="Debug";if(Εν) continue;ř.FontSize=ΕЊ;}}}bool ƛ(){Vector3D Ќ;return this.Υ.TryGetPlanetPosition(out Ќ);}int Ζό(Vector3 Εό,int ΔΠ){if(ΔΠ==-1) return 0;double Џ=-1;int Ǿ=-1;for(int i=Φ.Count-1;i>=0;i--){double Є=Vector3.Distance(Φ[i].Δ,Εό);if(Џ==-1||Є<Џ){Ǿ=i;Џ=Є;}
}return Math.Sign(Ǿ-ΔΠ);}bool ΗΡ(Vector3 Ќ){List<Vector3>Д=new List<Vector3>();for(int i=0;i<Φ.Count;i++) Д.Add(Φ[i].Δ);if(Θ.α&&Φ.Count>=1){Vector3 Ĵ=new Vector3();Ǫ(Θ,dockDist*σ,false,out Ĵ);if(Vector3.Distance(Θ.Δ,Φ.First().Δ)<Vector3.Distance(Θ.Δ,Φ.Last().Δ)){Д.Insert(0,Ĵ);Д.Insert(0,Θ.Δ);}
else{Д.Add(Ĵ);Д.Add(Θ.Δ);}}if(Μ==Κ.ΰ){if(Ε.α&&Φ.Count>=1){Vector3 Αρ=new Vector3();Ǫ(Ε,dockDist*σ,false,out Αρ);if(Vector3.Distance(Ε.Δ,Φ.First().Δ)<Vector3.Distance(Ε.Δ,Φ.Last().Δ)){Д.Insert(0,Αρ);Д.Insert(0,Ε.Δ);}else{Д.Add(Αρ);Д.Add(Ε.Δ);}}}else{if(γ!=Ξ.й)
if(Φ.Count>0&&Vector3.Distance(Ε.Δ,Φ.First().Δ)<Vector3.Distance(Ε.Δ,Φ.Last().Δ))
Д.Insert(0,Ε.Δ);else Д.Add(Ε.Δ);}int Ǿ=-1;double ǡ=-1;for(int i=0;i<Д.Count;i++){double Є=Vector3.Distance(Д[i],Ќ);if(Є<ǡ||ǡ==-1){ǡ=Є;Ǿ=i;}}if(Д.Count==0) return false;double ΓΞ=Vector3.Distance(Д[Ǿ],Ќ);double ΗΞ=Vector3.Distance(Д[Math.Max(0,Ǿ-1)],Д[Ǿ])*1.5f;
double Ελ=Vector3.Distance(Д[Math.Min(Д.Count-1,Ǿ+1)],Д[Ǿ])*1.5f;return ΓΞ<ΗΞ||ΓΞ<Ελ;}static float І(float a,float b){if(b==0) return 0;return a/b;}Vector3 Εα(Vector3 v,int ΒΦ){return new Vector3(Math.Round(v.X,ΒΦ),Math.Round(v.Y,ΒΦ),Math.Round(v.Z,ΒΦ));}float İ(Vector3 a,Vector3 b)
{if(a==b) return 0;float Εω=(a*b).Sum;float Γπ=a.Length();float ΓБ=b.Length();if(Γπ==0||ΓБ==0) return 0;float Ϊ=(float)((180.0f/Math.PI)*Math.Acos(Εω/(Γπ*ΓБ)));if(float.IsNaN(Ϊ)) return 0;return Ϊ;}float Ĉ(Vector3 v,Vector3 ǉ,float ΕΑ){float Ğ=İ(v,ǉ);if(ΕΑ>0f) Ğ*=-1;
if(Ğ>-90f) return Ğ-90f;else return 180f-(-Ğ-90f);}double ΓЊ(float ΖΪ){return(Math.PI/180)*ΖΪ;}bool ΒІ(double Ερ,double value,double ΒΩ){return(value>=Ερ&&value<=ΒΩ);}Vector3 Εψ(IMyTerminalBlock Σ,Vector3 Ѓ){return Vector3D.Transform(Ѓ,Σ.WorldMatrix);}Vector3 Βθ(IMyTerminalBlock Σ,Vector3 Ετ)
{return Ф(Σ,Ετ-Σ.GetPosition());}Vector3 Ф(IMyTerminalBlock Σ,Vector3 ΒΜ){return Vector3D.TransformNormal(ΒΜ,MatrixD.Transpose(Σ.WorldMatrix));}Vector3 Ē(Vector3 Ǥ,Vector3 ћ,Vector3 ΒΜ){MatrixD Βε=MatrixD.CreateFromDir(Ǥ,ћ);return Vector3D.TransformNormal(ΒΜ,MatrixD.Transpose(Βε));}Vector3 ΒΨ(Vector3 Ǥ,Vector3 ћ,Vector3 Ѓ)
{MatrixD Βε=MatrixD.CreateFromDir(Ǥ,ћ);return Vector3D.Transform(Ѓ,Βε);}String В(Vector3 v){return ""+v.X+"|"+v.Y+"|"+v.Z;}Vector3 Б(String s){String[]ι=s.Split('|');return new Vector3(float.Parse(Ι(ι,0)),float.Parse(Ι(ι,1)),float.Parse(Ι(ι,2)));}String ΖЅ(Ω Χ){String Ї=":";
String Ϊ=В(Χ.Δ)+Ї+В(Χ.ί)+Ї+
В(Χ.β)+Ї+В(Χ.φ)+Ї+В(Χ.ς);for(int i=0;i<Χ.ј.Length;i++)
Ϊ+=Ї+Math.Round(Χ.ј[i],3);return Ϊ;}Ω Εί(String s){String[]ι=s.Split(':');Ω Χ=new Ω(
Б(Ι(ι,0)),Б(Ι(ι,1)),
Б(Ι(ι,2)),Б(Ι(ι,3)),
Б(Ι(ι,4)));int Α=5;List<float>ΓΪ=new List<float>();while(Α<ι.Length){String ǀ=Ι(ι,Α);float f=0;if(!float.TryParse(ǀ,out f)) break;ΓΪ.Add(f);Α++;}Χ.ј=ΓΪ.ToArray();return Χ;}void Π<T>(T value,bool Ζυ){if(Ζυ) Storage+="\n";Storage+=value;}void Π<T>(T value){Π(value,true);}
String Ι(String[]ΗΒ,int Α){String ǀ=ΗΒ.ElementAtOrDefault(Α);if(String.IsNullOrEmpty(ǀ)) return "";return ǀ;}void Save(){if(Ɨ||Μ==Κ.с){Storage="";return;}Storage=DATAREV+";";Π(В(ΑΔ),false);Π(В(Θ.ί));Π(В(Θ.φ));Π(В(Θ.β));Π(В(Θ.ς));Π(В(Θ.Δ));Π(В(Θ.д));Π(Θ.α);Π(В(Ε.Δ));Π(В(Ε.ς));Π(В(Ε.ί));
Π(В(Ε.β));Π(В(Ε.φ));Π(В(Ε.д));Π(Ε.α);Π(В(ǭ));Π(В(ą));Π(";");Π((int) Μ,false);Π((int) γ);Π((int) э);Π(Ǡ);Π(н);Π(П);Π(м);Π(ǥ);Π(ǿ);Π(ȑ);if(Μ==Κ.ΰ){Π((int) χ.Ѕ);Π(χ.ѝ);Π(χ.ȟ);Π(χ.Ǐ);Π(χ.ў);Π((int) τ.Ѕ);Π(τ.ѝ);Π(τ.ȟ);Π(τ.Ǐ);Π(τ.ў);}else{Π((int) Ȋ);Π((int) а);Π((int) Й);Π((int) Ǔ);Π((int) ΑΙ);Π(ȧ);
Π(č);Π(Ŀ);Π(Ł);Π(ы);Π(я);Π(Ш);Π(ń);Π(ņ);Π(Ŧ);Π(ĝ);Π(Р);Π(в);Π(ρ);Π(π);Π(Ț);Π(к);Π(đ);Π(ı);}Π(";");for(int i=0;i<ǫ.Count;i++)
Π((i>0?"|":"")+ǫ[i],false);Π(";");for(int i=0;i<Φ.Count;i++)
Π(ΖЅ(Φ[i]),i>0);}Ȇ Επ(){if(Storage=="") return Ȇ.Ζο;String[]Š=Storage.Split(';');if(Ι(Š,0)!=DATAREV) return Ȇ.Δζ;int Α=0;try{String[]Ζ=Ι(Š,1).Split('\n');ΑΔ=Б(Ι(Ζ,Α++));Θ.ί=Б(Ι(Ζ,Α++));Θ.φ=Б(Ι(Ζ,Α++));Θ.β=Б(Ι(Ζ,Α++));Θ.ς=Б(Ι(Ζ,Α++));Θ.Δ=Б(Ι(Ζ,Α++));Θ.д=Б(Ι(Ζ,Α++));
Θ.α=bool.Parse(Ι(Ζ,Α++));Ε.Δ=Б(Ι(Ζ,Α++));Ε.ς=Б(Ι(Ζ,Α++));Ε.ί=Б(Ι(Ζ,Α++));Ε.β=Б(Ι(Ζ,Α++));Ε.φ=Б(Ι(Ζ,Α++));Ε.д=Б(Ι(Ζ,Α++));Ε.α=bool.Parse(Ι(Ζ,Α++));ǭ=Б(Ι(Ζ,Α++));ą=Б(Ι(Ζ,Α++));Ζ=Ι(Š,2).Split('\n');Α=0;Μ=(Κ) int.Parse(Ι(Ζ,Α++));γ=(Ξ) int.Parse(Ι(Ζ,Α++));э=(Ξ) int.Parse(Ι(Ζ,Α++));
Ǡ=int.Parse(Ι(Ζ,Α++));н=int.Parse(Ι(Ζ,Α++));П=int.Parse(Ι(Ζ,Α++));м=int.Parse(Ι(Ζ,Α++));ǥ=float.Parse(Ι(Ζ,Α++));ǿ=bool.Parse(Ι(Ζ,Α++));ȑ=bool.Parse(Ι(Ζ,Α++));if(Μ==Κ.ΰ){χ.Ѕ=(δ) int.Parse(Ι(Ζ,Α++));χ.ѝ=float.Parse(Ι(Ζ,Α++));χ.ȟ=float.Parse(Ι(Ζ,Α++));χ.Ǐ=Ι(Ζ,Α++);χ.ў=Ι(Ζ,Α++);
τ.Ѕ=(δ) int.Parse(Ι(Ζ,Α++));τ.ѝ=float.Parse(Ι(Ζ,Α++));τ.ȟ=float.Parse(Ι(Ζ,Α++));τ.Ǐ=Ι(Ζ,Α++);τ.ў=Ι(Ζ,Α++);}else{Ȋ=(ǘ) int.Parse(Ι(Ζ,Α++));а=(Ы) int.Parse(Ι(Ζ,Α++));Й=(ϊ) int.Parse(Ι(Ζ,Α++));Ǔ=(ѓ) int.Parse(Ι(Ζ,Α++));ΑΙ=(ǘ) int.Parse(Ι(Ζ,Α++));ȧ=bool.Parse(Ι(Ζ,Α++));č=bool.Parse(Ι(Ζ,Α++));
Ŀ=bool.Parse(Ι(Ζ,Α++));Ł=bool.Parse(Ι(Ζ,Α++));ы=int.Parse(Ι(Ζ,Α++));я=int.Parse(Ι(Ζ,Α++));Ш=int.Parse(Ι(Ζ,Α++));ń=float.Parse(Ι(Ζ,Α++));ņ=float.Parse(Ι(Ζ,Α++));Ŧ=float.Parse(Ι(Ζ,Α++));ĝ=float.Parse(Ι(Ζ,Α++));Р=int.Parse(Ι(Ζ,Α++));в=int.Parse(Ι(Ζ,Α++));ρ=int.Parse(Ι(Ζ,Α++));
π=int.Parse(Ι(Ζ,Α++));Ț=int.Parse(Ι(Ζ,Α++));к=int.Parse(Ι(Ζ,Α++));đ=int.Parse(Ι(Ζ,Α++));ı=float.Parse(Ι(Ζ,Α++));}Ζ=Ι(Š,3).Replace("\n","").Split('|');ǫ=Ζ.ToList();Ζ=Ι(Š,4).Split('\n');Φ.Clear();if(Ζ.Count()>=1&&Ζ[0]!="")
for(int i=0;i<Ζ.Length;i++)
Φ.Add(Εί(Ι(Ζ,i)));}catch{return Ȇ.ΔЂ;}Ŋ=э;υ();return Ȇ.ΔА;}void Γζ(){Ċ.Clear();for(int i=Ў.Count-1;i>=0;i--){String ε=Ў[i].CustomData.ToUpper();bool Αο=false;if(ε=="INSTRUCTIONS"){Αο=true;ΑΓ=true;}if(ε=="DEBUG") Αο=true;if(Αο){Ċ.Add(Ў[i]);Ў.RemoveAt(i);}}Đ(Ċ,false,1,false);
}void ΓΚ(List<IMyTerminalBlock>Γν){Ǣ.Clear();for(int i=0;i<Γν.Count;i++){IMyTerminalBlock Σ=Γν[i];try{String Γα=pamTag.Substring(0,pamTag.Length-1)+":";int Α=Σ.CustomName.IndexOf(Γα);int ķ=-1;if(Α<0||!int.TryParse(Σ.CustomName.Substring(Α+Γα.Length,1),out ķ)) continue;if(ķ==-1) continue;
ķ--;IMyTextSurfaceProvider ΔЊ=(IMyTextSurfaceProvider) Σ;if(ķ<ΔЊ.SurfaceCount&&ķ>=0)
Ǣ.Add(ΔЊ.GetSurface(ķ));}catch{}}}String ǆ="";void Γο(){String ΒА="";String ů="";ǆ=Γγ(false);ΒА+=ǆ;ů+=ǆ;ů+=Ζω();for(int i=0;i<Ў.Count;i++) Ў[i].WriteText(ΒА);for(int i=0;i<Ǣ.Count;i++) Ǣ[i].WriteText(ΒА);Echo(ů);for(int i=0;i<Ċ.Count;i++){IMyTextPanel ȁ=Ċ[i];String ε=ȁ.CustomData.ToUpper();
if(ε=="DEBUG") ȁ.WriteText(""+"\n"+"");if(ε=="INSTRUCTIONS") ȁ.WriteText(Δξ());}}string Δξ(){String Γ="";try{float ΔΩ=Runtime.MaxInstructionCount;Γ+="Inst: "+Runtime.CurrentInstructionCount+" Time: "+Math.Round(Runtime.LastRunTimeMs,3)+"\n";Γ+="Inst. avg/max: "+(int)(ī*ΔΩ)+" / "+(int)(ŉ*ΔΩ)+"\n";
Γ+="Inst. avg/max: "+Math.Round(ī*100f,1)+"% / "+Math.Round(ŉ*100f,1)+"% \n";Γ+="Time avg/max: "+Math.Round(Ŕ,2)+"ms / "+Math.Round(ΑЏ,2)+"ms \n";}catch{}for(int i=0;i<Ȁ.Count;i++)
Γ+=""+Ȁ.Keys.ElementAt(i)+" = "+Math.Round(Ȁ.Values.ElementAt(i)[0],2)+" / "+
Math.Round(Ȁ.Values.ElementAt(i)[1],2)+"%\n";return Γ;}void ΕΥ(){String Γ="Error occurred! \nPlease copy this and paste it \nin the \"Bugs and issues\" discussion.\n"+
"Version: "+VERSION+"\n";Đ(Ў,setLCDFontAndSize,0.9f,false);Đ(Ǣ,setLCDFontAndSize,0.9f,true);for(int i=0;i<Ў.Count;i++) Ў[i].WriteText(Γ+ȗ.ToString());for(int i=0;i<Ǣ.Count;i++) Ǣ[i].WriteText(Γ+ȗ.ToString());}void Ǩ(){if(!ΑΓ) return;try{Αζ=Runtime.CurrentInstructionCount;}catch{}
}void Ǧ(String έ){if(!ΑΓ) return;if(Αζ==0) return;try{float Ƈ=(Runtime.CurrentInstructionCount-Αζ)/Runtime.MaxInstructionCount*100;if(!Ȁ.ContainsKey(έ))
Ȁ.Add(έ,new float[]{Ƈ,Ƈ});else{Ȁ[έ][0]=Ƈ;Ȁ[έ][1]=Math.Max(Ƈ,Ȁ[έ][1]);}}catch{}}const String BROADCAST_TAG="[PAMCMD]";const String BROADCAST_SELF_ID="#";const Char BROADCAST_SEP=';';void Ζμ(String ǖ){if(!Ħ) return;String Ї=""+BROADCAST_SEP;String θ=VERSION+Ї;θ+=ĭ+Ї;θ+=(int) Μ+Ї;
θ+=ľ(κ.X)+""+Ї;θ+=ľ(κ.Y)+Ї;θ+=ľ(κ.Z)+Ї;if(Μ!=Κ.ΰ)
θ+=ΒΫ(э)+(э==Ξ.Њ?" "+Math.Round(ū,1)+"%":"")+Ї;else θ+=ΒΫ(э)+Ї;θ+=Ρ+Ї;θ+=Љ+""+Ї;θ+=ǆ+Ї;θ+=Ȧ+Ї;θ+=Ȝ+Ї;for(int i=0;i<Ǖ.Count;i++){if(Ǖ[i].Ĭ!=А.į) continue;θ+=Ǖ[i].έ+"/"+Ǖ[i].ν+"/"+Ǖ[i].ώ+Ї;}ΕЁ(θ,ǖ);}void ΕЁ(String θ,String ǖ){Βι(θ,BROADCAST_SELF_ID,ǖ);}
void Βι(String θ,String Е,String ǖ){try{if(!Ħ) return;θ=BROADCAST_TAG+BROADCAST_SEP+ΓЅ()+BROADCAST_SEP+Е+BROADCAST_SEP+Βχ+BROADCAST_SEP+ǖ+BROADCAST_SEP+θ;this.IGC.SendBroadcastMessage(BROADCAST_TAG,θ);}catch(Exception e){ȗ=e;}}String ΓЅ(){if(Μ!=Κ.с) return ""+Me.GetId();
return BROADCAST_SELF_ID;}bool ΑЀ(String θ){return θ.StartsWith(BROADCAST_TAG);}bool Л(ref String ε,out string ŝ,Char Ї){int Α=ε.IndexOf(Ї);ŝ="";if(Α<0) return false;ŝ=ε.Substring(0,Α);ε=ε.Remove(0,Α+1);return true;}bool ΔΓ(ref String θ,out String ǣ,out String ǖ){ǣ="";ǖ="";if(!Ħ) return false;
String љ="";if(!Л(ref θ,out љ,BROADCAST_SEP)||!ΑЀ(љ)) return false;if(!Л(ref θ,out ǣ,BROADCAST_SEP)) return false;if(!Л(ref θ,out љ,BROADCAST_SEP)||(љ!=ΓЅ()&&(љ!="*"&&Μ!=Κ.с))) return false;if(!Л(ref θ,out љ,BROADCAST_SEP)||(љ!=Βχ)) return false;if(!Л(ref θ,out ǖ,BROADCAST_SEP)) return false;
return true;}void ΓΣ(){bool ŭ=true;if(Δϊ){Δϊ=false;if(Me.CustomData.Contains("Antenna_Name")){Ρ="Update custom data";Me.CustomData="";}}String ũ=(Μ!=Κ.с?"[PAM-Ship]":"[PAM-Controller]")+" Broadcast-settings";try{if(Me.CustomData.Length==0||Me.CustomData.Split('\n')[0]!=ũ)
Δί(ũ);String[]Ζ=Me.CustomData.Split('\n');Ħ=bool.Parse(ƪ(ƍ(Ζ,"Enable_Broadcast",ref ŭ)));bool Βζ=false;bool Γκ=true;if(Ħ){if(Μ!=Κ.с)
ĭ=ƪ(ƍ(Ζ,"Ship_Name",ref ŭ)).Replace(BROADCAST_SELF_ID,"");Βχ=ƪ(ƍ(Ζ,"Broadcast_Channel",ref ŭ)).ToLower();Γκ=false;if(њ==null){њ=this.IGC.RegisterBroadcastListener(BROADCAST_TAG);њ.SetMessageCallback("");}List<IMyRadioAntenna>Ĩ=new List<IMyRadioAntenna>();ψ.GetBlocksOfType(Ĩ);bool ΒЂ=false;
for(int i=0;i<Ĩ.Count;i++)
if(Ĩ[i].EnableBroadcasting&&Ĩ[i].Enabled){ΒЂ=true;break;}if(Ĩ.Count==0) Ρ="No Antenna found";else if(!ΒЂ) Ρ="Antenna not ready";Βζ=Ĩ.Count==0||!ΒЂ;if(Γά&&!Βζ&&Μ!=Κ.с) Ρ="Antenna ok";}else if(Μ==Κ.с)
Ρ="Offline - Enable in PB custom data";Γά=Βζ;if(Γκ){if(њ!=null) this.IGC.DisableBroadcastListener(њ);њ=null;}}catch{ŭ=false;}if(!ŭ){Ρ="Reset custom data";Δί(ũ);}}void Δί(String ũ){String ε=ũ+"\n\n"+"Enable_Broadcast="+(Μ==Κ.с?"true":"false")+" \n";ε+=Μ!=Κ.с?"Ship_Name=Your_ship_name_here\n":"";
Me.CustomData=ε+"Broadcast_Channel=#default";}String ƪ(String Ā){int Α=Ā.IndexOf("//");if(Α!=-1) Ā=Ā.Substring(0,Α);String[]ι=Ā.Split('=');if(ι.Length<=1) return "";return ι[1].Trim();}String ƍ(String[]Ζ,String Ζι,ref bool ȭ){foreach(String Ā in Ζ)
if(Ā.StartsWith(Ζι)) return Ā;ȭ=false;return "";}void Ζη(string И){if(ȝ) ё=new List<ǎ>();String ǣ="";String ǖ="";if(!ΑЀ(И)) ΖЂ(И);if(њ!=null&&њ.HasPendingMessage){MyIGCMessage θ=њ.AcceptMessage();String ε=(string) θ.Data;if(ΔΓ(ref ε,out ǣ,out ǖ)&&ǣ!=""&&ǣ!=BROADCAST_SELF_ID)
{ǎ ή=ΓΩ(ǣ,"");if(ή==null){ή=new ǎ(ǣ);ё.Add(ή);}ή.Αω(ǖ,false,false,true);Εά(ή,ε);ё.Sort(delegate(ǎ a,ǎ b){if(a.έ==null&&b.έ==null) return 0;else if(a.έ==null) return-1;else if(b.έ==null) return 1;else return a.έ.CompareTo(b.έ);});}}if(ȏ||ȝ){if(Ő<=0||ȝ){Ρ="";ȝ=false;
ΗΘ();ΓΣ();Βα=DateTime.Now;}}ΗΝ();}void Εά(ǎ ή,String ε){ή.Δτ=DateTime.Now;String ŝ="";Л(ref ε,out ή.Δβ,BROADCAST_SEP);Л(ref ε,out ή.έ,BROADCAST_SEP);if(ή.Δβ!=VERSION) return;String Ɓ="";String[]Ľ=new string[3];Л(ref ε,out Ɓ,BROADCAST_SEP);Л(ref ε,out Ľ[0],BROADCAST_SEP);Л(ref ε,out Ľ[1],BROADCAST_SEP);
Л(ref ε,out Ľ[2],BROADCAST_SEP);Л(ref ε,out ή.Εε,BROADCAST_SEP);Л(ref ε,out ή.Ρ,BROADCAST_SEP);Л(ref ε,out ŝ,BROADCAST_SEP);Л(ref ε,out ή.ΗΗ,BROADCAST_SEP);String ΓЉ="",Δς="";Л(ref ε,out ΓЉ,BROADCAST_SEP);Л(ref ε,out Δς,BROADCAST_SEP);ή.Ћ.Clear();while(true){String Δη;if(!Л(ref ε,out Δη,BROADCAST_SEP)) break;
String[]Ơ=Δη.Split('/');if(Ơ.Count()<3) continue;int ώ=0;if(!int.TryParse(Ơ[2],out ώ)) continue;ή.Ћ.Add(new и(Ơ[0],Ơ[1],ώ,А.į));}int ΔϏ=0;if(!int.TryParse(ŝ,out ή.Љ)) ή.Љ=0;if(!int.TryParse(Ɓ,out ΔϏ)) ή.Μ=Κ.Ȗ;if(!float.TryParse(Ľ[0],out ή.Δ.X)) ή.Δ.X=0;if(!float.TryParse(Ľ[1],out ή.Δ.Y)) ή.Δ.Y=0;
if(!float.TryParse(Ľ[2],out ή.Δ.Z)) ή.Δ.Z=0;if(!float.TryParse(ΓЉ,out ή.Ȧ)) ή.Ȧ=0;if(!float.TryParse(Δς,out ή.Ȝ)) ή.Ȝ=0;ή.Μ=(Κ) ΔϏ;ή.ΖΛ=(int) Math.Round(Vector3.Distance(Me.GetPosition(),ή.Δ));ή.Γη=0;for(int i=0;i<ή.Ћ.Count();i++) ή.Γη+=ή.Ћ[i].ώ;}ǎ ΓΩ(String ǵ,String έ){ǵ=ǵ.ToUpper();έ=έ.ToUpper();
for(int i=0;i<ё.Count;i++){if(ǵ!=""&&ё[i].ǵ.ToUpper()==ǵ) return ё[i];if(έ!=""&&ё[i].έ.ToUpper()==έ) return ё[i];}return null;}void ĩ(ǎ ή,String К){if(ή==null){for(int i=0;i<ё.Count;i++)
ё[i].Αω(К,true,false,false);Βι(К,"*",К);}else{ή.Αω(К,true,false,false);Βι(К,ή.ǵ,К);}}void ΖЂ(string И){if(И=="") return;var ι=И.ToUpper().Split(' ');ι.DefaultIfEmpty("");var К=ι.ElementAtOrDefault(0);var Ȟ=ι.ElementAtOrDefault(1);String ǹ="Invalid argument: "+И;if(Ј==Τ.ΓΠ){if(Č!=null)
{switch(К){case "UP":{if(Љ<2) break;if(Č.Љ==0){Љ=1;return;}ĩ(Č,"UP");return;}case "DOWN":{if(Љ<1) break;if(Љ==1){ĩ(Č,"MRES");break;}ĩ(Č,"DOWN");break;}case "APPLY":{if(Љ<2) break;ĩ(Č,"APPLY");return;}}}}switch(К){case "UP":this.Αε(false);return;case "DOWN":this.ΑΣ(false);return;
case "APPLY":this.ƽ(true);return;}switch(К){case "CLEAR":ΗΙ();return;case "SENDALL":ĩ(null,Ȟ);return;case "SEND":ΕΫ(И.Remove(0,"SEND".Length+1));return;}Ρ=ǹ;}void ΕΫ(String ő){if(ő=="") return;var ι=ő.Split(':');if(ι.Length!=2){Ρ="Missing separator \":\"";return;}ι.DefaultIfEmpty("");
String ĭ=ι.ElementAtOrDefault(0).Trim();ǎ ή=ΓΩ("",ĭ);if(ή!=null) ĩ(ή,ι.ElementAtOrDefault(1).Trim());else Ρ="Unknown ship: "+ĭ;}void ΗΙ(){ё.Clear();Č=null;μ(Τ.Main);Љ=0;}void ΗΘ(){List<IMyTerminalBlock>Ş=new List<IMyTerminalBlock>();ψ.GetBlocksOfType(Ў,у);ψ.SearchBlocksOfName(pamTag.Substring(0,pamTag.Length-1)+":",Ş,
q=>q.CubeGrid==Me.CubeGrid&&q is IMyTextSurfaceProvider);Ў=Ǎ(Ў,pamTag,true);ΓΚ(Ş);Γζ();Đ(Ў,setLCDFontAndSize,1.15f,false);Đ(Ǣ,setLCDFontAndSize,1.15f,true);}void ΗΝ(){String ů="[PAM]-Controller\n\n"+"Run-arguments: (Type without:[ ])\n"+"———————————————\n"+
"[UP] Menu navigation up\n"+"[DOWN] Menu navigation down\n"+"[APPLY] Apply menu point\n"+
"[CLEAR] Clear miner list\n"+"[SEND ship:cmd] Send to a ship*\n"+"[SENDALL cmd] Send to all ships*\n"+
"———————————————\n\n"+"*[SEND] = Cmd to one ship:\n"+" e.g.: \"SEND Miner 1:homepos\"\n\n"+
"*[SENDALL] = Cmd to all ships:\n"+" e.g.: \"SENDALL homepos\"\n\n";for(int i=0;i<Ǣ.Count;i++)
Ǣ[i].WriteText(ΔΤ(ђ.Γλ,"0",false));for(int i=0;i<Ў.Count;i++){ђ С=ђ.Ȗ;String Ņ="";ΖΜ(Ў[i],out С,out Ņ);Ў[i].WriteText(ΔΤ(С,Ņ,i==0));}Echo(ů);for(int i=0;i<Ċ.Count;i++){IMyTextPanel ȁ=Ċ[i];String ε=ȁ.CustomData.ToUpper();if(ε=="DEBUG") ȁ.WriteText(""+"\n"+"");if(ε=="INSTRUCTIONS") ȁ.WriteText(Δξ());
}}String ƽ(bool Η){int Εέ=0;return ƽ(Η,0,ref Εέ,false,1);}String ƽ(bool Η,int ΗΫ,ref int Ηδ,bool Ηε,int Βμ){return "[PAM]-Controller | "+ё.Count+" Connected ships\n";}String ΔΤ(ђ С,String Ņ,bool ΗΩ){return ƽ(false);}void ΖΜ(IMyTerminalBlock ȁ,out ђ С,out String Ņ){bool ȭ=true;String Ɓ=ƪ(ƍ(ȁ.CustomData.Split('\n'),"mode",ref ȭ)).ToUpper();
String[]ι=Ɓ.Split(':');String Ō=ι.Length>0?ι[0].Trim():"";Ņ=ι.Length>1?ι[1].Trim():"";С=ђ.Ȗ;if(Ō=="MAIN") С=ђ.Ζε;else if(Ō=="MAINX") С=ђ.Γλ;else if(Ō=="MENU") С=ђ.Ζϊ;else if(Ō=="INVENTORY") С=ђ.ΖЎ;else if(Ō=="DEBUG") С=ђ.ΕЅ;if(С==ђ.Ȗ) Ņ=Ɓ;}String Γξ(int ΒΒ,String Γ,int ΓЃ,ref int ȉ)
{String[]Ζ=Γ.Split('\n');if(ΓЃ>=ȉ+ΒΒ-1) ȉ++;ȉ=Math.Min(Ζ.Count()-1-ΒΒ,ȉ);if(ΓЃ<ȉ+1) ȉ--;ȉ=Math.Max(0,ȉ);String Ϊ="";for(int i=0;i<ΒΒ;i++){int Δχ=i+ȉ;if(Δχ>=Ζ.Count()) break;Ϊ+=Ζ[Δχ]+"\n";}return Ϊ;}String Ηή(int Ĝ,int Βμ,String Γ){String[]Ζ=Γ.Split('\n');
int Εσ=Ĝ*Βμ;int Ες=(Ĝ+1)*Βμ;String Ϊ="";for(int i=Εσ;i<Ες;i++){if(i>=Ζ.Count()) break;Ϊ+=Ζ[i]+"\n";}return Ϊ;}String Ευ(String s){if(s=="") return s;return s.First().ToString().ToUpper()+s.Substring(1).ToLower();}String Ζΰ(String s,int Δό){if(s=="") return s;if(s.Length>Δό) s=s.Substring(0,Δό-1)+".";
return s;}string ΗΪ(String ē,float value,float ΒΩ,int Γύ,int Γυ,int ΖΙ){float ĉ=І(value,ΒΩ)*Γύ;String Ɩ="[";for(int i=0;i<Γύ;i++){if(i<=ĉ) Ɩ+="|";else Ɩ+="'";}Ɩ+="]";return Ɩ+" "+Ζΰ(Ευ(ē),Γυ).PadRight(Γυ)+"".PadRight(ΖΙ)+Ζθ(value);}String Ζθ(float ώ){if(ώ>=1000000) return Math.Round(ώ/1000000f,ώ/1000000f<100?1:0)+"M";
if(ώ>=1000) return Math.Round(ώ/1000f,ώ/1000f<100?1:0)+"K";return ""+Math.Round(ώ);}String ΒϏ(int ŏ){if(ŏ>=60*60) return Math.Round(ŏ/(60f*60f),1)+" h";if(ŏ>=60) return Math.Round(ŏ/60f,1)+" min";return ""+ŏ+" s";}string ľ(float v){return Math.Round(v,2)+" ";}
string Ηκ(Vector3 v){return "X"+ľ(v.X)+"Y"+ľ(v.Y)+"Z"+ľ(v.Z);}