const string VERSION="1.3.1";const string DATAREV="14";const String pamTag="[PAM]";const String controllerTag="[PAM-Controller]";const int gyroSpeedSmall=15;const int gyroSpeedLarge=5;const int generalSpeedLimit=100;const float dockingSpeed=0.5f;const float dockDist=0.6f;const float followPathDock=2f;
const float followPathJob=1f;const float useDockDirectionDist=1f;const float useJobDirectionDist=0f;const float wpReachedDist=2f;const float drillRadius=1.4f;const float sensorRange=2f;const float fastSpeed=10f;const float minAccelerationSmall=0.2f;const float minAccelerationLarge=0.1f;
const float minEjection=25f;const bool setLCDFontAndSize=true;const bool checkConveyorSystem=false;public enum Κ{Ȭ,Ŗ,ў,п,ΰ}public enum Β{ю,ď,Ů,ȩ,ą,Ǚ,Ш,
ĕ,Ű,Ƞ,Ŷ,Ƃ,č,
Αξ,ȑ,Ț,ľ,ΓΒ,ΒϏ,
ΑЈ,Ʃ,ΑΛ,ΑΣ,ȝ}public enum Ξ{л,ΑΡ,Ћ,Αλ,ƍ,Ư,ƥ,Ħ,ħ}public enum в{None,ľ,ю,Γψ}public enum Τ{Main,ΓЄ,Ŧ,Ť,ΑΥ,Ƴ,
Βϊ,ΓΦ,Δχ,ΓЉ,ΓЈ,Ηά,
Ηδ,Ηβ,Βφ,Δγ,Ƈ}public enum Ц{ơ,ŵ,ΗΜ,Γμ,ΰ}public enum Ǜ{ƹ,ΔΔ}public enum Ч{Ɛ,Βή,ΓΝ,Ŏ}public enum ϋ{ΒЈ,ΔΒ,ΑЇ,ΒЎ,ƨ,Βη,ΑΒ}public enum њ{ΒΗ,ΒΚ,ΒΜ}public enum В{Ģ,ΕЀ,Ě}public enum δ{ΒΙ,Αώ,ΑІ,Δυ,Δά,
ΑЊ,ΑΑ,ΑΜ,Βε,
Βξ,Βι}public enum ά{ǧ,ȅ,Ƿ,ǁ,Αά,Βκ}public enum Ȅ{ΒЍ,ΒΫ,ΖЉ}public enum ȍ{Γθ,ΔΥ,Εε,ΔΓ}public enum ǳ{None,Αφ,ΕЊ,Εω}public enum ο{ſ,Ə,Ʊ,Ŏ,Βς,ƚ,ΒΒ,Ζί,Ατ}public enum ј{Ȭ,ΕΖ,Ηή,Εβ,ΗΛ,ΖΜ,ΓЌ}class Ϊ{public bool α=false;public Vector3 Δ=new Vector3();
public Vector3 β=new Vector3();public Vector3 ί=new Vector3();public Vector3 τ=new Vector3();public Vector3 ς=new Vector3();public Vector3 о=new Vector3();public float Л=0;public float Ηζ=0;public float[]ǒ=null;public Ϊ(){}public Ϊ(Ϊ ǻ){α=ǻ.α;Δ=ǻ.Δ;β=ǻ.β;ί=ǻ.ί;τ=ǻ.τ;ς=ǻ.ς;
о=ǻ.о;ǒ=ǻ.ǒ;}public Ϊ(Vector3 Δ,Vector3 ί,Vector3 β,Vector3 τ,Vector3 ς){this.Δ=Δ;this.β=β;this.ί=ί;this.τ=τ;this.Л=0;this.ς=ς;}public void ΖΟ(List<IMyThrust>Ɔ,List<string>Ǧ){ǒ=new float[Ǧ.Count];for(int i=0;i<ǒ.Length;i++)
ǒ[i]=-1;for(int i=0;i<Ɔ.Count;i++){string и=ΔϏ(Ɔ[i]);int Α=Ǧ.IndexOf(и);if(Α!=-1)
ǒ[Α]=Ѕ(Ɔ[i].MaxEffectiveThrust,Ɔ[i].MaxThrust);}}}class Βί{public Ϊ Й=null;public List<Vector3>ł=new List<Vector3>();public float ŋ=0;public float ΑЎ=0;public float ń=0;public float Βώ=0;public Vector3 ƞ=new Vector3();}class ĸ{public δ Ї=δ.ΒΙ;public float і=0;public float Ȫ=0;
public string ǎ="";public string ћ="";DateTime ΓΪ;public bool Βμ=false;private bool Βρ=false;public bool ΑЌ(bool ђ){if(ђ){Ȫ=0;Βρ=false;return false;}Βρ=true;return Ȫ>і;}public void ΖΪ(){ΑЌ(true);Βμ=false;}public void Ζρ(){if(Βρ)
if((DateTime.Now-ΓΪ).TotalSeconds>1){Ȫ++;ΓΪ=DateTime.Now;}}public bool ΒΟ(){switch(Ї){case δ.Αώ:return true;case δ.ΑІ:return true;}return false;}}class м{public String έ="";public String ν="";public int Ϗ=0;public В Ł=В.Ě;public м(String έ,String ν,int Ϗ,В Ł){this.έ=έ;this.ν=ν;
this.Ϗ=Ϗ;this.Ł=Ł;}}class ΕΣ{public ΕΣ(Vector3 Њ,float Ѓ){this.Њ=Њ;this.Ѓ=Ѓ;}public Vector3 Њ;public float Ѓ;}class ѕ{public DateTime Δφ;public DateTime ΔЋ;public String Ǻ="";public String έ="";public String Δσ="";public String Ρ="";public String Ζν="";public String ΕЌ="";public String ΒΝ="";
public Vector3 Δ=new Vector3();public List<м>Ќ=new List<м>();public Κ Μ=Κ.Ȭ;public ǳ ȓ;public float ȣ;public float ȟ;public int І;public int ΕΝ=0;public int Γο=0;public bool ΗΨ(){return(DateTime.Now-Δφ).TotalSeconds>10;}public bool Ετ(){if(ȓ!=ǳ.Αφ) return false;return(DateTime.Now-ΔЋ).TotalSeconds>=4;
}public ѕ(String Ǻ){this.Ǻ=Ǻ;}public ǳ Αα(String О,bool ΕΑ,bool Γξ,bool ΖЏ){if(О==""&&!Γξ) return ǳ.None;if(ȓ==ǳ.Αφ&&Ετ())
ȓ=ǳ.Εω;if(ΕΑ){ΒΝ=О;ȓ=ǳ.Αφ;ΔЋ=DateTime.Now;return ȓ;}else if(Γξ){ΒΝ="";ȓ=ǳ.None;}else if(ΒΝ==О){if(ΖЏ) ȓ=ǳ.ΕЊ;return ȓ;}return ǳ.None;}}public String Ηα(String ΗΑ){switch(ΗΑ){case "IRON":return "Fe";case "NICKEL":return "Ni";case "COBALT":return "Co";case "MAGNESIUM":return "Mg";
case "SILICON":return "Si";case "SILVER":return "Ag";case "GOLD":return "Au";case "PLATINUM":return "Pt";case "URANIUM":return "U";default:return "";}}IMyGridTerminalSystem ω;Vector3 Ɩ=new Vector3();Vector3 θ=new Vector3();Vector3 Ƶ=new Vector3();Vector3 Ɠ=new Vector3();Vector3 ƫ=new Vector3();
DateTime Αδ=new DateTime();bool ț=true;int Ας=0;bool Ȇ=false;bool Ǝ=false;bool ƺ=true;bool ΔЎ=false;bool ĺ=false;bool ΑΘ=false;float Ȳ=0;float ě=0;int ȯ=0;int ũ=0;int Ō=0;int ΓΔ=0;float ĵ=0;float Ň=0;double ΒЄ=0;float Ŵ=0;List<int>Ķ=new List<int>();List<int>Ĺ=new List<int>();
Κ Μ=Κ.Ȭ;int ύ=0;float ȇ=0;float ǯ=0;float σ=0;IMyRemoteControl Υ;IMySensorBlock μ;List<IMyTimerBlock>ΑΩ=new List<IMyTimerBlock>();List<IMyShipConnector>ж=new List<IMyShipConnector>();List<IMyThrust>Ǫ=new List<IMyThrust>();List<IMyGyro>ƣ=new List<IMyGyro>();List<IMyTerminalBlock>ξ=new List<IMyTerminalBlock>();
List<IMyLandingGear>Ǹ=new List<IMyLandingGear>();List<IMyReactor>ȗ=new List<IMyReactor>();List<IMyConveyorSorter>ƃ=new List<IMyConveyorSorter>();List<IMyGasTank>я=new List<IMyGasTank>();List<IMyTerminalBlock>ś=new List<IMyTerminalBlock>();List<IMyTerminalBlock>Į=new List<IMyTerminalBlock>();
List<IMyTerminalBlock>Ā=new List<IMyTerminalBlock>();List<IMyBatteryBlock>ȥ=new List<IMyBatteryBlock>();List<IMyTextPanel>Г=new List<IMyTextPanel>();List<IMyTextSurface>ǡ=new List<IMyTextSurface>();List<IMyTextPanel>ė=new List<IMyTextPanel>();IMyTerminalBlock х=null;Ϊ Θ=new Ϊ();Ϊ Αύ=new Ϊ();
Ϊ Αυ=new Ϊ();bool Ǩ=false;bool ŀ=false;bool Ĩ=false;bool ΑΓ=false;List<String>Ǧ=new List<string>();List<Ϊ>Φ=new List<Ϊ>();List<Ϊ>Ž=new List<Ϊ>();int Βΰ=0;double Γυ=0;Ϊ Ε=new Ϊ();Vector3 ǭ;Vector3 ċ;Ξ γ=Ξ.л;Ǜ ǃ=Ǜ.ƹ;int Т=0;int й=0;double Ũ=0;bool ǅ=false;ĸ υ=new ĸ();
ĸ φ=new ĸ();Ч Я=Ч.Ɛ;bool ȡ=true;Ǜ Ȃ=Ǜ.ƹ;int ѐ=3;int э=3;int Ы=30;њ ќ=њ.ΒΗ;bool Ȁ=true;bool ı=true;bool ĭ=true;bool Đ=false;ϋ И=ϋ.ΒЈ;bool ȃ=true;float Ǥ=90;float з=20;float Р=5;float г=20;float ǚ=0.70f;float ĥ=1.50f;float ļ=2.50f;float ť=0f;float İ=0f;Β Ψ;
Ξ ы;Β ŧ;Βί η=null;int ρ=0;int π=0;int б=0;int Ȩ=0;int Ċ=30;int ї=0;bool Є=true;Vector3 е;double Ж=0;bool ΑΔ=false;int ΑЂ=0;int Ѐ=0;int ΑЅ=0;int ē=0;int Δό=0;Vector3 ƀ=new Vector3();float Ъ=0;float П=0;int ȳ=0;float ΒΕ=0;float ƭ=0;float Н=0;float ĩ=0;bool ΑЃ=false;
bool Ę=false;bool ţ=false;bool Ȑ=false;bool Ȋ=false;DateTime ΖЇ=new DateTime();Ϊ Ǘ=null;Ϊ ΓΣ=null;float ǫ=0;в ǜ;float Ȓ=0;float ă=0;String ΓΖ="";float Ʈ=0;float ȟ=0;float ȣ=0;List<м>Ǔ=new List<м>();float Е=0;bool ő=false;bool ΓЁ=false;bool Γκ=false;bool Ƽ=false;
bool Γύ=false;float Βτ=0;float Βλ=0;Vector3 ΓΛ=new Vector3();Vector3 ϊ=new Vector3();Vector3 ƛ=new Vector3(1,1,1);float Αρ=1;Vector3 ŕ=new Vector3();bool ƙ=false;bool ΓΑ=false;bool Αϊ=false;bool ΔА=false;float ǂ=0;float ƿ=2;Vector3 Γί;Vector3 Αγ;Vector3 ΑΝ;float[,]џ=new float[3,2];
Dictionary<String,float[,]>ц=new Dictionary<string,float[,]>();Dictionary<String,float>Γό=new Dictionary<String,float>();int Αη=0;Dictionary<String,float[]>Ȉ=new Dictionary<string,float[]>();float Αω;bool Ǌ=false;int Ǉ=0;int Ȝ=0;int ΑΕ=0;int Ȯ=0;String Ρ="";int[]ΓϏ=new int[Enum.GetValues(typeof(Τ)).Length];
bool Δή=false;int Ɵ=0;int І=0;Τ Ј=Τ.Main;int ΖΣ=0,Ζϊ=0,Ζδ=0,ΕБ=0;int Ζψ=0,ΖЌ=0;bool ņ=false;bool ΓΥ=false;String Ľ="";String Ασ="";IMyBroadcastListener Ǎ=null;bool Δπ=true;List<ѕ>ǐ=null;ѕ ć=null;int Ηέ=0,ΗΥ=0;int Ηί=0,Ηη=0;int Ημ=0,ΗΤ=0,Ηλ=0;
String ΖЁ="";Exception Ȥ=null;bool ǀ=false;Ξ Ļ=Ξ.л;bool Δΰ=true;String ΔΑ="";bool Ź=false;bool ΒΧ=true;int ǈ=0;int[]ь=null;Vector3 Απ=new Vector3();bool Γζ=false;bool ф(IMyTerminalBlock Σ)=>Σ.CubeGrid==Me.CubeGrid;Program(){ω=GridTerminalSystem;Runtime.UpdateFrequency=UpdateFrequency.Update10;
if(ΒЌ(Me,controllerTag,true))
Μ=Κ.п;λ(Τ.Main);if(Μ!=Κ.п){Ρ="Welcome to [PAM]!";ȍ Βα=ΖΑ();if(Μ==Κ.Ȭ){List<IMyShipDrill>ΔΦ=new List<IMyShipDrill>();List<IMyShipGrinder>ΔΘ=new List<IMyShipGrinder>();ω.GetBlocksOfType(ΔΦ,q=>q.CubeGrid==Me.CubeGrid);ω.GetBlocksOfType(ΔΘ,q=>q.CubeGrid==Me.CubeGrid);if(ΔΦ.Count>0)
{Μ=Κ.Ŗ;Ρ="Miner mode enabled!";}else if(ΔΘ.Count>0){Μ=Κ.ў;Ρ="Grinder mode enabled!";}else{Μ=Κ.ΰ;Ƕ(Ц.ΰ);}}if(Βα==ȍ.Γθ) ƺ=false;if(Βα==ȍ.ΔΥ) Ρ="Data restore failed!";if(Βα==ȍ.ΔΓ) Ρ="New version, wipe data";}}void Main(string З,UpdateType Εθ){try{if(Ȥ!=null){Εη();ΔΧ();return;}
Ǝ=(Εθ&UpdateType.Update10)!=0;if(Ǝ) Ας++;Ȇ=Ας>=10;if(Ȇ) Ας=0;if(Ǝ){Ǉ++;if(Ǉ>4) Ǉ=0;Ō=Math.Max(0,10-(DateTime.Now-Αδ).Seconds);}if(З!="") ΖЁ=З;if(Μ!=Κ.п)
Εσ(З);else
ΕΡ(З);Δή=false;try{int Γγ=Runtime.CurrentInstructionCount;float Ď=Ѕ(Γγ,Runtime.MaxInstructionCount);if(Ď>0.90) Ρ="Max. instructions >90%";if(Ď>ĵ) ĵ=Ď;if(Ǌ){Ķ.Add(Γγ);while(Ķ.Count>10) Ķ.RemoveAt(0);Ň=0;for(int i=0;i<Ķ.Count;i++) Ň+=Ķ[i];Ň=Ѕ(Ѕ(Ň,Ķ.Count),Runtime.MaxInstructionCount);
double ΒΩ=Runtime.LastRunTimeMs;if(ΑΘ&&ΒΩ>ΒЄ) ΒЄ=ΒΩ;Ĺ.Add((int)(ΒΩ*1000f));while(Ĺ.Count>10) Ĺ.RemoveAt(0);Ŵ=0;for(int i=0;i<Ĺ.Count;i++) Ŵ+=Ĺ[i];Ŵ=Ѕ(Ŵ,Ĺ.Count)/1000f;}}catch{ĵ=0;}}catch(Exception e){Ȥ=e;}}void Εσ(string З){bool Ƥ=false;String Γώ="";if(ύ<=1&&!ΒΦ(З))
Δκ(З);if(Ǎ!=null&&Ǎ.HasPendingMessage){MyIGCMessage κ=Ǎ.AcceptMessage();String ζ=(string) κ.Data;String ǟ="";if(ύ<=1&&ΔЉ(ref ζ,out ǟ,out Γώ)&&ǟ==BROADCAST_SELF_ID){Δκ(ζ);Ƥ=true;}}bool ΔΞ=ΑΘ&&Ψ==Β.ю&&!ĺ&&!Ƥ&&ȯ==0&&!ΑΓ;if(Ȇ&&Ψ!=Β.ю) Ƥ=true;if((Ǝ&&!ΔΞ)||(Ȇ&&ΔΞ))
{if(ȯ==0&&(Ō<=0||ț)){ΔЎ=ύ>0;ύ=0;ȯ=1;Ǭ();ΕΜ();ΓΫ();Ǳ("Scan 1");}else if(ȯ==1){ȯ=2;Ǭ();Ζω();Ǳ("Scan 2");}else if(ȯ==2){ȯ=0;Ǭ();Ζτ();Ǳ("Scan 3");Αδ=DateTime.Now;if(ύ<=1&&ƺ)
Ɩ=ΑЋ(Υ,Υ.CenterOfMass);ƺ=false;if(ț){ț=false;χ();}if(ΔЎ&&ύ==0) Ρ="Setup complete";}else{if(γ==Ξ.Ћ&&Μ!=Κ.ΰ){Ǭ();ΖΦ();Ǳ("Inv balance");}Ǭ();switch(ũ){case 0:ΗΠ();break;case 1:Ζέ();break;case 2:Ει();break;case 3:ΕΩ();break;case 4:Ζκ();break;case 5:ΖΧ();break;case 6:ΕЇ(Υ);break;
}Ǳ("Update: "+ũ);ũ++;if(ũ>6){ũ=0;ΑΘ=true;if(Ļ!=Ξ.л){switch(Ļ){case Ξ.Ħ:ĉ();break;case Ξ.ħ:ĉ();break;case Ξ.Ћ:ĉ();break;case Ξ.Ư:ƕ();break;case Ξ.ƥ:Ȱ();break;}Ļ=Ξ.л;}}}if(!ț){if(!ǲ(Υ,true)){Υ=null;ƺ=true;ύ=2;}if(ύ>=2&&Ψ!=Β.ю)
χ();if(ύ<=1){ě=Υ.CalculateShipMass().PhysicalMass;Ȳ=(float) Υ.GetShipSpeed();θ=Ζό(Υ,Ɩ);Ƶ=Υ.WorldMatrix.Forward;Ɠ=Υ.WorldMatrix.Left;ƫ=Υ.WorldMatrix.Down;Ζθ();if(Ψ!=Β.ю){ĺ=false;Δτ(false);ΔЊ(false);String ΔБ=ΑΟ(Ψ)+" "+(int) Ψ;Ǭ();Ζη();ΑА(false);Ǳ(ΔБ);Ǭ();Ζλ();Ǳ("Thruster");Ǭ();
Δρ();Ǳ("Gyroscope");}else{if(ĺ){if(Ƒ()){Ф(ƫ,Ƶ,Ɠ,0.25f,true);Δρ();Ρ="Aligning to planet: "+Math.Round(ǂ-0.25f,2)+"°";if(ƙ) Αΰ(true,true);}else Αΰ(true,true);}}Ź=false;}}}Ǭ();ΔΧ();Ǳ("Print");if(Ƥ||ΓΔ<=0){Ǭ();ΕΥ(Γώ);Ǳ("Broadcast");ΓΔ=4;}else if(Ȇ) ΓΔ--;}void Δκ(string З){if(З=="") return;
var ι=З.ToUpper().Split(' ');ι.DefaultIfEmpty("");var О=ι.ElementAtOrDefault(0);var Ȧ=ι.ElementAtOrDefault(1);var ř=ι.ElementAtOrDefault(2);var Γέ=ι.ElementAtOrDefault(3);String Ǯ="Invalid argument: "+З;bool ΒΔ=false;switch(О){case "UP":this.Βϋ(false);break;case "DOWN":this.ΒΡ(false);break;
case "UPLOOP":this.Βϋ(true);break;case "DOWNLOOP":this.ΒΡ(true);break;case "APPLY":this.ΓЅ(true);break;case "MRES":І=0;break;case "STOP":this.χ();break;case "PATHHOME":{this.χ();this.ΒЉ();}break;case "PATH":{this.χ();this.ΒЉ();Θ.α=true;}break;case "START":{this.χ();ΑЍ();}break;
case "ALIGN":{Αΰ(!ĺ,false);}break;case "CONT":{this.χ();this.ĉ();}break;case "JOBPOS":{this.χ();this.Ȱ();}break;case "HOMEPOS":{this.χ();this.ƕ();}break;case "FULL":{ő=true;}break;case "RESET":{ǀ=true;ύ=2;}break;default:ΒΔ=true;break;}if(Μ!=Κ.ΰ){switch(О){case "SHUTTLE":{Ζσ();}break;
case "CFGS":{if(!ΖΠ(Ȧ,ř,Γέ)) Ρ=Ǯ;}break;case "CFGB":{if(!ΕΦ(Ȧ,ř)) Ρ=Ǯ;}break;case "CFGL":{if(!Č(ref Ǥ,true,ο.Ʊ,Ȧ,"")||!Εΰ(ř))
Ρ=Ǯ;}break;case "CFGE":{if(!Č(ref Р,true,ο.ƚ,Ȧ,"IG")||
!Č(ref з,true,ο.Βς,ř,"IG")||
!Č(ref г,true,ο.ΒΒ,Γέ,"IG"))
Ρ=Ǯ;}break;case "CFGA":{if(!Č(ref ǚ,false,ο.Ə,Ȧ,"")) Ρ=Ǯ;}break;case "CFGW":{if(!Č(ref ĥ,false,ο.ſ,Ȧ,"")||
!Č(ref ļ,false,ο.ſ,ř,""))
Ρ=Ǯ;}break;case "NEXT":{ΑЄ(false);}break;case "PREV":{ΑЄ(true);}break;default:if(ΒΔ) Ρ=Ǯ;break;}}else{switch(О){case "UNDOCK":{Ź=true;}break;default:if(ΒΔ) Ρ=Ǯ;break;}}}String ΖΩ(){String Γ="\n\n"+"Run-arguments: (Type without:[ ])\n"+"———————————————\n"+
"[UP] Menu navigation up\n"+"[DOWN] Menu navigation down\n"+"[APPLY] Apply menu point\n\n"+
"[UPLOOP] \"UP\" + looping\n"+"[DOWNLOOP] \"DOWN\" + looping\n"+
"[PATHHOME] Record path, set home\n"+"[PATH] Record path, use old home\n"+
"[START] Start job\n"+"[STOP] Stop every process\n"+"[CONT] Continue last job\n"+
"[JOBPOS] Move to job position\n"+"[HOMEPOS] Move to home position\n\n"+
"[FULL] Simulate ship is full\n"+"[ALIGN] Align the ship to planet\n"+"[RESET] Reset all data\n";if(Μ!=Κ.ΰ)
Γ+="[SHUTTLE] Enable shuttle mode\n"+"[NEXT] Next hole\n"+"[PREV] Previous hole\n\n"+
"[CFGS width height depth]*\n"+"[CFGB done damage]*\n"+"[CFGL maxload weightLimit]*\n"+
"[CFGE minUr minBat minHyd]*\n"+"[CFGW forward backward]*\n"+"[CFGA acceleration]*\n"+
"———————————————\n"+
"*[CFGS] = Config Size:\n"+" e.g.: \"CFGS 5 3 20\"\n\n"+
"*[CFGB] = Config Behaviour:\n"+" When done: [HOME,STOP]\n"+" On Damage: [HOME,JOB,STOP,IG]\n"+
" e.g.: \"CFGB HOME IG\"\n\n"+
"*[CFGL] = Config max load:\n"+" maxload: [10..95]\n"+" weight limit: [On/Off]\n"+
" e.g.: \"CFGL 70 on\"\n\n"+
"*[CFGE] = Config energy:\n"+" minUr (Uranium): [1..25, IG]\n"+" minBat (Battery): [5..30, IG]\n"+
" minHyd (Hydrogen): [10..90, IG]\n"+" e.g.: \"CFGE 20 10 IG\"\n\n"+
"*[CFGW] = Config work speed:\n"+" fwd: [0.5..10]\n"+" bwd: [0.5..10]\n"+
" e.g.: \"CFGW 1.5 2\"\n\n"+
"*[CFGA] = Config acceleration:\n"+" acceleration: [10..100]\n"+" e.g.: \"CFGA 80\"\n";else
Γ+="[UNDOCK] Leave current connector\n\n";return Γ;}void Ζσ(){χ();Μ=Κ.ΰ;Ƕ(Ц.ΰ);Ε.α=false;Θ.α=false;μ=null;ξ.Clear();γ=Ξ.л;}void Αΰ(bool Ё,bool ǖ){if(!Ё) Ρ="Aligning canceled";if(ǖ) Ρ="Aligning done";if(ǖ||!Ё){ĺ=false;ΓΞ();ΑΖ(false,0,0,0,0);return;}if(Ƒ()) ĺ=true;}bool ΖΠ(String Ζυ,String Ζι,String ΖΘ)
{bool ΕЃ=γ==Ξ.Ћ;int w,h,d;if(int.TryParse(Ζυ,out w)&&int.TryParse(Ζι,out h)&&int.TryParse(ΖΘ,out d)){this.χ();ѐ=w;э=h;Ы=d;ę(false);ǆ(false,false);if(ΕЃ) ĉ();return true;}return false;}bool Εΰ(String Ş){if(Ş=="ON"){Ȁ=true;return true;}if(Ş=="OFF"){Ȁ=false;return true;}
return false;}bool ΕΦ(String ΔЇ,String Ɨ){bool ā=true;if(ΔЇ=="HOME") ȡ=true;else if(ΔЇ=="STOP") ȡ=false;else ā=false;if(Ɨ=="HOME") Я=Ч.Ɛ;else if(Ɨ=="STOP") Я=Ч.ΓΝ;else if(Ɨ=="JOB") Я=Ч.Βή;else if(Ɨ=="IG") Я=Ч.Ŏ;else ā=false;return ā;}void λ(Τ Ń){ΓϏ[(int) Ј]=І;І=ΓϏ[(int) Ń];
if(Ń==Τ.ΓЈ) І=0;Ј=Ń;if(Μ!=Κ.п)
Ĕ(Ј==Τ.Ŧ,false,0,0);Δή=true;}void Βϋ(bool Ακ){if(І>0) І--;else if(Ακ) І=Ɵ-1;}void ΒΡ(bool Ακ){if(І<Ɵ-1) І++;else if(Ακ) І=0;}String Ƕ(Ц κ){switch(κ){case Ц.ơ:Ρ="Job is running";break;case Ц.ŵ:Ρ="Connector not ready!";break;case Ц.ΗΜ:Ρ="Ship modified, path outdated!";break;
case Ц.Γμ:Ρ="Interrupted by player!";break;case Ц.ΰ:Ρ="Shuttle mode enabled!";break;}return "";}String Ζβ(Ǜ Њ){switch(Њ){case Ǜ.ƹ:return "Top-Left";case Ǜ.ΔΔ:return "Center";default:return "";}}String ΕΙ(њ С){switch(С){case њ.ΒΚ:return "Auto"+(Μ==Κ.Ŗ?" (Ore)":"");case њ.ΒΜ:return "Auto (+Stone)";
case њ.ΒΗ:return "Default";default:return "";}}String ΒЀ(Ξ М){switch(М){case Ξ.л:return "No job";case Ξ.ΑΡ:return "Job paused";case Ξ.Ћ:return "Job active";case Ξ.Ħ:return "Job active";case Ξ.ħ:return "Job active";case Ξ.Αλ:return "Job done";case Ξ.ƍ:return "Job changed";case Ξ.Ư:return "Move home";
case Ξ.ƥ:return "Move to job";}return "";}String Γα(Ч ΕЄ){switch(ΕЄ){case Ч.Ɛ:return "Return home";case Ч.Βή:return "Fly to job pos";case Ч.ΓΝ:return "Stop";case Ч.Ŏ:return "Ignore";}return "";}String Ζΰ(ϋ С){switch(С){case ϋ.ΒЈ:return "Off";case ϋ.ΒЎ:return "Drop pos (Stone) ";case ϋ.ƨ:return "Drop pos (Sto.+Ice)";
case ϋ.ΔΒ:return "Cur. pos (Stone)";case ϋ.ΑЇ:return "Cur. pos (Sto.+Ice)";case ϋ.Βη:return "In motion (Stone)";case ϋ.ΑΒ:return "In motion (Sto.+Ice)";}return "";}String ΔΖ(в М){switch(М){case в.None:return "No batteries";case в.ľ:return "Charging";case в.Γψ:return "Discharging";}return "";}
String ΑΟ(Β М){String ΗΫ=Μ==Κ.ΰ?"target":"job";switch(М){case Β.ю:return "Idle";case Β.ď:return "Flying to XY position";case Β.Ů:return Μ==Κ.ў?"Grinding":"Mining";case Β.ȩ:return "Returning";case Β.ΑΛ:return "Flying to drop pos";case Β.ą:return "Returning to dock";case Β.Ǚ:return "Flying to dock area";
case Β.Ш:return "Flying to job area";case Β.ĕ:return "Flying to path";case Β.Ű:return "Flying to job position";case Β.Ƞ:return "Approaching dock";case Β.Ŷ:return "Docking";case Β.Ƃ:return "Aligning";case Β.č:return "Aligning";case Β.Αξ:return "Retry docking";case Β.ȑ:return "Unloading";case Β.ȝ:return ΔΑ;
case Β.Ț:return "Undocking";case Β.ľ:return "Charging batteries";case Β.ΓΒ:return "Waiting for uranium";case Β.ΒϏ:return "Filling up hydrogen";case Β.ΑЈ:return "Waiting for ejection";case Β.Ʃ:return "Waiting for ejection";case Β.ΑΣ:return "Flying to drop pos";}return "";}String ΓΗ(δ Ї){switch(Ї)
{case δ.ΒΙ:return "On \"Undock\" command";case δ.Αώ:return "On player entered cockpit";case δ.Δυ:return "On ship is full";case δ.Δά:return "On ship is empty";case δ.ΑІ:return "On time delay";case δ.ΑΑ:return "On batteries empty(<25%)";case δ.ΑΜ:return "On batteries empty(=0%)";case δ.ΑЊ:return "On batteries full";
case δ.Βξ:return "On hydrogen empty(<25%)";case δ.Βι:return "On hydrogen empty(=0%)";case δ.Βε:return "On hydrogen full";}return "";}bool Ν(ref String Γ,int ΓΩ,int Ȕ,bool Η,String Ĉ){Ɵ+=1;if(ΓΩ==Ȕ) Ĉ=">"+Ĉ+(Ǉ>=2?" .":"");else Ĉ=" "+Ĉ;Γ+=Ĉ+"\n";return ΓΩ==Ȕ&&Η;}String ΓЅ(bool Η)
{int Α=0;int Λ=І;Ɵ=0;String ΔΪ="———————————————\n";String ī="--------------------------------------------\n";String Γ="";Γ+=ΒЀ(γ)+" | "+(Θ.α?"Ready to dock":"No dock")+"\n";Γ+=ΔΪ;double Ő=Math.Max(Math.Round(this.Ж),0);if(Ј==Τ.Main){bool Ȣ=Μ==Κ.ΰ;if(Ν(ref Γ,Λ,Α++,Η," Record path & set home")) ΒЉ();
if(Μ==Κ.Ŗ)
if(Ν(ref Γ,Λ,Α++,Η," Setup mining job")) λ(Τ.Ŧ);if(Μ==Κ.ў)
if(Ν(ref Γ,Λ,Α++,Η," Setup grinding job")) λ(Τ.Ŧ);if(Μ==Κ.ΰ)
if(Ν(ref Γ,Λ,Α++,Η," Setup shuttle job")) λ(Τ.Βφ);if(Ν(ref Γ,Λ,Α++,Η," Continue job")) ĉ();if(Ν(ref Γ,Λ,Α++,Η," Fly to home position")) ƕ();if(Ν(ref Γ,Λ,Α++,Η," Fly to job position")) Ȱ();if(Ν(ref Γ,Λ,Α++,Η," Behavior settings"))
if(Ȣ) λ(Τ.Ƈ);else λ(Τ.Ƴ);if(Ν(ref Γ,Λ,Α++,Η," Info")) λ(Τ.ΓΦ);if(Μ!=Κ.ΰ)
if(Ν(ref Γ,Λ,Α++,Η," Help")) λ(Τ.ΓЉ);}else if(Ј==Τ.Ŧ){double Εέ=Math.Round(ѐ*ȇ,1);double Εν=Math.Round(э*ǯ,1);String ό="";if(Ν(ref ό,Λ,Α++,Η," Start new job!")) ΑЍ();if(Ν(ref ό,Λ,Α++,Η," Change current job")){ǆ(false,false);λ(Τ.Main);}if(Ν(ref ό,Λ,Α++,Η," Width + (Width: "+ѐ+" = "+Εέ+"m)")){ğ(ref ѐ,5,20,1);ę(true);}
if(Ν(ref ό,Λ,Α++,Η," Width -")){ğ(ref ѐ,-5,20,-1);ę(true);}if(Ν(ref ό,Λ,Α++,Η," Height + (Height: "+э+" = "+Εν+"m)")){ğ(ref э,5,20,1);ę(true);}if(Ν(ref ό,Λ,Α++,Η," Height -")){ğ(ref э,-5,20,-1);ę(true);}if(Ν(ref ό,Λ,Α++,Η," Depth + ("+(ќ==њ.ΒΗ?"Depth":"Min")+": "+Ы+"m)")){ğ(ref Ы,5,50,2);ę(true);}
if(Ν(ref ό,Λ,Α++,Η," Depth -")){ğ(ref Ы,-5,50,-2);ę(true);}if(Ν(ref ό,Λ,Α++,Η," Depth mode: "+ΕΙ(ќ))){ќ=ș(ќ);}if(Ν(ref ό,Λ,Α++,Η," Start pos: "+Ζβ(Ȃ))){Ȃ=ș(Ȃ);}if(Μ==Κ.ў&&ќ==њ.ΒΜ) ќ=ș(ќ);Γ+=Δς(8,ό,Λ,ref Ζψ);}else if(Ј==Τ.Βφ){float[]Δλ=new float[]{0,3,10,30,60,300,600,1200,1800};
if(Ν(ref Γ,Λ,Α++,Η," Next")) λ(Τ.Δγ);if(Ν(ref Γ,Λ,Α++,Η," Back")) λ(Τ.Main);Γ+=" Leave connector 1:\n";if(Ν(ref Γ,Λ,Α++,Η," - "+ΓΗ(υ.Ї))) υ.Ї=ș(υ.Ї);if(!υ.ΒΟ()) Γ+="\n";else if(Ν(ref Γ,Λ,Α++,Η," - Delay: "+ΒΖ((int) υ.і))) υ.і=Γλ(υ.і,Δλ);Γ+=" Leave connector 2:\n";if(Ν(ref Γ,Λ,Α++,Η," - "+ΓΗ(φ.Ї))) φ.Ї=ș(φ.Ї);
if(!φ.ΒΟ()) Γ+="\n";else if(Ν(ref Γ,Λ,Α++,Η," - Delay: "+ΒΖ((int) φ.і))) φ.і=Γλ(φ.і,Δλ);}else if(Ј==Τ.Δγ){if(Ν(ref Γ,Λ,Α++,Η," Start job!")) ΑЍ();if(Ν(ref Γ,Λ,Α++,Η," Back")) λ(Τ.Βφ);Γ+=" Timer: \"Docking connector 1\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(υ.ǎ!=""?υ.ǎ:"-"))) υ.ǎ=ƽ(ref ΖΣ);
Γ+=" Timer: \"Leaving connector 1\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(υ.ћ!=""?υ.ћ:"-"))) υ.ћ=ƽ(ref Ζδ);Γ+=" Timer: \"Docking connector 2\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(φ.ǎ!=""?φ.ǎ:"-"))) φ.ǎ=ƽ(ref Ζϊ);Γ+=" Timer: \"Leaving connector 2\":\n";if(Ν(ref Γ,Λ,Α++,Η," = "+(φ.ћ!=""?φ.ћ:"-"))) φ.ћ=ƽ(ref ΕБ);
}else if(Ј==Τ.Ť){String Δι=Ǥ+" %";if(Ȇ) Ȝ++;if(Ȝ>1){Ȝ=0;ΑΕ++;if(ΑΕ>1) ΑΕ=0;}bool[]ΑЀ=new bool[]{ȗ.Count==0,ǜ==в.None,я.Count==0};int Δθ=0;while(true){Δθ++;Ȯ++;if(Ȯ>ΑЀ.Length-1) Ȯ=0;if(Δθ>=ΑЀ.Length) break;if(!ΑЀ[Ȯ]) break;}bool Ȣ=Μ==Κ.ΰ;if(!Ȣ&&Ȁ&&Е!=-1&&ΑΕ==0)
Δι=Е<1000000?Math.Round(Е)+" Kg":Math.Round(Е/1000)+" t";if(Ν(ref Γ,Λ,Α++,Η," Stop!")){χ();λ(Τ.Main);}if(Ν(ref Γ,Λ,Α++,Η," Behavior settings"))
if(!Ȣ) λ(Τ.Ƴ);else λ(Τ.Ƈ);if(!Ȣ){if(Ν(ref Γ,Λ,Α++,Η," Next hole")) ΑЄ(false);}else if(Ν(ref Γ,Λ,Α++,Η," Undock")) Ź=true;Γ+=ī;if(!Ȣ) Γ+="Progress: "+Math.Round(Ũ,1)+" %\n";Γ+="State: "+ΑΟ(Ψ)+" "+Ő+"m \n";Γ+="Load: "+Ʈ+" % Max: "+Δι+" \n";if(Ȯ==0) Γ+="Uranium: "+(ȗ.Count==0?"No reactors":Math.Round(ă,1)+"Kg "+(Р==-1?"":" Min: "+Р+" Kg"))+"\n";
if(Ȯ==1) Γ+="Battery: "+(ǜ==в.None?ΔΖ(ǜ):ǫ+"% "+(з==-1||Ȣ?"":" Min: "+з+" %"))+"\n";if(Ȯ==2) Γ+="Hydrogen: "+(я.Count==0?"No tanks":Math.Round(Ȓ,1)+"% "+(г==-1||Ȣ?"":" Min: "+г+" %"))+"\n";}else if(Ј==Τ.Ƴ){String ό="";if(Ν(ref ό,Λ,Α++,Η," Back")){if(γ==Ξ.Ћ) λ(Τ.Ť);else λ(Τ.Main);}
if(Ν(ref ό,Λ,Α++,Η," Max load: "+Ǥ+"%")) Щ(ref Ǥ,Ǥ<=80?-10:-5,ο.Ʊ,false);if(Ν(ref ό,Λ,Α++,Η," Weight limit: "+(Ȁ?"On":"Off"))) Ȁ=!Ȁ;if(Ν(ref ό,Λ,Α++,Η," Ejection: "+Ζΰ(И))) И=ș(И);if(Ν(ref ό,Λ,Α++,Η," Toggle sorters: "+(Đ?"On":"Off"))){Đ=!Đ;if(Đ) Ǡ(ΒΧ);}
if(Ν(ref ό,Λ,Α++,Η," Unload ice: "+(ȃ?"On":"Off"))) ȃ=!ȃ;if(Ν(ref ό,Λ,Α++,Η," Uranium: "+(Р==-1?"Ignore":"Min "+Р+"Kg"))) Щ(ref Р,(Р>5?-5:-1),ο.ƚ,true);if(Ν(ref ό,Λ,Α++,Η," Battery: "+(з==-1?"Ignore":"Min "+з+"%"))) Щ(ref з,-5,ο.Βς,true);if(Ν(ref ό,Λ,Α++,Η," Hydrogen: "+(г==-1?"Ignore":"Min "+г+"%"))) Щ(ref г,-10,ο.ΒΒ,true);
if(Ν(ref ό,Λ,Α++,Η," When done: "+(ȡ?"Return home":"Stop"))) ȡ=!ȡ;if(Ν(ref ό,Λ,Α++,Η," On damage: "+Γα(Я))) Я=ș(Я);if(Ν(ref ό,Λ,Α++,Η," Advanced...")) λ(Τ.Βϊ);Γ+=Δς(8,ό,Λ,ref ΖЌ);}else if(Ј==Τ.Βϊ){if(Ν(ref Γ,Λ,Α++,Η," Back")){if(γ==Ξ.Ћ) λ(Τ.Ť);else λ(Τ.Main);}
if(Ν(ref Γ,Λ,Α++,Η,(Μ==Κ.ў?" Grinder":" Drill")+" inv. balancing: "+(ı?"On":"Off"))) ı=!ı;if(Ν(ref Γ,Λ,Α++,Η," Enable"+(Μ==Κ.ў?" grinders":" drills")+": "+(ĭ?"Fwd + Bwd":"Fwd"))) ĭ=!ĭ;if(Ν(ref Γ,Λ,Α++,Η," Work speed fwd.: "+ĥ+"m/s")) Щ(ref ĥ,0.5f,ο.ſ,false);
if(Ν(ref Γ,Λ,Α++,Η," Work speed bwd.: "+ļ+"m/s")) Щ(ref ļ,0.5f,ο.ſ,false);if(Ν(ref Γ,Λ,Α++,Η," Acceleration: "+Math.Round(ǚ*100f)+"%"+(ǚ>0.80f?" (risky)":""))) Щ(ref ǚ,0.1f,ο.Ə,false);if(Ν(ref Γ,Λ,Α++,Η," Width overlap: "+ť*100f+"%")) ΓΨ(true,0.05f);if(Ν(ref Γ,Λ,Α++,Η," Height overlap: "+İ*100f+"%")) ΓΨ(false,0.05f);
}else if(Ј==Τ.Ƈ){if(Ν(ref Γ,Λ,Α++,Η," Back")){if(γ==Ξ.Ћ) λ(Τ.Ť);else λ(Τ.Main);}if(Ν(ref Γ,Λ,Α++,Η," Max load: "+Ǥ+"%")) Щ(ref Ǥ,Ǥ<=80?-10:-5,ο.Ʊ,false);if(Ν(ref Γ,Λ,Α++,Η," Unload ice: "+(ȃ?"On":"Off"))) ȃ=!ȃ;if(Ν(ref Γ,Λ,Α++,Η," Uranium: "+(Р==-1?"Ignore":"Min "+Р+"Kg"))) Щ(ref Р,(Р>5?-5:-1),ο.ƚ,true);
if(Ν(ref Γ,Λ,Α++,Η," Battery: "+(з==-1?"Ignore":"Charge up"))) з=(з==-1?1:-1);if(Ν(ref Γ,Λ,Α++,Η," Hydrogen: "+(г==-1?"Ignore":"Fill up"))) г=(г==-1?1:-1);if(Ν(ref Γ,Λ,Α++,Η," On damage: "+Γα(Я))) Я=ș(Я);if(Ν(ref Γ,Λ,Α++,Η," Acceleration: "+Math.Round(ǚ*100f)+"%"+(ǚ>0.80f?" (risky)":""))) Щ(ref ǚ,0.1f,ο.Ə,false);
}else if(Ј==Τ.ΓЄ){double ΕΒ=0;if(Φ.Count>0) ΕΒ=Vector3.Distance(Φ.Last().Δ,θ);if(Ν(ref Γ,Λ,Α++,Η," Stop path recording")) Γή();if(Μ!=Κ.ΰ){if(Ν(ref Γ,Λ,Α++,Η," Home: "+(Ǩ?"Use old home":(Θ.α?"Was set! ":"none ")))) Ǩ=!Ǩ;}else{if(Ν(ref Γ,Λ,Α++,Η," Connector 1: "+(Ǩ?"Use old connector":(Θ.α?"Was set! ":"none ")))) Ǩ=!Ǩ;
if(Ν(ref Γ,Λ,Α++,Η," Connector 2: "+(ŀ?"Use old connector":(Ε.α?"Was set! ":"none ")))) ŀ=!ŀ;}if(Ν(ref Γ,Λ,Α++,Η," Path: "+(Ĩ?"Use old path":(Φ.Count>1?"Count: "+Φ.Count:"none ")))) Ĩ=!Ĩ;Γ+=ī;Γ+="Wp spacing: "+Math.Round(Γυ)+"m\n";}else if(Ј==Τ.ΑΥ){if(Ν(ref Γ,Λ,Α++,Η," Stop")){χ();λ(Τ.Main);}
Γ+=ī;Γ+="State: "+ΑΟ(Ψ)+" \n";Γ+="Speed: "+Math.Round(Ȳ,1)+"m/s\n";Γ+="Target dist: "+Ő+"m\n";Γ+="Wp count: "+Φ.Count+"\n";Γ+="Wp left: "+ΑЂ+"\n";}else if(Ј==Τ.ΓΦ){List<IMyTerminalBlock>Ă=ΓΠ();if(Ȇ) Ȝ++;if(Ȝ>=Ă.Count) Ȝ=0;if(Ν(ref Γ,Λ,Α++,Η," Next")) λ(Τ.Δχ);
Γ+=ī;Γ+="Version: "+VERSION+"\n";Γ+="Ship load: "+Math.Round(Ʈ,1)+"% "+Math.Round(ȟ,1)+" / "+Math.Round(ȣ,1)+"\n";Γ+="Uranium: "+(ȗ.Count==0?"No reactors":Math.Round(ă,1)+"Kg "+ΓΖ)+"\n";Γ+="Battery: "+(ǜ==в.None?"":ǫ+"% ")+ΔΖ(ǜ)+"\n";Γ+="Hydrogen: "+(я.Count==0?"No tanks":Math.Round(Ȓ,1)+"% ")+"\n";
Γ+="Damage: "+(Ă.Count==0?"None":""+(Ȝ+1)+"/"+Ă.Count+" "+Ă[Ȝ].CustomName)+"\n";}else if(Ј==Τ.Δχ){if(Ν(ref Γ,Λ,Α++,Η," Back")) λ(Τ.Main);Γ+=ī;Γ+="Next scan: "+Ō+"s\n";Γ+="Ship size: "+Math.Round(ȇ,1)+"m "+Math.Round(ǯ,1)+"m "+Math.Round(σ,1)+"m \n";
Γ+="Broadcast: "+(ņ?"Online - "+Ľ:"Offline")+"\n";Γ+="Max Instructions: "+Math.Round(ĵ*100f,1)+"% \n";}else if(Ј==Τ.ΓЉ){if(Ν(ref Γ,Λ,Α++,Η," Back")) λ(Τ.Main);Γ+=ī;Γ+="1. Dock to your docking station\n";Γ+="2. Select Record path & set home\n";Γ+="3. Fly the path to the ores\n";
Γ+="4. Select stop path recording\n";Γ+="5. Align ship in mining direction\n";Γ+="6. Select Setup job and start\n";}if(ύ==2) Γ="Fatal setup error\nNext scan: "+Ō+"s\n";if(ǀ) Γ="Recompile script now";int ΖΡ=Γ.Split('\n').Length;for(int i=ΖΡ;i<=10;i++) Γ+="\n";Γ+=ΔΪ;Γ+="Last: "+Ρ+"\n";
return Γ;}void ΓΨ(bool Ευ,float р){χ();ǆ(true,false);if(Ευ) Щ(ref ť,р,ο.Ατ,false);else Щ(ref İ,р,ο.Ατ,false);ΓЃ();Ĕ(true,true,0,0);}float Γλ(float ε,float[]Ɯ){float Ω=Ɯ[0];for(int i=Ɯ.Length-1;i>=0;i--)
if(ε<Ɯ[i]) Ω=Ɯ[i];return Ω;}String ƽ(ref int Ȕ){String Ω="";if(Ȕ>=ΑΩ.Count) Ȕ=-1;if(Ȕ>=0) Ω=ΑΩ[Ȕ].CustomName;Ȕ++;return Ω;}void ǌ(string έ){if(γ!=Ξ.Ћ) return;if(έ=="") return;IMyTerminalBlock Σ=ω.GetBlockWithName(έ);if(Σ==null||!(Σ is IMyTimerBlock)){Ρ="Timerblock "+έ+" not found!";
return;}((IMyTimerBlock) Σ).Trigger();}void ğ(ref int value,int Š,int Ȍ,int Βψ){if(Š==0) return;if(value<Ȍ&&Βψ>0||value<=Ȍ&&Βψ<0){value+=Βψ;return;}int ΗΖ=Math.Abs(Š);int ΒЋ=0;int ΒΠ=1;while(true){ΒЋ+=ΒΠ*ΗΖ*10;if(Š<0&&value-Ȍ<=ΒЋ) break;if(Š>0&&value-Ȍ<ΒЋ) break;
ΒΠ++;}value+=ΒΠ*Š;}void ę(bool ΗΧ){ѐ=Math.Max(ѐ,1);э=Math.Max(э,1);Ы=Math.Max(Ы,0);Ĕ(Ј==Τ.Ŧ,false,0,0);}bool Č(ref float value,bool ΖЄ,ο ν,String ȭ,String ΕΘ){if(ȭ=="") return false;float ġ=-1;bool ΔЌ=false;if(ȭ.ToUpper()==ΕΘ) ΔЌ=true;else if(!float.TryParse(ȭ,out ġ)) return false;
else ġ=Math.Max(0,ġ);if(ΖЄ) ġ=(float) Math.Round(ġ);Щ(ref value,ġ,ν,ΔЌ,false);return true;}void Щ(ref float value,float р,ο ν,bool ŝ){Щ(ref value,value+р,ν,ŝ,true);}void Щ(ref float value,float Ġ,ο ν,bool ŝ,bool ΕϏ){float ѝ=0,є=0;if(ν==ο.ſ){ѝ=0.5f;є=10f;}if(ν==ο.Ə){ѝ=0.1f;є=1f;}
if(ν==ο.Ŏ){ѝ=50f;є=100f;}if(ν==ο.Βς){ѝ=5f;є=30f;}if(ν==ο.ƚ){ѝ=1f;є=25f;}if(ν==ο.Ʊ){ѝ=10f;є=95f;}if(ν==ο.ΒΒ){ѝ=10f;є=90f;}if(ν==ο.Ζί){ѝ=10f;є=1800;}if(ν==ο.Ατ){ѝ=0.0f;є=0.75f;}if(Ġ==-1&&ŝ){value=-1;return;}if(value==-1) ŝ=false;
bool Γς=Ġ<ѝ||Ġ>є;if(Γς&&ΕϏ){if(Ġ<value) value=є;else if(Ġ>value) value=ѝ;}else value=Ġ;if(Γς&&ŝ) value=-1;else value=Math.Max(ѝ,Math.Min(value,є));value=(float) Math.Round(value,2);}void ΑЄ(bool Ερ){if(Ερ) б=Math.Max(0,б-1);else б++;ΑА(true);}T ș<T>(T ε){int Α=Array.IndexOf(Enum.GetValues(ε.GetType()),ε);
Α++;if(Α>=ΖЍ(ε)) Α=0;return(T) Enum.GetValues(ε.GetType()).GetValue(Α);}int ΖЍ<T>(T value){return Enum.GetValues(value.GetType()).Length;}void ΒЉ(){Ž.Clear();for(int i=0;i<Φ.Count;i++) Ž.Add(Φ[i]);Φ.Clear();ΑΓ=true;Αύ=new Ϊ(Θ);Αυ=new Ϊ(Ε);Θ.α=false;if(Μ==Κ.ΰ) Ε.α=false;for(int i=0;i<ц.Count;i++)
if(!Ǧ.Contains(ц.Keys.ElementAt(i)))
Ǧ.Add(ц.Keys.ElementAt(i));Ǩ=false;ŀ=false;Ĩ=false;λ(Τ.ΓЄ);}void Γή(){if(Ǩ) Θ=Αύ;if(ŀ) Ε=Αυ;if(Ĩ){Φ.Clear();for(int i=0;i<Ž.Count;i++) Φ.Add(Ž[i]);}ΑΓ=false;χ();λ(Τ.Main);}void Ζθ(){if(!ΑΓ) return;if(Ψ!=Β.ю){Γή();return;}if(!Αύ.α) Ǩ=false;if(!Αυ.α) ŀ=false;if(Ž.Count<=1) Ĩ=false;
IMyShipConnector Ǒ=Э(MyShipConnectorStatus.Connectable);if(Ǒ==null) Ǒ=Э(MyShipConnectorStatus.Connected);if(Ǒ!=null){if(Math.Round(Ȳ,2)<=0.20) Βΰ++;else Βΰ=0;if(Βΰ>=5){if(Μ==Κ.ΰ&&(Θ.α||Ǩ)&&Vector3.Distance(Θ.Δ,Ǒ.GetPosition())>5){Ε.ί=Υ.WorldMatrix.Forward;Ε.τ=Υ.WorldMatrix.Left;
Ε.β=Υ.WorldMatrix.Down;Ε.ς=Υ.GetNaturalGravity();Ε.Δ=Ǒ.GetPosition();Ε.α=true;Ε.о=Ǒ.Position;}else{Θ.ί=Υ.WorldMatrix.Forward;Θ.τ=Υ.WorldMatrix.Left;Θ.β=Υ.WorldMatrix.Down;Θ.ς=Υ.GetNaturalGravity();Θ.Δ=Ǒ.GetPosition();Θ.α=true;Θ.о=Ǒ.Position;}}}double Αν=-1;if(Φ.Count>0) Αν=Vector3.Distance(θ,Φ.Last().Δ);
double ΕΫ=Math.Max(1.5,Math.Pow(Ȳ/100.0,2));double ΔΝ=Math.Max(Ȳ*ΕΫ,2);Γυ=ΔΝ;if((Αν==-1)||Αν>=ΔΝ){Ϊ Χ=new Ϊ(θ,Ƶ,ƫ,Ɠ,Υ.GetNaturalGravity());Χ.ΖΟ(Ǫ,Ǧ);Φ.Add(Χ);}}Ϊ ǿ(){if(Μ!=Κ.ΰ) return Θ;return ΓΣ;}void Ņ(Ϊ Ϋ,Ξ М){ΓΣ=Ϋ;if(γ==Ξ.Ћ) ы=М;}bool ǹ(Ϊ Ϋ,float Ѓ,bool Ζο,out Vector3 Њ)
{if(Ζο){Vector3I ΒЅ=new Vector3I((int) Ϋ.о.X,(int) Ϋ.о.Y,(int) Ϋ.о.Z);IMySlimBlock Σ=Me.CubeGrid.GetCubeBlock(ΒЅ);if(Σ==null||!(Σ.FatBlock is IMyShipConnector)){Њ=new Vector3();return false;}Vector3 ΖΖ=У(Υ,Σ.FatBlock.GetPosition()-θ);Vector3 Ελ=У(Υ,Σ.FatBlock.WorldMatrix.Forward);Њ=Ϋ.Δ-ΑЉ(Ϋ.ί,Ϋ.β*-1,ΖΖ)-ΑЉ(Ϋ.ί,Ϋ.β*-1,Ελ)*Ѓ;
return true;}else{Њ=Ϋ.Δ;return true;}}Vector3 ȉ(int ΖА,int Εμ,bool ΖЀ){if(!ΖЀ&&Γζ) return Απ;float Επ=((Т-1f)/2f)-ΖА;float ΗΟ=((й-1f)/2f)-Εμ;Απ=Ε.Δ+Ε.τ*Επ*ȇ+ċ*-1*ΗΟ*ǯ;Γζ=true;return Απ;}Vector3 ΑΤ(Vector3 Ζή,float ΕЏ){return Ζή+(ǭ*ΕЏ);}ά Αο(){float А=-1;
ά Ω=ά.ǧ;if(Μ!=Κ.ΰ){if(γ!=Ξ.л){Vector3 Ђ=Ē(ǭ,ċ*-1,θ-Ε.Δ);if(Math.Abs(Ђ.X)<=(float)(Т*ȇ)/2f&&Math.Abs(Ђ.Y)<=(float)(й*ǯ)/2f){if(Ђ.Z<=-1&&Ђ.Z>=-Ċ*2) return ά.ǁ;if(Ђ.Z>-1&&Ђ.Z<σ*2) return ά.ǧ;}if(Ȗ(Ε.Δ,ref А)) Ω=ά.ǧ;}if(Θ.α){if(Ȗ(Θ.Δ,ref А)) Ω=ά.Ƿ;
for(int i=0;i<Φ.Count;i++)
if(Ȗ(Φ[i].Δ,ref А)) Ω=ά.ȅ;if(Vector3.Distance(θ,Θ.Δ)<dockDist*σ) Ω=ά.Ƿ;if(Э(MyShipConnectorStatus.Connectable)!=null||Э(MyShipConnectorStatus.Connected)!=null)
Ω=ά.Ƿ;}}else{Vector3 Њ=new Vector3();IMyShipConnector ǵ=Э(MyShipConnectorStatus.Connected);if(Θ.α){if(Ȗ(Θ.Δ,ref А)) Ω=ά.Ƿ;if(ǹ(Θ,dockDist,true,out Њ))
if(Ȗ(Њ,ref А)) Ω=ά.Ƿ;if(ǵ!=null&&Vector3.Distance(ǵ.GetPosition(),Θ.Δ)<5)
return ά.Αά;}for(int i=0;i<Φ.Count;i++)
if(Vector3.Distance(Φ[i].Δ,Θ.Δ)>dockDist*σ&&Vector3.Distance(Φ[i].Δ,Ε.Δ)>dockDist*σ)
if(Ȗ(Φ[i].Δ,ref А)) Ω=ά.ȅ;if(Ε.α){if(Ȗ(Ε.Δ,ref А)) Ω=ά.ǧ;if(ǹ(Ε,dockDist,true,out Њ))
if(Ȗ(Њ,ref А)) Ω=ά.ǧ;if(ǵ!=null&&Vector3.Distance(ǵ.GetPosition(),Ε.Δ)<5)
return ά.Βκ;}}return Ω;}bool Ȗ(Vector3 Њ,ref float А){float Ѓ=Vector3.Distance(Њ,θ);if(Ѓ<А||А==-1){А=Ѓ;return true;}return false;}void ΑЍ(){if(ύ>0){Ρ="Setup error! Can't start";return;}if(Μ==Κ.ΰ){ĉ();return;}Ε.Δ=θ;Ε.ς=Υ.GetNaturalGravity();Ε.ί=Ƶ;Ε.β=ƫ;Ε.τ=Ɠ;
ǭ=х.WorldMatrix.Forward;ċ=Ε.β;if(ǭ==Υ.WorldMatrix.Down) ċ=Υ.WorldMatrix.Backward;ǆ(true,true);Ο(Β.ď);ΒΥ();}void ǆ(bool ѓ,bool ΖΗ){if(γ==Ξ.л&&!ѓ) return;bool Εζ=ѓ||γ==Ξ.Αλ||Т!=ѐ||й!=э||ǃ!=Ȃ;if(Εζ){if(γ!=Ξ.л){γ=Ξ.ƍ;ȉ(ρ,π,ΖΗ);Ρ="Job changed, lost progress";}ǃ=Ȃ;
Т=ѐ;й=э;π=0;ρ=0;ĩ=0;Ȩ=0;Н=0;б=0;ΑА(true);}}void ΒЁ(){н(θ,0);с(Ǫ,true);}void ΒΥ(){Ƕ(Ц.ơ);ΒЁ();ŏ(Ǹ,false);Ǡ(ΒΧ);γ=Ξ.Ћ;ΔЊ(true);ы=γ;λ(Τ.Ť);ΕΕ();ǅ=true;ǈ=0;for(int i=ś.Count-1;i>=0;i--)
if(Ÿ(ś[i],false)) ǈ++;if(ǈ>0) Ρ="Started with damage";}void χ(){if(γ==Ξ.Ћ){γ=Ξ.ΑΡ;Ρ="Job paused";}Ο(Β.ю);ы=γ;ΑΖ(false,0,0,0,0);ΑΫ();ΔΤ(new Vector3(),false);ΓΞ();Αζ(ChargeMode.Auto);ΑΠ(false);Δτ(true);ǽ(Β.ю);Ĕ(false,false,0,0);с(ξ,false);с(ж,true);Ǡ(true);ΑΔ=false;ǅ=false;
ő=false;Ź=false;if(Ј!=Τ.Main&&Ј!=Τ.Ƴ&&Ј!=Τ.Βϊ&&Ј!=Τ.Ƈ)
λ(Τ.Main);}void ĉ(){ά Б=Αο();if(Μ==Κ.ΰ){if(!Ε.α||!Θ.α) return;ΒΥ();bool ΒΤ=Vector3.Distance(θ,Θ.Δ)<Vector3.Distance(θ,Ε.Δ);if(Ļ==Ξ.Ħ) ΒΤ=true;if(Ļ==Ξ.ħ) ΒΤ=false;if(ΒΤ){Ņ(Θ,Ξ.Ħ);switch(Б){case ά.Αά:Ο(Β.ȝ);break;case ά.ȅ:Ο(Β.Ш);break;case ά.Ƿ:Ο(Β.Ƞ);break;default:Ο(Β.Ț);break;
}}else{Ņ(Ε,Ξ.ħ);switch(Б){case ά.Βκ:Ο(Β.ȝ);break;case ά.ǧ:Ο(Β.Ƞ);break;case ά.ȅ:Ο(Β.Ш);break;default:Ο(Β.Ț);break;}}}else{if(γ!=Ξ.ΑΡ&&γ!=Ξ.ƍ) return;bool Εδ=γ==Ξ.ƍ;ΒΥ();bool ΒΪ=ŭ(false)&&Θ.α;switch(Б){case ά.ǧ:Ο(ΒΪ?Β.ĕ:Β.ď);break;case ά.ȅ:Ο(ΒΪ?Β.Ǚ:Β.Ш);break;case ά.Ƿ:Ο(ΒΪ?Β.Ƞ:Β.ȑ);break;
case ά.ǁ:{if(Ȩ!=б||Εδ) Ο(Β.ȩ);else Ο(Β.Ů);}break;default:break;}}}void Ȱ(){if(γ==Ξ.л&&!Θ.α) return;if(Μ==Κ.ΰ&&(!Ε.α||!Θ.α)) return;Ρ="Move to job";ά Б=Αο();if(Μ==Κ.ΰ){Ņ(Ε,Ξ.ħ);switch(Б){case ά.ǧ:Ο(Β.Ƞ);break;case ά.ȅ:Ο(Β.Ш);break;case ά.Βκ:return;default:Ο(Β.Ț);break;
}ǽ(Β.ȝ);}else{switch(Б){case ά.ǧ:Ο(Β.Ш);break;case ά.ȅ:Ο(Β.Ш);break;case ά.Ƿ:Ο(Β.ȑ);break;case ά.ǁ:Ο(Β.ȩ);break;default:break;}if(γ==Ξ.л) ǽ(Β.Ш);else ǽ(Β.č);ΑΔ=true;}ΒЁ();λ(Τ.ΑΥ);ŏ(Ǹ,false);ы=Ξ.ƥ;}void ƕ(){if(!Θ.α) return;Ρ="Move home";ά Б=Αο();if(Μ==Κ.ΰ){Ņ(Θ,Ξ.Ħ);switch(Б)
{case ά.ȅ:Ο(Β.Ǚ);break;case ά.Ƿ:Ο(Β.Ƞ);break;case ά.Αά:return;default:Ο(Β.Ț);break;}ǽ(Β.ȝ);}else{if(Э(MyShipConnectorStatus.Connected)!=null) return;if(Э(MyShipConnectorStatus.Connectable)!=null){Ο(Β.Ŷ);ǽ(Β.ȑ);return;}switch(Б){case ά.ǧ:Ο(Β.ĕ);break;case ά.ȅ:Ο(Β.Ǚ);break;case ά.Ƿ:Ο(Β.Ǚ);break;
case ά.ǁ:Ο(Β.ą);break;default:break;}ǽ(Β.ȑ);}ΒЁ();λ(Τ.ΑΥ);ŏ(Ǹ,false);ы=Ξ.Ư;}void Ο(Β ΑΦ){if(ΑΦ==Β.ю) ŧ=Β.ю;if(ŧ!=Β.ю&&Ψ==ŧ&&ΑΦ!=ŧ){χ();return;}Є=true;Ψ=ΑΦ;}void ǽ(Β М){this.ŧ=М;}Ȅ Εϊ(int ű,bool ђ){if(ђ){ь=null;ρ=0;π=0;}if(Ȃ==Ǜ.ƹ){int ΓΚ=ű+1;π=(int) Math.Floor(Ѕ(ű,Т));
if(π%2==0) ρ=ű-(π*Т);else ρ=Т-1-(ű-(π*Т));if(π>=й) return Ȅ.ΒΫ;else return Ȅ.ΒЍ;}else if(Ȃ==Ǜ.ΔΔ){if(ь==null) ь=new int[]{0,-1,0,0};int Δε=(int) Math.Ceiling(Т/2f);int ΔΕ=(int) Math.Ceiling(й/2f);int ΕΓ=(int) Math.Floor(Т/2f);int Ζς=(int) Math.Floor(й/2f);
int ů=0;while(ь[2]<Math.Pow(Math.Max(Т,й),2)){if(ů>200) return Ȅ.ΖЉ;ů++;ь[2]++;if(-Δε<ρ&&ρ<=ΕΓ&&-ΔΕ<π&&π<=Ζς){if(ь[3]==ű){this.ρ=ρ-1+Δε;this.π=π-1+ΔΕ;return Ȅ.ΒЍ;}ь[3]++;}if(ρ==π||(ρ<0&&ρ==-π)||(ρ>0&&ρ==1-π)){int ΗΚ=ь[0];ь[0]=-ь[1];ь[1]=ΗΚ;
}ρ+=ь[0];π+=ь[1];}}return Ȅ.ΒΫ;}void Ζη(){if(Ψ==Β.ď){if(Є){Ѐ=0;if(Ȩ!=б) ĩ=0;Ȩ=б;}if(Ѐ==0){Ȅ Ω=Εϊ(б,Є);if(Ω==Ȅ.ΒΫ){γ=Ξ.Αλ;Ρ="Job done";if(ȡ&&Θ.α){Ο(Β.ĕ);ǽ(Β.ȑ);ы=Ξ.Ư;}else{Ο(Β.Ű);ǽ(Β.č);ы=Ξ.ƥ;}return;}if(Ω==Ȅ.ΒЍ){Ѐ=1;с(ξ,true);е=ȉ(ρ,π,true);н(е,10);
Ф(Ε.β,Ε.ί,Ε.τ,false);}}else{if(Ж<wpReachedDist){Ο(Β.Ů);return;}}}if(Ψ==Β.Ů){if(Є){с(ξ,true);Ǡ(false);е=ȉ(ρ,π,false);н(ΑΤ(е,0),0);Ф(Ε.β,Ε.ί,Ε.τ,false);Ѐ=1;Ъ=0;П=0;ƭ=0;ΒΕ=-1;Ċ=Ы;ΑЃ=true;}if(!ΒΑ()){Ο(Β.ą);return;}if(ŭ(true)){Δό=ȁ("","ORE",В.Ě);if((И==ϋ.ΒЎ||И==ϋ.ƨ||
И==ϋ.Βη||И==ϋ.ΑΒ)&&Μ!=Κ.ў)
Ο(Β.ΑΛ);else if((И==ϋ.ΔΒ||И==ϋ.ΑЇ)&&Μ!=Κ.ў)
Ο(Β.ΑЈ);else
Ο(Β.ą);return;}Н=Vector3.Distance(θ,е);if(Н>ĩ){ĩ=Н;ΑЃ=false;}if(Μ==Κ.ў&&Δψ()==MyDetectedEntityType.SmallGrid)
П+=2;else П-=2;П=Math.Max(100,Math.Min(400,П));if(Ѐ>0&&Ѐ<П){if(Н>Ъ){if(П>150) Ъ=Н;else Ъ=(float) Math.Ceiling(Н);Ѐ=1;}else Ѐ++;}else{if(Ѐ>0){Ρ="Ship stuck! Retrying";Ъ=Н;Ѐ=0;Ĕ(false,true,0,σ*sensorRange);}н(ΑΤ(е,Math.Max(0,Ъ-σ)),Αψ(false));if(Ж<=wpReachedDist/2){Ѐ=1;Ъ=0;}
return;}Ĕ(false,true,σ*sensorRange,0);Vector3 ΗΓ=е+ǭ*Н;bool ΔЏ=false;if(Vector3.Distance(ΗΓ,θ)>0.3f){Vector3 ΖΔ=е+ǭ*(Н+0.1f);н(ΖΔ,4);ΔЏ=true;}else{float ǔ=Αψ(true);Vector3 ΓΙ=ΑΤ(е,Math.Max(Ы+1,Н+1));Ǟ(true,false,false,ΓΙ,ΓΙ-е,ǔ,ǔ);}bool ΒΣ=false;if(ќ==њ.ΒΜ||ќ==њ.ΒΚ)
{if(!ΔЏ){float ΒА=0;foreach(IMyTerminalBlock ǘ in ξ)
ΒА+=ΖΨ(ǘ,"","",ќ==њ.ΒΚ?new string[]{"STONE"}:null);if(ΒА>ΒΕ||Н<Ы||ΑЃ){ΑЅ=0;ƭ=Н;Ċ=(int)(Math.Max(Ċ,ƭ)+σ/2);}else{ΒΣ=Н-ƭ>2&&ΑЅ>=20;ΑЅ++;}ΒΕ=ΒА;}}else ΒΣ=Н>=Ċ;if(Ȩ!=б){Ο(Β.ȩ);Н=0;return;}if(ΒΣ){б++;Ο(Β.ȩ);Н=0;return;}}if(Ψ==Β.ȩ||Ψ==Β.ą||Ψ==Β.ΑΛ)
{if(Є){е=ȉ(ρ,π,false);Ф(Ε.β,Ε.ί,Ε.τ,false);с(ξ,ĭ);Ǡ(false);Ъ=Vector3.Distance(θ,е);Ĕ(false,true,0,σ*sensorRange);}н(е,Αψ(false));if(Vector3.Distance(θ,е)>=Ъ+5){с(ξ,false);Ǡ(true);Ρ="Can´t return!";}if(Ж<wpReachedDist){if(Ψ==Β.ȩ&&ΑΔ) Ο(Β.Ű);if(Ψ==Β.ȩ) Ο(Β.ď);
if(Ψ==Β.ΑΛ) Ο(Β.ΑΣ);if(Ψ==Β.ą){if(Θ.α) Ο(Β.ĕ);else{χ();Ȱ();Ρ="Can´t return, no dock found";}}return;}}if(Ψ==Β.Ǚ||Ψ==Β.Ш){if(Ψ==Β.Ш&&γ==Ξ.Ћ&&Μ!=Κ.ΰ){if(!ΒΑ()||ŭ(true)){Ο(Β.Ǚ);return;}}bool Αθ=false;bool ΒΘ=false;bool Γρ=false;float ń=0;bool ΓЍ=false;Ϊ Χ=null;
if(Є){if(Ψ==Β.Ǚ||Μ==Κ.ΰ){Ϊ Ϋ=ǿ();η=new Βί();η.Й=Ϋ;η.ŋ=followPathDock*σ;η.ΑЎ=useDockDirectionDist*σ;η.ń=10;η.ł.Add(Ϋ.Δ);Vector3 ĝ=new Vector3();if(ǹ(Ϋ,dockDist*σ,true,out ĝ))
η.ł.Add(ĝ);else η.ŋ*=1.5f;if(Μ==Κ.ΰ){if(Ϋ==Θ) η.ƞ=Ε.Δ;if(Ϋ==Ε) η.ƞ=Θ.Δ;η.Βώ=dockDist*σ*1.1f;}}else if(Ψ==Β.Ш){η=new Βί();η.Й=Ε;η.ŋ=followPathJob*σ;η.ΑЎ=useJobDirectionDist*σ;η.ń=10;η.ƞ=Θ.Δ;η.Βώ=dockDist*σ*1.1f;η.ł.Add(Ε.Δ);if(γ==Ξ.л){if(!Θ.α||Φ.Count==0){χ();return;}
float Ζπ=Vector3.Distance(Φ.First().Δ,Θ.Δ);float ΖΚ=Vector3.Distance(Φ.Last().Δ,Θ.Δ);if(Ζπ<ΖΚ) η.Й=Φ.Last();else η.Й=Φ.First();}}ƀ=new Vector3();ΓЍ=!ΗΒ(θ);с(ξ,false);Ǡ(true);ї=-1;double ǝ=-1;for(int i=Φ.Count-1;i>=0;i--){if(Vector3.Distance(Φ[i].Δ,η.ƞ)<=η.Βώ) continue;
double Ѓ=Vector3.Distance(Φ[i].Δ,θ);if(ǝ==-1||Ѓ<ǝ){ї=i;ǝ=Ѓ;}}ē=Ζχ(η.Й.Δ,ї);Ǘ=null;}ΗΘ(Φ,ē,η.ł,η.ŋ,Є,ref Ѐ);for(int i=0;i<η.ł.Count;i++){float Ѓ=Vector3.Distance(θ,η.ł[i]);if(Ѓ<=η.ŋ) Αθ=true;if(Ѓ<=η.ΑЎ) ΒΘ=true;}if(ΒΘ) ń=η.ń;float Ηι=Ǘ!=null?Ǘ.Л:Ȳ;
float ΕΞ=(float) Math.Max(Ȳ*0.1f*σ,wpReachedDist);if((Ж<ΕΞ)||Є){if(!Є) ї+=ē;if(ē==0||ї>Φ.Count-1||ї<0)
Αθ=true;else{ΑЂ=ē>0?Φ.Count-1-ї:ї;Χ=Φ[ї];Ǘ=Χ;if(ї>=1&&ї<Φ.Count-1)
ƀ=Χ.Δ-Φ[ї-ē].Δ;else Ǘ=null;ϊ=Χ.Δ;Γρ=true;}}if(ΒΘ)
Ф(η.Й.β,η.Й.ί,η.Й.τ,false);else if(ΓЍ)
Βά(η.Й.β,10,true);else if(Γρ&&Χ!=null){if(ē>0) Ф(Χ.β,Χ.ί,Χ.τ,90,false);else Ф(Χ.β,-Χ.ί,-Χ.τ,90,false);}Ǟ(true,false,true,ϊ,ƀ,Ǘ==null?0:Ǘ.Л,ń);if(Αθ){ΑЂ=0;if(Ψ==Β.Ǚ||Μ==Κ.ΰ){Ο(Β.Ƞ);return;}if(Ψ==Β.Ш&&ΑΔ){Ο(Β.Ű);return;}if(Ψ==Β.Ш){Ο(Β.ď);return;}
}}if(Ψ==Β.Ƞ||Ψ==Β.Αξ){Ϊ Ϋ=ǿ();if(Є){if(!ǹ(Ϋ,dockDist*σ,true,out ϊ)){Ƕ(Ц.ŵ);χ();return;}н(ϊ,0);Βά(Ϋ.β,90,true);}if(Ж<followPathDock*σ&&Ж!=-1){н(ϊ,10);Ф(Ϋ.β,Ϋ.ί,Ϋ.τ,false);}if(Э(MyShipConnectorStatus.Connectable)!=null||Э(MyShipConnectorStatus.Connected)!=null)
{Ο(Β.Ŷ);return;}if(Ж<wpReachedDist/2&&Ж!=-1){Ο(Β.Ƃ);return;}}if(Ψ==Β.Ƃ||Ψ==Β.č){if(Є){if(Ψ==Β.Ƃ){Ϊ Ϋ=ǿ();if(!ǹ(Ϋ,dockDist*σ,true,out ϊ)){Ƕ(Ц.ŵ);χ();return;}Ǟ(true,true,false,ϊ,0);Ф(Ϋ.β,Ϋ.ί,Ϋ.τ,10,false);}if(Ψ==Β.č){Ф(Ε.β,Ε.ί,Ε.τ,0.5f,false);ϊ=Ε.Δ;
Ǟ(true,true,false,ϊ,0);}}if(ƙ){ΑΖ(false,0,0,0,0);if(Ψ==Β.Ƃ) Ο(Β.Ŷ);if(Ψ==Β.č) χ();return;}}if(Ψ==Β.Ŷ){if(Э(MyShipConnectorStatus.Connected)!=null){if(Μ==Κ.ΰ) Ο(Β.ȝ);else Ο(Β.ȑ);return;}Ϊ Ϋ=ǿ();if(Є){П=0;ΖЇ=DateTime.Now;Ѐ=0;Ф(Ϋ.β,Ϋ.ί,Ϋ.τ,false);}Vector3I ΒЅ=new Vector3I((int) Ϋ.о.X,(int) Ϋ.о.Y,(int) Ϋ.о.Z);
IMySlimBlock Γη=Me.CubeGrid.GetCubeBlock(ΒЅ);float ΔЃ=dockingSpeed;float ΕΧ=dockingSpeed*5;float ΓБ=Math.Max(1.5f,Math.Min(5f,σ*0.15f));if(!ǹ(Ϋ,0,true,out ϊ)||!ǹ(Ϋ,ΓБ,true,out ƀ)||
Γη==null||!Γη.FatBlock.IsFunctional){Ƕ(Ц.ŵ);χ();return;}if(П==1||(Vector3.Distance(θ,ϊ)<=ΓБ*1.1f&&!Є))
П=1;else{Vector3 ΖΓ=У(Υ,ƀ-θ);Vector3 ΒΓ=У(Υ,Υ.GetNaturalGravity());float ΕΟ=Ɗ(ΖΓ,ΒΓ,null);ΔЃ=Math.Min(ΕΧ,ΕΟ);}Ǟ(true,false,false,ϊ,ϊ-θ,dockingSpeed,ΔЃ);if(Є) Ъ=(float) Ж;IMyShipConnector Βο=Э(MyShipConnectorStatus.Connectable);if(Βο!=null){Ǟ(false,false,false,ϊ,0);
if(Ѐ>0) Ѐ=0;Ѐ--;if(Ѐ<-5){Βο.Connect();if(Βο.Status==MyShipConnectorStatus.Connected){if(Μ==Κ.ΰ) Ο(Β.ȝ);else Ο(Β.ȑ);ΑΫ();ŏ(Ǹ,true);return;}}}else{float Γι=(float) Math.Round(Ж,1);if(Γι<Ъ){Ѐ=-1;Ъ=Γι;}else Ѐ++;if(Ѐ>20){Ο(Β.Αξ);return;}}}if(Ψ==Β.ȑ||Ψ==Β.ȝ||
Ψ==Β.ΓΒ||Ψ==Β.ΒϏ||Ψ==Β.ľ){bool ΒІ=false,ΑΨ=false;if(Μ==Κ.ΰ){if(ǿ()==Θ) ΒІ=true;else if(ǿ()==Ε) ΑΨ=true;}if(Є){ő=false;if(Э(MyShipConnectorStatus.Connected)==null){Ο(Β.Ț);return;}ΑΫ();if(ΒІ) ǌ(υ.ǎ);if(ΑΨ) ǌ(φ.ǎ);Ę=false;Ȋ=false;Ȑ=false;ţ=false;}if(Э(MyShipConnectorStatus.Connected)==null){χ();Ƕ(Ц.Γμ);return;}
if(γ!=Ξ.Ћ||з==-1||ǜ==в.None) Ȋ=true;else if(ǫ>=100f) Ȋ=true;else if(ǫ<=99f) Ȋ=false;if(γ!=Ξ.Ћ||г==-1||я.Count==0) Ȑ=true;else if(Ȓ>=100f) Ȑ=true;else if(Ȓ<=99) Ȑ=false;if(γ!=Ξ.Ћ||Р==-1||ȗ.Count==0) ţ=true;else ţ=ă>=Р;ĸ Ю=null;if(ΒІ) Ю=υ;
if(ΑΨ) Ю=φ;if(Ю!=null&&(Ю.Ї==δ.ΑΑ||Ю.Ї==δ.ΑΜ)) Ȋ=true;if(Ю!=null&&(Ю.Ї==δ.ΑЊ)) if(!Ę) Ȋ=false;if(Ю!=null&&(Ю.Ї==δ.Βξ||Ю.Ї==δ.Βι)) Ȑ=true;if(Ю!=null&&(Ю.Ї==δ.Βε)) if(!Ę) Ȑ=false;if(Ȇ){ChargeMode Δβ=Ȋ?ChargeMode.Auto:ChargeMode.Recharge;if(Ю!=null&&(Ю.Ї==δ.ΑΜ||Ю.Ї==δ.ΑΑ))
Δβ=ChargeMode.Discharge;Αζ(Δβ);ΑΠ(!Ȑ);}if(!Ę){if(Μ==Κ.ΰ)
Ę=γ!=Ξ.Ћ||ΕІ(Є,true)||Ź;else
Ę=γ!=Ξ.Ћ||ΔΡ();}else{if(!Ȋ) Ο(Β.ľ);if(!Ȑ) Ο(Β.ΒϏ);if(!ţ) Ο(Β.ΓΒ);Є=false;}if(Ę&&Ȋ&&Ȑ&&ţ){Αζ(ChargeMode.Auto);ΑΠ(false);if(γ==Ξ.Ћ){if(Μ==Κ.ΰ){if(ǿ()==Θ) ǌ(υ.ћ);else if(ǿ()==Ε) ǌ(φ.ћ);if(ǿ()==Θ) Ņ(Ε,Ξ.ħ);else Ņ(Θ,Ξ.Ħ);}}Ο(Β.Ț);return;}}if(Ψ==Β.Ț){if(Є){IMyShipConnector ǵ=Э(MyShipConnectorStatus.Connected);
if(ǵ==null){Ο(Β.Ш);return;}IMyShipConnector ǻ=ǵ.OtherConnector;ΓЇ(ǵ,false);ŏ(Ǹ,false);Ϊ Ϋ=null;if(Vector3.Distance(ǵ.GetPosition(),Θ.Δ)<5f&&Θ.α) Ϋ=Θ;if(Vector3.Distance(ǵ.GetPosition(),Ε.Δ)<5f&&Ε.α) Ϋ=Ε;if(Ϋ!=null){if(!ǹ(Ϋ,dockDist*σ,true,out ϊ)){Ƕ(Ц.ŵ);χ();return;}
н(ϊ,5);Ф(Ϋ.β,Ϋ.ί,Ϋ.τ,false);}else н(θ+ǻ.WorldMatrix.Forward*dockDist*σ,5);if(γ==Ξ.Ћ) Ƕ(Ц.ơ);}if(Ж<wpReachedDist){с(ж,true);Ο(Β.Ш);return;}}if(Ψ==Β.Ű){if(Є){Ǡ(true);с(ξ,false);ϊ=Ε.Δ;н(ϊ,20);Ф(Ε.β,Ε.ί,Ε.τ,false);}if(Ж<wpReachedDist/2){Ο(Β.č);return;}}if(Ψ==Β.ĕ){
if(Є){Ǡ(true);с(ξ,false);int А=-1;double ǝ=-1;for(int i=Φ.Count-1;i>=0;i--){double Ѓ=Vector3.Distance(Φ[i].Δ,θ);if(ǝ==-1||Ѓ<ǝ){А=i;ǝ=Ѓ;}}if(А==-1){Ο(Β.Ǚ);return;}ϊ=Φ[А].Δ;н(ϊ,10);Ф(Ε.β,Ε.ί,Ε.τ,false);}if(Ж<wpReachedDist){Ο(Β.Ǚ);return;}}if(Ψ==Β.ΑΣ)
{bool ǖ=false;if(Є){Ǡ(true);if((И==ϋ.ΒЎ||И==ϋ.ƨ)&&Ƒ()&&
Ĥ(ǭ,Υ.GetNaturalGravity())<25&&Т>=2&&й>=2){Vector3 Ų=θ;if(ρ>0&&π<й-1) Ų=ȉ(ρ-1,π+1,true);else if(ρ<Т-1&&π<й-1) Ų=ȉ(ρ+1,π+1,true);else if(ρ<Т-1&&π>0) Ų=ȉ(ρ+1,π-1,true);else if(ρ>0&&π>0) Ų=ȉ(ρ-1,π-1,true);else ǖ=true;if(!ǖ) н(Ų,10);
}else ǖ=true;}if(Ж<wpReachedDist/2) ǖ=true;if(ǖ){Ο(Β.Ʃ);return;}}if(Ψ==Β.ΑЈ||Ψ==Β.Ʃ){if(Є){Ǟ(true,true,false,θ,0);с(ξ,false);Ǡ(true);Ѐ=-1;П=И==ϋ.Βη||И==ϋ.ΑΒ?0:-1;}bool đ=!ΒΑ();int ƌ=ȁ("STONE","ORE",В.Ě);if(И==ϋ.ΑЇ||И==ϋ.ΑΒ||И==ϋ.ƨ)
ƌ+=ȁ("ICE","ORE",В.Ě);bool Εχ=ƌ>0;bool Βζ=false;if(П>=0){float Ğ=(float) Math.Sin(ΔΨ(П))*ȇ/3f;float ΖЎ=(float) Math.Cos(ΔΨ(П))*ǯ/3f;Vector3 Εα=ȉ(ρ,π,true)+ΑЉ(ǭ,ċ*-1,new Vector3(Ğ,ΖЎ,0));н(Εα,0.3f);if(Ж<Math.Min(ȇ,ǯ)/10f) П+=5f;if(П>=360) П=0;}if(Ѐ==-1||ƌ<Ѐ){Ѐ=ƌ;Ъ=0;}
else{Ъ++;if(Ъ>50) Βζ=true;}if(!Εχ||đ||Βζ){if(!đ){int Ζά=ȁ("","ORE",В.Ě);if(ŭ(true)) đ=true;else if(100-(Ѕ(Ζά,Δό)*100)<minEjection) đ=true;else Ƕ(Ц.ơ);}if(Βζ&&đ) Ρ="Ejection failed";if(Ψ==Β.Ʃ){if(đ){if(Θ.α) Ο(Β.ĕ);else{χ();Ȱ();Ρ="Can´t return, no dock found";}}
else Ο(Β.ď);}else if(đ) Ο(Β.ą);else Ο(Β.Ů);return;}}Є=false;}void ΗΘ(List<Ϊ>Ȟ,int ψ,List<Vector3>Ŭ,float Ő,bool ђ,ref int Ǖ){if(ђ){for(int i=0;i<Ȟ.Count;i++) Ȟ[i].Л=0;Ǖ=-1;return;}if(ψ==0) return;int р=ψ*-1;if(Ǖ==-1) Ǖ=р>0?1:Ȟ.Count-2;int ů=0;while(Ǖ>=1&&Ǖ<Ȟ.Count-1)
{if(ů>50) return;ů++;try{if((р<0&&Ǖ>=1)||(р>0&&Ǖ<=Ȟ.Count-2)){Ϊ ε=Ȟ[Ǖ];bool ΓΜ=false;for(int j=0;j<Ŭ.Count;j++)
if(Vector3.Distance(ε.Δ,Ŭ[j])<=Ő){ΓΜ=true;break;}if(!ΓΜ){Ϊ Ƅ=Ȟ[Ǖ-р];Ϊ ΓΚ=Ȟ[Ǖ+р];Vector3 ΖΝ=ε.Δ-ΓΚ.Δ;Vector3 Βσ=Ƅ.Δ-ε.Δ;Vector3 ΗΔ=ε.Δ+Vector3.Normalize(ΖΝ)*Βσ.Length();Vector3 Εϋ=Ƅ.Δ-ΗΔ;Vector3 Ʒ=Ē(ψ>0?ε.ί:ε.ί*-1,ε.β*-1,Εϋ);Vector3 ΗΡ=Ē(ψ>0?ε.ί:ε.ί*-1,ε.β*-1,Βσ);
Vector3 ƒ=Ē(ψ>0?ε.ί:ε.ί*-1,ε.β*-1,ε.ς);ε.Л=(float) Math.Sqrt(Math.Pow(Ƅ.Л,2)+Math.Pow(Ɗ(-ΗΡ,ƒ,ε),2));for(int j=0;j<Ŭ.Count;j++)
if(Vector3.Distance(Ƅ.Δ,Ŭ[j])<=Ő){Vector3 ΑΙ=Ē(ψ>0?ε.ί:ε.ί*-1,ε.β*-1,Ŭ[j]-ε.Δ);float ΕЍ=Ɗ(-ΑΙ,ƒ,ε);ε.Л=Math.Min(ε.Л,ΕЍ)/2f;}if(Ʒ.Length()==0) Ʒ=new Vector3(0,0,1);Vector3 ΖЂ=Ē(ε.ί,ε.β*-1,ε.ς);float ΗΙ=œ(-Ʒ,ΖЂ,ε);float Ƙ=Ѕ(ΗΙ,ě);float Βθ=(float) Math.Sqrt(Ѕ(Ʒ.Length()*1.0f,0.5f*Ƙ));
ε.Л=Math.Min(ε.Л,(Βσ.Length()/Βθ)*ǚ);}}}catch{return;}Ǖ+=р;}Ǖ=-1;}void ΑА(bool ђ){if(ђ){Ũ=0;return;}if(Μ==Κ.ΰ) return;float ǖ=б*Math.Max(1,Ы);if(Ȩ==б) ǖ+=Math.Min(Ы,Н);float Εή=Т*й*Math.Max(1,Ы);Ũ=Math.Max(Ũ,(float) Math.Min(ǖ/Εή*100.0,100));}MyDetectedEntityType Δψ()
{try{if(ǲ(μ,true)&&!μ.LastDetectedEntity.IsEmpty()) return μ.LastDetectedEntity.Type;}catch{}return MyDetectedEntityType.None;}float Αψ(bool ǣ){if(Μ==Κ.ў&&Δψ()==MyDetectedEntityType.None&&!Ÿ(μ,true))
return fastSpeed;else return ǣ?ĥ:ļ;}void Ει(){float Δα=0,Γχ=0,ȭ=0,Αε=0;for(int i=0;i<ȥ.Count;i++){IMyBatteryBlock Ɓ=ȥ[i];if(!ǲ(Ɓ,true)) continue;Δα+=Ɓ.MaxStoredPower;Γχ+=Ɓ.CurrentStoredPower;ȭ+=Ɓ.CurrentInput;Αε+=Ɓ.CurrentOutput;}ǫ=(float) Math.Round(Ѕ(Γχ,Δα)*100,1);
if(ȭ>=Αε) ǜ=в.ľ;else ǜ=в.Γψ;if(ȭ==0&&Αε==0||ǫ==100.0) ǜ=в.ю;if(ȥ.Count==0) ǜ=в.None;}void Ζκ(){float Γω=0;for(int i=0;i<я.Count;i++){IMyGasTank Δω=я[i];if(!ǲ(Δω,true)) continue;Γω+=(float) Δω.FilledRatio;}Ȓ=Ѕ(Γω,я.Count)*100f;}void ΕΩ(){ă=0;try{for(int i=0;i<ȗ.Count;i++)
{IMyReactor Βπ=ȗ[i];if(!ǲ(Βπ,true)) continue;List<MyInventoryItem>Ќ=new List<MyInventoryItem>();Βπ.GetInventory(0).GetItems(Ќ);float Ϗ=0;for(int j=0;j<Ќ.Count;j++){MyInventoryItem Ў=Ќ[j];if(Ў.Type.SubtypeId.ToUpper()=="URANIUM"&&Ў.Type.TypeId.ToUpper().Contains("_INGOT"))
Ϗ+=(float) Ў.Amount;}if(Ϗ<ă||i==0){ă=Ϗ;ΓΖ=Βπ.CustomName;}}}catch(Exception e){Ȥ=e;}}void ΗΠ(){ȣ=0;ȟ=0;try{for(int i=0;i<Į.Count;i++){IMyTerminalBlock Σ=Į[i];if(!ǲ(Σ,true)) continue;ȟ+=(float) Σ.GetInventory(0).CurrentVolume;ȣ+=(float) Σ.GetInventory(0).MaxVolume;
}Ʈ=(float) Math.Min(Math.Round(Ѕ(ȟ,ȣ)*100,1),100.0);}catch(Exception e){Ȥ=e;}}void Ζέ(){try{Ǔ.Clear();for(int i=0;i<Į.Count;i++){IMyTerminalBlock Σ=Į[i];if(!ǲ(Σ,true)) continue;ΔЄ(Σ,В.Ģ);}if(И!=ϋ.ΒЈ){for(int i=0;i<Ā.Count;i++){IMyTerminalBlock Σ=Ā[i];if(!ǲ(Σ,true)) continue;
ΔЄ(Σ,В.ΕЀ);}}ΕЉ(Ǔ);}catch(Exception e){Ȥ=e;}}void ΖΧ(){if(ǅ){if(ΓΠ().Count>ǈ){ǅ=false;if(Я!=Ч.Ŏ){χ();if(Я==Ч.Βή) Ȱ();if(Я==Ч.Ɛ)
if(Θ.α) ƕ();else Ȱ();}Ρ="Damage detected";}}}bool ΒΑ(){if(!ΑΘ) return true;if(γ==Ξ.Ћ){if(з>0&&ǜ!=в.None)
if(ǫ<=з){Ρ="Low energy! Move home";return false;}if(Р>0&&ȗ.Count>0)
if(ă<=Р){Ρ="Low fuel: "+ΓΖ;return false;}if(г>0&&я.Count>0)
if(Ȓ<=г){Ρ="Low hydrogen";return false;}}return true;}List<IMyTerminalBlock>ΓΠ(){List<IMyTerminalBlock>Ă=new List<IMyTerminalBlock>();for(int i=0;i<ś.Count;i++){IMyTerminalBlock Σ=ś[i];if(Ÿ(Σ,false)) Ă.Add(Σ);}return Ă;}bool Ÿ(IMyTerminalBlock Σ,bool Βν){return(!ǲ(Σ,Βν)||!Σ.IsFunctional);
}bool ǲ(IMyTerminalBlock Σ,bool Βν){if(Σ==null) return false;try{IMyCubeBlock Δώ=Me.CubeGrid.GetCubeBlock(Σ.Position).FatBlock;if(Βν) return Δώ==Σ;else return Δώ.GetType()==Σ.GetType();}catch{return false;}}float ΖΨ(IMyTerminalBlock Σ,String и,String Δμ,String[]ǥ){float ǰ=0;for(int i=0;i<Σ.InventoryCount;i++)
{IMyInventory Ζξ=Σ.GetInventory(i);List<MyInventoryItem>Ќ=new List<MyInventoryItem>();Ζξ.GetItems(Ќ);foreach(MyInventoryItem Ў in Ќ){if(ǥ!=null&&(ǥ.Contains(Ў.Type.TypeId.ToUpper())||ǥ.Contains(Ў.Type.SubtypeId.ToUpper())))
continue;if((и==""||Ў.Type.TypeId.ToUpper()==и)&&(Δμ==""||Ў.Type.SubtypeId.ToUpper()==Δμ))
ǰ+=(float) Ў.Amount;}}return ǰ;}м ΖЃ(String έ,String ν,В Б,bool ΕЎ){έ=έ.ToUpper();ν=ν.ToUpper();for(int i=0;i<Ǔ.Count;i++){м Ў=Ǔ[i];if(Ў.έ.ToUpper()==έ&&Ў.ν.ToUpper()==ν&&(Ў.Ł==Б||Б==В.Ě))
return Ў;}м Ω=null;if(ΕЎ){Ω=new м(έ,ν,0,Б);Ǔ.Add(Ω);}return Ω;}int ȁ(String έ,String ν,В Б){return ȁ(έ,ν,Б,null);}int ȁ(String έ,String ν,В Б,String[]ǥ){int ǰ=0;έ=έ.ToUpper();ν=ν.ToUpper();for(int i=0;i<Ǔ.Count;i++){м Ў=Ǔ[i];if(ǥ!=null&&ǥ.Contains(Ў.έ.ToUpper())) continue;
if((έ==""||Ў.έ.ToUpper()==έ)&&(ν==""||Ў.ν.ToUpper()==ν)&&(Ў.Ł==Б||Б==В.Ě))
ǰ+=Ў.Ϗ;}return ǰ;}void ΔЄ(IMyTerminalBlock Σ,В Б){for(int i=0;i<Σ.InventoryCount;i++){List<MyInventoryItem>Ќ=new List<MyInventoryItem>();Σ.GetInventory(i).GetItems(Ќ);for(int j=0;j<Ќ.Count;j++)
ΖЃ(Ќ[j].Type.SubtypeId,Ќ[j].Type.TypeId.Replace("MyObjectBuilder_",""),Б,true).Ϗ+=(int) Ќ[j].Amount;}}void ΕЉ(List<м>а){for(int i=а.Count-1;i>0;i--)
for(int j=0;j<i;j++){м a=а[j];м b=а[j+1];if(a.Ϗ<b.Ϗ) а.Move(j,j+1);}}bool ŭ(bool Ηΰ){if(Ȁ&&Μ!=Κ.ΰ)
if(Е!=-1&&ě>=Е){Ρ="Ship too heavy";return true;}if(Ʈ>=Ǥ||ő){ő=false;Ρ="Ship is full";return true;}return false;}bool ΔΡ(){String[]ǥ=null;if(!ȃ) ǥ=new string[]{"ICE"};if(Μ==Κ.Ŗ) return ȁ("","ORE",В.Ģ,ǥ)==0;if(Μ==Κ.ў) return ȁ("","COMPONENT",В.Ģ,ǥ)==0;else return ȁ("","",В.Ģ,ǥ)==0;
}bool Εφ(){List<IMyCockpit>ΒЂ=new List<IMyCockpit>();ω.GetBlocksOfType(ΒЂ,q=>q.CubeGrid==Me.CubeGrid);for(int i=0;i<ΒЂ.Count;i++)
if(ΒЂ[i].IsUnderControl) return true;return false;}bool ΕІ(bool ђ,bool ΑΗ){IMyShipConnector Ǒ=Э(MyShipConnectorStatus.Connected);if(Ǒ==null) return false;if(Vector3.Distance(Θ.Δ,Ǒ.GetPosition())<5)
return ΓІ(υ,ђ,ΑΗ);if(Vector3.Distance(Ε.Δ,Ǒ.GetPosition())<5)
return ΓІ(φ,ђ,ΑΗ);return false;}bool ΓІ(ĸ Ǵ,bool ђ,bool ΑΗ){if(ђ) Ǵ.ΖΪ();Ǵ.Ζρ();bool Ь=false;String к="";switch(Ǵ.Ї){case δ.ΒΙ:{к="Waiting for command";Ь=false;break;}case δ.Δυ:{к="Waiting for cargo";Ь=ŭ(true);break;}case δ.Δά:{к="Unloading";Ь=ΔΡ();break;}case δ.ΑІ:{Ь=true;break;}
case δ.ΑЊ:{к="Charging batteries";Ь=ǫ>=100f;break;}case δ.ΑΑ:{к="Discharging batteries";Ь=ǫ<=25f;break;}case δ.ΑΜ:{к="Discharging batteries";Ь=ǫ<=0f;break;}case δ.Βε:{к="Filling up hydrogen";Ь=Ȓ>=100f;break;}case δ.Βξ:{к="Unloading hydrogen";Ь=Ȓ<=25f;break;}
case δ.Βι:{к="Unloading hydrogen";Ь=Ȓ<=0f;break;}case δ.Αώ:{bool Δη=Εφ();if(!Δη) Ǵ.Βμ=true;Ь=Ǵ.Βμ&&Δη;к="Waiting for passengers";break;}}if(!Ь) Ǵ.ΑЌ(true);if(Ь&&Ǵ.ΒΟ()){Ь=Ǵ.ΑЌ(false);к="Undocking in: "+ΒΖ((int) Math.Max(0,Ǵ.і-Ǵ.Ȫ));}if(ΑΗ) ΔΑ=к;return Ь;}void ΖΦ()
{if(!ı) return;if(ξ.Count<=1) return;float ΔΠ=0,Γΰ=0;for(int i=0;i<ξ.Count;i++){IMyTerminalBlock ǘ=ξ[i];if(Ÿ(ǘ,true)) continue;ΔΠ+=(float) ǘ.GetInventory(0).MaxVolume;Γΰ+=(float) ǘ.GetInventory(0).CurrentVolume;}float Γτ=(float) Math.Round(Ѕ(Γΰ,ΔΠ),5);for(int Γε=0;Γε<Math.Max(1,Math.Floor(ξ.Count/10f));Γε++)
{float ΒЇ=0,ΑЁ=0;float Δέ=0,ΔΙ=0;IMyTerminalBlock Ǿ=null,ȕ=null;for(int i=0;i<ξ.Count;i++){IMyTerminalBlock ǘ=ξ[i];if(Ÿ(ǘ,true)) continue;float Αχ=(float) ǘ.GetInventory(0).MaxVolume;float ƪ=Ѕ((float) ǘ.GetInventory(0).CurrentVolume,Αχ);if(Ǿ==null||ƪ>ΒЇ){Ǿ=ǘ;ΒЇ=ƪ;Δέ=Αχ;}
if(ȕ==null||ƪ<ΑЁ){ȕ=ǘ;ΑЁ=ƪ;ΔΙ=Αχ;}}if(Ǿ==null||ȕ==null||Ǿ==ȕ) return;if(checkConveyorSystem&&!Ǿ.GetInventory(0).IsConnectedTo(ȕ.GetInventory(0))){if(Αη>20) Ρ="Inventory balancing failed";else Αη++;return;}Αη=0;List<MyInventoryItem>Ќ=new List<MyInventoryItem>();
Ǿ.GetInventory(0).GetItems(Ќ);float ō=0;if(Ќ.Count==0) continue;MyInventoryItem Ƣ=Ќ[0];String ΓΤ=Ƣ.Type.TypeId+Ƣ.Type.SubtypeId;if(!Γό.TryGetValue(ΓΤ,out ō)){if(ΕЋ(Ǿ.GetInventory(0),0,ȕ.GetInventory(0),out ō))
Γό.Add(ΓΤ,ō);else return;}float Εξ=((ΒЇ-Γτ)*Δέ/ō);float Ζώ=((Γτ-ΑЁ)*ΔΙ/ō);int Βδ=(int) Math.Min(Ζώ,Εξ);if(Βδ<=0) return;if((float) Ƣ.Amount<Βδ)
Ǿ.GetInventory(0).TransferItemTo(ȕ.GetInventory(0),0,null,null,Ƣ.Amount);else
Ǿ.GetInventory(0).TransferItemTo(ȕ.GetInventory(0),0,null,null,Βδ);}}bool ΕЋ(IMyInventory ŷ,int Α,IMyInventory Ζϋ,out float ΔΚ){ΔΚ=0;float ΖІ=(float) ŷ.CurrentVolume;List<MyInventoryItem>ΒБ=new List<MyInventoryItem>();ŷ.GetItems(ΒБ);float ΓЂ=0;for(int i=0;i<ΒБ.Count;i++) ΓЂ+=(float) ΒБ[i].Amount;
ŷ.TransferItemTo(Ζϋ,Α,null,null,1);float ΓЎ=ΖІ-(float) ŷ.CurrentVolume;List<MyInventoryItem>Βω=new List<MyInventoryItem>();ŷ.GetItems(Βω);float ΔΛ=0;for(int i=0;i<Βω.Count;i++) ΔΛ+=(float) Βω[i].Amount;if(ΓЎ==0f||!Βύ(0.9999,ΓЂ-ΔΛ,1.0001))
return false;ΔΚ=ΓЎ;return true;}void Ζλ(){Vector3 ź=ϊ-θ;if(ź.Length()==0) ź=new Vector3(0,0,-1);Vector3 ΑΙ=У(Υ,ź);Vector3 Γν=Vector3.Normalize(ΑΙ);Vector3 į=У(Υ,Υ.GetNaturalGravity());float ΗΣ=Βλ>0?Math.Max(0,1-Ĥ(ź,ΓΛ)/5):0;float Л=(float) Math.Min((Βτ>0?Βτ:1000f),Math.Max(Ɗ(-ΑΙ,į,null),Βλ*ΗΣ));
if(!ΓЁ) Л=0;if(Γκ) Л=Math.Max(0,1-ǂ/ƿ)*Л;if(generalSpeedLimit>0) Л=Math.Min(generalSpeedLimit,Л);if(Γύ) Л*=(float) Math.Min(1,Ѕ(ź.Length(),wpReachedDist)/2);Vector3 ΔЀ=У(Υ,Υ.GetShipVelocities().LinearVelocity);float ΕΨ=(float)(Math.Max(0,15-Ĥ(-Γν,-ΔЀ))/15)*0.85f+0.15f;
Αρ+=Math.Sign(ΕΨ-Αρ)/10f;Vector3 ȧ=Γν*Л*Αρ-(ΔЀ);Vector3 Αό=Βέ(ȧ,null);if(Ƽ&&Ж>0.1f){ȧ.X*=Αϋ(ȧ.X,ref ƛ.X,1f,Αό.X,20);ȧ.Y*=Αϋ(ȧ.Y,ref ƛ.Y,1f,Αό.Y,20);ȧ.Z*=Αϋ(ȧ.Z,ref ƛ.Z,1f,Αό.Z,20);}else ƛ=new Vector3(1,1,1);ŕ=ě*ȧ-į*ě;ΔΤ(ŕ,Ƽ);Ж=Vector3.Distance(θ,ϊ);
}float Αϋ(float value,ref float М,float р,float Ǽ,float ΒΨ){value=Math.Sign(Math.Round(value,2));if(value==Math.Sign(М)) М+=Math.Sign(М)*р;else М=value;if(value==0) М=1;float Ω=Math.Abs(М);if(Ω<ΒΨ||Ǽ==0) return Ω;М=Math.Min(ΒΨ,Math.Max(-ΒΨ,М));Ω=Math.Abs(Ǽ);return Ω;
}void Δρ(){float д=90,т=90,ч=90;float ǔ=(float)(Me.CubeGrid.GridSizeEnum==MyCubeSize.Small?gyroSpeedSmall:gyroSpeedLarge)/100f;Vector3 ǣ,ш,ž,Αή;if(Αϊ){ǣ=Vector3.Normalize(ϊ-θ);ž=У(Υ,ǣ);ш=У(Υ,ΑΝ);д=Ĥ(ž,new Vector3(0,-1,0))-90;т=Ą(ш,new Vector3(-1,0,0),ш.Y);
ч=Ą(ž,new Vector3(-1,0,0),ž.Z);}else{ǣ=Αγ;ш=У(Υ,ΑΝ);ž=У(Υ,Αγ);Αή=У(Υ,Γί);д=Ą(ш,new Vector3(0,0,1),ш.Y);т=Ą(ш,new Vector3(-1,0,0),ш.Y);ч=Ą(Αή,new Vector3(0,0,1),Αή.X);}if(ΔА&&Ƒ()){Vector3 ΒΓ=Υ.GetNaturalGravity();ш=У(Υ,ΒΓ);д=Ą(ш,new Vector3(0,0,1),ш.Y);
т=Ą(ш,new Vector3(-1,0,0),ш.Y);}if(!Βύ(-45,т,45)){д=0;ч=0;}if(!Βύ(-45,ч,45)) д=0;ΑΖ(ΓΑ,1,(-д)*ǔ,(-ч)*ǔ,(-т)*ǔ);ǂ=Math.Max(Math.Abs(д),Math.Max(Math.Abs(т),Math.Abs(ч)));ƙ=ǂ<=ƿ;}void ΕЇ(IMyTerminalBlock Ƭ){if(Ƭ==null) return;џ=new float[3,2];ц=new Dictionary<string,float[,]>();
for(int i=0;i<Ǫ.Count;i++){IMyThrust Х=Ǫ[i];if(!Х.IsFunctional) continue;Vector3 ψ=У(Ƭ,Х.WorldMatrix.Backward);float ȫ=Х.MaxEffectiveThrust;if(Math.Round(ψ.X,2)!=0.0)
if(ψ.X>=0) џ[0,0]+=ȫ;else џ[0,1]-=ȫ;if(Math.Round(ψ.Y,2)!=0.0)
if(ψ.Y>=0) џ[1,0]+=ȫ;else џ[1,1]-=ȫ;if(Math.Round(ψ.Z,2)!=0.0)
if(ψ.Z>=0) џ[2,0]+=ȫ;else џ[2,1]-=ȫ;String и=ΔϏ(Х);float[,]ъ=null;if(ц.ContainsKey(и)) ъ=ц[и];else{ъ=new float[3,2];ц.Add(и,ъ);}float Ǽ=Х.MaxThrust;if(Math.Round(ψ.X,2)!=0.0)
if(ψ.X>=0) ъ[0,0]+=Ǽ;else ъ[0,1]-=Ǽ;if(Math.Round(ψ.Y,2)!=0.0)
if(ψ.Y>=0) ъ[1,0]+=Ǽ;else ъ[1,1]-=Ǽ;if(Math.Round(ψ.Z,2)!=0.0)
if(ψ.Z>=0) ъ[2,0]+=Ǽ;else ъ[2,1]-=Ǽ;}}static String ΔϏ(IMyThrust Х){return Х.BlockDefinition.SubtypeId;}Vector3 Βυ(Vector3 у,float[,]Ŀ){return new Vector3(
у.X>=0?Ŀ[0,0]:Ŀ[0,1],
у.Y>=0?Ŀ[1,0]:Ŀ[1,1],
у.Z>=0?Ŀ[2,0]:Ŀ[2,1]);}bool Δξ(Ϊ Χ,String и,out float ΒЏ){ΒЏ=0;int Α=Ǧ.IndexOf(и);if(Α==-1||Χ.ǒ==null||Α>=Χ.ǒ.Length)
return false;ΒЏ=Χ.ǒ[Α];if(ΒЏ==-1) return false;return true;}Vector3 Βέ(Vector3 у,Ϊ Χ){if(Χ!=null){Vector3 Ω=new Vector3();for(int i=0;i<ц.Keys.Count;i++){String и=ц.Keys.ElementAt(i);float Ū=0;if(!Δξ(Χ,и,out Ū))
return Βυ(у,џ);Ω+=Βυ(у,ц.Values.ElementAt(i))*Ū;}return Ω;}return Βυ(у,џ);}float œ(Vector3 у,Ϊ Χ){return œ(у,new Vector3(),Χ);}float œ(Vector3 у,Vector3 ς,Ϊ Χ){Vector3 ΕА=Βέ(у,Χ);Vector3 ȫ=ΕА+ς*ě;float Ď=(ȫ/у).AbsMin();return(float)(у*Ď).Length();}float Ɗ(Vector3 Ǆ,Vector3 į,Ϊ Χ)
{if(Ǆ.Length()==0) return 0;float Γφ=1;if(į.Length()>0) Γφ=Math.Min(1,Ĥ(-į,Ǆ)/90)*0.4f+0.6f;float ŕ=œ(Ǆ,į,Χ);if(ŕ==0) return 0.1f;float Ƙ=Ѕ(ŕ,ě);float Βθ=(float) Math.Sqrt(Ѕ(Ǆ.Length(),Ƙ*0.5f));return Ƙ*Βθ*Γφ*ǚ;}float Ɲ(Vector3 ǣ,Vector3 Ǐ,Vector3 ς,Ϊ Χ){if(ς.Length()==0f) return 0;
Vector3 ƒ=Ē(ǣ,Ǐ,Vector3.Normalize(ς));float ѓ=œ(-ƒ,Χ);return ѓ/ς.Length();}void ΔЊ(bool Ζμ){float щ=0;float ΑΧ=0.9f;if(Ζμ){Е=-1;ȳ=0;Ǘ=null;if(γ!=Ξ.л&&Ε.ς.Length()!=0){щ=ΑΧ*Ɲ(Ε.ί,Ε.β*-1,Ε.ς,null);if(щ<Е||Е==-1) Е=щ;}if(Θ.α&&Θ.ς.Length()!=0){щ=ΑΧ*Ɲ(Θ.ί,Θ.β*-1,Θ.ς,null);
if(щ<Е||Е==-1) Е=щ;}return;}if(ȳ==-1) return;if(ȳ>=0){int Γδ=0;while(ȳ<Φ.Count){if(Γδ>100) return;Γδ++;Ϊ Χ=Φ[ȳ];if(Χ.ς.Length()!=0f){щ=ΑΧ*Math.Min(
Ɲ(Χ.ί,Χ.β*-1,Χ.ς,Χ),
Ɲ(Χ.ί*-1,Χ.β*-1,Χ.ς,Χ));if(щ<Е||Е==-1) Е=щ;}else Ǘ=Χ;ȳ++;}ȳ=-1;}bool Βχ=true;float Ș=0;if(Ǘ!=null){for(int i=0;i<ц.Count;i++){String и=ц.Keys.ElementAt(i);float[,]ъ=ц.Values.ElementAt(i);float Ū=0;if(!Δξ(Ǘ,и,out Ū)){Βχ=false;break;}for(int a=0;a<ъ.GetLength(0);a++)
for(int b=0;b<ъ.GetLength(1);b++){float Ć=Math.Abs(ъ[a,b]*Ū);if(Ć==0) continue;Βχ=true;if(Ș==0||Ć<Ș) Ș=Ć;}}}if(!Βχ){for(int a=0;a<џ.GetLength(0);a++)
for(int b=0;b<џ.GetLength(1);b++){float Ć=Math.Abs(џ[a,b]);if(Ć==0) continue;if(Ș==0||Ć<Ș) Ș=Ć;}}if(Ș>0){float ΖЅ=Me.CubeGrid.GridSizeEnum==MyCubeSize.Small?minAccelerationSmall:minAccelerationLarge;щ=Ѕ(Ș,ΖЅ);if(щ>0)
if(щ<Е||Е==-1) Е=щ;}}void ΔΤ(Vector3 ѓ,bool Ё){if(!Ё){for(int i=0;i<Ǫ.Count;i++)
Ǫ[i].SetValueFloat("Override",0.0f);return;}Vector3 ΓΕ=Βέ(ѓ,null);float Εί=Math.Min(1,Math.Abs(Ѕ(ѓ.X,ΓΕ.X)));float ΕЈ=Math.Min(1,Math.Abs(Ѕ(ѓ.Y,ΓΕ.Y)));float Εά=Math.Min(1,Math.Abs(Ѕ(ѓ.Z,ΓΕ.Z)));for(int i=0;i<Ǫ.Count;i++){IMyThrust Х=Ǫ[i];Vector3 ψ=Ες(У(Υ,Х.WorldMatrix.Backward),1);
if(ψ.X!=0&&Math.Sign(ψ.X)==Math.Sign(ѓ.X))
Х.SetValueFloat("Override",Х.MaxThrust*Εί);else if(ψ.Y!=0&&Math.Sign(ψ.Y)==Math.Sign(ѓ.Y))
Х.SetValueFloat("Override",Х.MaxThrust*ΕЈ);else if(ψ.Z!=0&&Math.Sign(ψ.Z)==Math.Sign(ѓ.Z))
Х.SetValueFloat("Override",Х.MaxThrust*Εά);else
Х.SetValueFloat("Override",0.0f);}}void ΑΖ(bool Ё,float Εκ,float д,float ч,float т){for(int i=0;i<ƣ.Count;i++){IMyGyro ώ=ƣ[i];ώ.GyroOverride=Ё;if(!Ё) ώ.GyroPower=100;else ώ.GyroPower=Εκ;if(!Ё) continue;Vector3 ǩ=Υ.WorldMatrix.Forward;Vector3 ŉ=Υ.WorldMatrix.Right;Vector3 Ǐ=Υ.WorldMatrix.Up;
Vector3 Ĵ=ώ.WorldMatrix.Forward;Vector3 ģ=ώ.WorldMatrix.Up;Vector3 ĳ=ώ.WorldMatrix.Left*-1;if(Ĵ==ǩ) ώ.SetValueFloat("Roll",т);else if(Ĵ==(ǩ*-1)) ώ.SetValueFloat("Roll",т*-1);else if(ģ==(ǩ*-1)) ώ.SetValueFloat("Yaw",т);else if(ģ==ǩ) ώ.SetValueFloat("Yaw",т*-1);else if(ĳ==ǩ) ώ.SetValueFloat("Pitch",т);
else if(ĳ==(ǩ*-1)) ώ.SetValueFloat("Pitch",т*-1);if(ĳ==(ŉ*-1)) ώ.SetValueFloat("Pitch",д);else if(ĳ==ŉ) ώ.SetValueFloat("Pitch",д*-1);else if(ģ==ŉ) ώ.SetValueFloat("Yaw",д);else if(ģ==(ŉ*-1)) ώ.SetValueFloat("Yaw",д*-1);else if(Ĵ==(ŉ*-1)) ώ.SetValueFloat("Roll",д);
else if(Ĵ==ŉ) ώ.SetValueFloat("Roll",д*-1);if(ģ==(Ǐ*-1)) ώ.SetValueFloat("Yaw",ч);else if(ģ==Ǐ) ώ.SetValueFloat("Yaw",ч*-1);else if(ĳ==Ǐ) ώ.SetValueFloat("Pitch",ч);else if(ĳ==(Ǐ*-1)) ώ.SetValueFloat("Pitch",ч*-1);else if(Ĵ==Ǐ) ώ.SetValueFloat("Roll",ч);else if(Ĵ==(Ǐ*-1)) ώ.SetValueFloat("Roll",ч*-1);
}}void ΓΞ(){this.ΓΑ=false;}void Ф(Vector3 ų,Vector3 ǩ,Vector3 Βό,float Ȍ,bool Ř){Βά(ų,Ȍ,Ř);ƿ=Ȍ;Αϊ=false;this.Αγ=ǩ;this.Γί=Βό;}void Ф(Vector3 ų,Vector3 ǩ,Vector3 Βό,bool Ř){Ф(ų,ǩ,Βό,2f,Ř);}void Βά(Vector3 ų,float Ȍ,bool Ř){ƿ=Ȍ;this.ΓΑ=true;this.ΔА=Ř;Αϊ=true;ƙ=false;
this.ΑΝ=ų;}void ΑΫ(){Ǟ(false,false,false,ϊ,0);Ƽ=false;}void н(Vector3 Й,float ǔ){Ǟ(true,false,false,Й,ǔ);}void Ǟ(bool Ё,bool ΒΛ,bool Αέ,Vector3 Й,float ǔ){Ǟ(Ё,ΒΛ,Αέ,Й,Й-θ,0.0f,ǔ);}void Ǟ(bool Ё,bool ΒΛ,bool Αέ,Vector3 Й,Vector3 Εό,float ΕΗ,float ǔ){Ƽ=true;this.ΓЁ=Ё;
ϊ=Й;this.Βτ=ǔ;this.Βλ=ΕΗ;this.Γύ=ΒΛ;this.Γκ=Αέ;this.ΓΛ=Εό;Ж=Vector3.Distance(Й,θ);}void ΕΕ(){ω.GetBlocksOfType(ś,ф);}void ΕΜ(){if(ǀ){ύ=2;return;}List<IMyRemoteControl>ū=new List<IMyRemoteControl>();List<IMySensorBlock>ΔΜ=new List<IMySensorBlock>();List<IMyTerminalBlock>ż=new List<IMyTerminalBlock>();
ω.GetBlocksOfType(ū,ф);ω.GetBlocksOfType(Г,ф);ω.GetBlocksOfType(ΔΜ,ф);ω.SearchBlocksOfName(pamTag.Substring(0,pamTag.Length-1)+":",ż,
q=>q.CubeGrid==Me.CubeGrid&&q is IMyTextSurfaceProvider);Г=ё(Г,pamTag,true);Δύ();Δδ(ż);ȱ(Г,setLCDFontAndSize,1.4f,false);ȱ(ǡ,setLCDFontAndSize,1.4f,true);List<IMySensorBlock>Δϊ=ё(ΔΜ,pamTag,true);if(Δϊ.Count>0) μ=Δϊ[0];else μ=null;if(Μ==Κ.Ŗ){ω.GetBlocksOfType(ξ,q=>q.CubeGrid==Me.CubeGrid&&q is IMyShipDrill);
if(ξ.Count==0){ύ=1;Ρ="Drills are missing";}}else if(Μ==Κ.ў){ω.GetBlocksOfType(ξ,q=>q.CubeGrid==Me.CubeGrid&&q is IMyShipGrinder);if(ξ.Count==0){ύ=1;Ρ="Grinders are missing";}if(μ==null){ύ=1;Ρ="Sensor is missing";}}else if(Μ==Κ.ΰ){ω.GetBlocksOfType(ΑΩ,q=>q.CubeGrid==Me.CubeGrid);
}List<IMyRemoteControl>Δο=ё(ū,pamTag,true);if(Δο.Count>0) ū=Δο;if(ū.Count>0) Υ=ū[0];else{Υ=null;ύ=2;Ρ="Remote is missing";return;}σ=(float) Υ.CubeGrid.WorldVolume.Radius*2;х=null;if(Μ!=Κ.ΰ){ΓЃ();if(ξ.Count>0&&х!=null){if(μ!=null&&(х.WorldMatrix.Forward!=μ.WorldMatrix.Forward||
!(Υ.WorldMatrix.Forward==μ.WorldMatrix.Up||Υ.WorldMatrix.Down==μ.WorldMatrix.Down))){ύ=1;Ρ="Wrong sensor direction";}if(х.WorldMatrix.Forward!=Υ.WorldMatrix.Forward&&
х.WorldMatrix.Forward!=Υ.WorldMatrix.Down){ύ=2;Ρ="Wrong remote direction";}}}}void Ζω(){ω.GetBlocksOfType(Ǹ,ф);ω.GetBlocksOfType(ж,ф);ω.GetBlocksOfType(Ǫ,ф);ω.GetBlocksOfType(ƣ,ф);ω.GetBlocksOfType(ȥ,ф);ω.GetBlocksOfType(ȗ,ф);ω.GetBlocksOfType(я,
q=>q.CubeGrid==Me.CubeGrid&&q.BlockDefinition.ToString().ToUpper().Contains("HYDROGEN"));ω.GetBlocksOfType(ƃ,ф);if(Me.CubeGrid.GridSizeEnum==MyCubeSize.Small)
ж=ё(ж,"ConnectorMedium",false);else
ж=ё(ж,"Connector",false);List<IMyShipConnector>ΓΡ=ё(ж,pamTag,true);if(ΓΡ.Count>0) ж=ΓΡ;if(ύ<=1){if(ж.Count==0){ύ=1;Ρ="Connector is missing";}if(ƣ.Count==0){ύ=1;Ρ="Gyros are missing";}if(Ǫ.Count==0){ύ=1;Ρ="Thrusters are missing";}}List<IMyConveyorSorter>ΓΟ=ё(ƃ,pamTag,true);
if(ΓΟ.Count>0) ƃ=ΓΟ;List<IMyLandingGear>Δί=ё(Ǹ,pamTag,true);if(Δί.Count>0) Ǹ=Δί;for(int i=0;i<Ǹ.Count;i++) Ǹ[i].AutoLock=false;List<IMyBatteryBlock>ΓΘ=ё(ȥ,pamTag,true);if(ΓΘ.Count>0) ȥ=ΓΘ;List<IMyGasTank>Γσ=ё(я,pamTag,true);if(Γσ.Count>0) я=Γσ;}void Ζτ(){ω.GetBlocksOfType(Ā,q=>q.CubeGrid==Me.CubeGrid&&q.InventoryCount>0);
Į.Clear();for(int i=Ā.Count-1;i>=0;i--){if(ΖΥ(Ā[i])){Į.Add(Ā[i]);Ā.RemoveAt(i);}}}bool ΖΥ(IMyTerminalBlock Σ){if(Σ is IMyCargoContainer) return true;if(Σ is IMyShipDrill) return true;if(Σ is IMyShipGrinder) return true;if(Σ is IMyShipConnector){if(((IMyShipConnector) Σ).ThrowOut) return false;
if(Me.CubeGrid.GridSizeEnum!=MyCubeSize.Large&&ΒЌ(Σ,"ConnectorSmall",false))
return false;else return true;}return false;}void ΓЃ(){if(Υ==null) return;х=null;float Ʋ=0,ư=0,Ƹ=0,Ɖ=0,Ƌ=0,ƾ=0;List<IMyTerminalBlock>ΑБ=ё(ξ,pamTag,true);bool Εώ=ΑБ.Count==0;if(ΑБ.Count>0) х=ΑБ[0];else if(ξ.Count>0) х=ξ[0];int ǰ=0;for(int i=0;i<ξ.Count;i++)
{if(ξ[i].WorldMatrix.Forward!=х.WorldMatrix.Forward){if(Εώ){ύ=2;Ρ="Mining direction is unclear!";return;}continue;}ǰ++;Vector3 Ђ=ΑЋ(Υ,ξ[i].GetPosition());if(i==0){Ʋ=Ђ.X;ư=Ђ.X;Ƹ=Ђ.Y;Ɖ=Ђ.Y;Ƌ=Ђ.Z;ƾ=Ђ.Z;}ư=Math.Max(Ђ.X,ư);Ʋ=Math.Min(Ђ.X,Ʋ);Ɖ=Math.Max(Ђ.Y,Ɖ);Ƹ=Math.Min(Ђ.Y,Ƹ);
ƾ=Math.Max(Ђ.Z,ƾ);Ƌ=Math.Min(Ђ.Z,Ƌ);}ȇ=(ư-Ʋ)*(1-ť)+drillRadius*2;ǯ=(Ɖ-Ƹ)*(1-İ)+drillRadius*2;if(х!=null&&х.WorldMatrix.Forward==Υ.WorldMatrix.Down)
ǯ=(ƾ-Ƌ)*(1-İ)+drillRadius*2;}List<T>ё<T>(List<T>а,String љ,bool Ơ){List<T>Ω=new List<T>();for(int i=0;i<а.Count;i++)
if(ΒЌ(а[i],љ,Ơ)) Ω.Add(а[i]);return Ω;}bool ΒЌ<T>(T Σ,String љ,bool Ơ){IMyTerminalBlock b=(IMyTerminalBlock) Σ;if(Ơ&&b.CustomName.ToUpper().Contains(љ.ToUpper())) return true;if(!Ơ&&b.BlockDefinition.ToString().ToUpper().Contains(љ.ToUpper())) return true;return false;}void с<T>(List<T>а,bool Ё)
{for(int i=0;i<а.Count;i++)
ΓЇ((IMyTerminalBlock) а[i],Ё);}void ΓЇ(IMyTerminalBlock Σ,bool Ё){if(Σ==null) return;String ΕЅ=Ё?"OnOff_On":"OnOff_Off";var a=Σ.GetActionWithName(ΕЅ);a.Apply(Σ);}void Ǡ(bool Ё){ΒΧ=Ё;if(!Đ) return;с(ƃ,Ё);}void Αζ(ChargeMode С){for(int i=0;i<ȥ.Count;i++) ȥ[i].ChargeMode=С;}void ΑΠ(bool ΗΞ)
{for(int i=0;i<я.Count;i++) я[i].Stockpile=ΗΞ;}void ŏ(List<IMyLandingGear>Αμ,bool Γϊ){for(int i=0;i<Αμ.Count;i++){if(Γϊ) Αμ[i].Lock();if(!Γϊ) Αμ[i].Unlock();}}void Δτ(bool Ё){if(Δΰ==Ё) return;List<IMyShipController>Ʀ=new List<IMyShipController>();ω.GetBlocksOfType(Ʀ,ф);if(Ʀ.Count==0) return;
for(int i=0;i<Ʀ.Count;i++)
Ʀ[i].DampenersOverride=Ё;Δΰ=Ё;}IMyShipConnector Э(MyShipConnectorStatus к){for(int i=0;i<ж.Count;i++){if(!ǲ(ж[i],true)) continue;if(ж[i].Status==к) return ж[i];}return null;}void Ĕ(bool ΑϏ,bool ΑΚ,float ΗΕ,float ΖЊ){if(μ==null||ξ.Count==0) return;Vector3 ǋ=new Vector3();int ǰ=0;
for(int i=0;i<ξ.Count;i++){if(ξ[i].WorldMatrix.Forward!=х.WorldMatrix.Forward) continue;ǰ++;ǋ+=ξ[i].GetPosition();}ǋ=ǋ/ǰ;Vector3 Ĳ=ΑЋ(μ,ǋ);μ.Enabled=true;μ.ShowOnHUD=ΑϏ;μ.LeftExtend=(ΑΚ?1:ѐ)/2f*ȇ-Ĳ.X;μ.RightExtend=(ΑΚ?1:ѐ)/2f*ȇ+Ĳ.X;μ.TopExtend=(ΑΚ?1:э)/2f*ǯ+Ĳ.Y;
μ.BottomExtend=(ΑΚ?1:э)/2f*ǯ-Ĳ.Y;μ.FrontExtend=(ΑϏ?Ы:ΗΕ)-Ĳ.Z;μ.BackExtend=ΑϏ?0:ΖЊ+σ*0.75f+Ĳ.Z;μ.DetectFloatingObjects=true;μ.DetectAsteroids=false;μ.DetectLargeShips=true;μ.DetectSmallShips=true;μ.DetectStations=true;μ.DetectOwner=true;μ.DetectSubgrids=false;
μ.DetectPlayers=false;μ.DetectEnemy=true;μ.DetectFriendly=true;μ.DetectNeutral=true;}void ȱ<T>(List<T>а,bool Ζφ,float ΖΕ,bool Εο){for(int i=0;i<а.Count;i++){IMyTextSurface Ŝ=null;if(а[i]is IMyTextSurface) Ŝ=(IMyTextSurface) а[i];if(Ŝ!=null){Ŝ.ContentType=ContentType.TEXT_AND_IMAGE;
if(!Ζφ) continue;Ŝ.Font="Debug";if(Εο) continue;Ŝ.FontSize=ΖΕ;}}}bool Ƒ(){Vector3D Њ;return this.Υ.TryGetPlanetPosition(out Њ);}int Ζχ(Vector3 ΖΞ,int ΓЊ){if(ΓЊ==-1) return 0;double А=-1;int ȋ=-1;for(int i=Φ.Count-1;i>=0;i--){double Ѓ=Vector3.Distance(Φ[i].Δ,ΖΞ);if(А==-1||Ѓ<А){ȋ=i;А=Ѓ;}
}return Math.Sign(ȋ-ΓЊ);}bool ΗΒ(Vector3 Њ){List<Vector3>Џ=new List<Vector3>();for(int i=0;i<Φ.Count;i++) Џ.Add(Φ[i].Δ);if(Θ.α&&Φ.Count>=1){Vector3 ĝ=new Vector3();ǹ(Θ,dockDist*σ,false,out ĝ);if(Vector3.Distance(Θ.Δ,Φ.First().Δ)<Vector3.Distance(Θ.Δ,Φ.Last().Δ)){Џ.Insert(0,ĝ);Џ.Insert(0,Θ.Δ);}
else{Џ.Add(ĝ);Џ.Add(Θ.Δ);}}if(Μ==Κ.ΰ){if(Ε.α&&Φ.Count>=1){Vector3 ΑЏ=new Vector3();ǹ(Ε,dockDist*σ,false,out ΑЏ);if(Vector3.Distance(Ε.Δ,Φ.First().Δ)<Vector3.Distance(Ε.Δ,Φ.Last().Δ)){Џ.Insert(0,ΑЏ);Џ.Insert(0,Ε.Δ);}else{Џ.Add(ΑЏ);Џ.Add(Ε.Δ);}}}else{if(γ!=Ξ.л)
if(Φ.Count>0&&Vector3.Distance(Ε.Δ,Φ.First().Δ)<Vector3.Distance(Ε.Δ,Φ.Last().Δ))
Џ.Insert(0,Ε.Δ);else Џ.Add(Ε.Δ);}int ȋ=-1;double ǝ=-1;for(int i=0;i<Џ.Count;i++){double Ѓ=Vector3.Distance(Џ[i],Њ);if(Ѓ<ǝ||ǝ==-1){ǝ=Ѓ;ȋ=i;}}if(Џ.Count==0) return false;double ΓА=Vector3.Distance(Џ[ȋ],Њ);double ΖЋ=Vector3.Distance(Џ[Math.Max(0,ȋ-1)],Џ[ȋ])*1.5f;
double ΖΒ=Vector3.Distance(Џ[Math.Min(Џ.Count-1,ȋ+1)],Џ[ȋ])*1.5f;return ΓА<ΖЋ||ΓА<ΖΒ;}static float Ѕ(float a,float b){if(b==0) return 0;return a/b;}Vector3 Ες(Vector3 v,int Ββ){return new Vector3(Math.Round(v.X,Ββ),Math.Round(v.Y,Ββ),Math.Round(v.Z,Ββ));}float Ĥ(Vector3 a,Vector3 b)
{if(a==b) return 0;float Ζγ=(a*b).Sum;float ΔΟ=a.Length();float Δϋ=b.Length();if(ΔΟ==0||Δϋ==0) return 0;float Ω=(float)((180.0f/Math.PI)*Math.Acos(Ζγ/(ΔΟ*Δϋ)));if(float.IsNaN(Ω)) return 0;return Ω;}float Ą(Vector3 v,Vector3 Ƭ,float ΕΛ){float Ğ=Ĥ(v,Ƭ);if(ΕΛ>0f) Ğ*=-1;
if(Ğ>-90f) return Ğ-90f;else return 180f-(-Ğ-90f);}double ΔΨ(float ΕЂ){return(Math.PI/180)*ΕЂ;}bool Βύ(double ΗΗ,double value,double Αί){return(value>=ΗΗ&&value<=Αί);}Vector3 Ζό(IMyTerminalBlock Σ,Vector3 Ђ){return Vector3D.Transform(Ђ,Σ.WorldMatrix);}Vector3 ΑЋ(IMyTerminalBlock Σ,Vector3 Ζα)
{return У(Σ,Ζα-Σ.GetPosition());}Vector3 У(IMyTerminalBlock Σ,Vector3 ΓΓ){return Vector3D.TransformNormal(ΓΓ,MatrixD.Transpose(Σ.WorldMatrix));}Vector3 Ē(Vector3 ǣ,Vector3 Ǐ,Vector3 ΓΓ){MatrixD ΒЊ=MatrixD.CreateFromDir(ǣ,Ǐ);return Vector3D.TransformNormal(ΓΓ,MatrixD.Transpose(ΒЊ));}Vector3 ΑЉ(Vector3 ǣ,Vector3 Ǐ,Vector3 Ђ)
{MatrixD ΒЊ=MatrixD.CreateFromDir(ǣ,Ǐ);return Vector3D.Transform(Ђ,ΒЊ);}String Ѝ(Vector3 v){return ""+v.X+"|"+v.Y+"|"+v.Z;}Vector3 Д(String s){String[]ι=s.Split('|');return new Vector3(float.Parse(Ι(ι,0)),float.Parse(Ι(ι,1)),float.Parse(Ι(ι,2)));}String Εγ(Ϊ Χ){String Љ=":";
String Ω=Ѝ(Χ.Δ)+Љ+Ѝ(Χ.ί)+Љ+
Ѝ(Χ.β)+Љ+Ѝ(Χ.τ)+Љ+Ѝ(Χ.ς);for(int i=0;i<Χ.ǒ.Length;i++)
Ω+=Љ+Math.Round(Χ.ǒ[i],3);return Ω;}Ϊ ΖΛ(String s){String[]ι=s.Split(':');Ϊ Χ=new Ϊ(
Д(Ι(ι,0)),Д(Ι(ι,1)),
Д(Ι(ι,2)),Д(Ι(ι,3)),
Д(Ι(ι,4)));int Α=5;List<float>Γβ=new List<float>();while(Α<ι.Length){String ƻ=Ι(ι,Α);float f=0;if(!float.TryParse(ƻ,out f)) break;Γβ.Add(f);Α++;}Χ.ǒ=Γβ.ToArray();return Χ;}void Π<T>(T value,bool ΖΙ){if(ΖΙ) Storage+="\n";Storage+=value;}void Π<T>(T value){Π(value,true);}
String Ι(String[]Εύ,int Α){String ƻ=Εύ.ElementAtOrDefault(Α);if(String.IsNullOrEmpty(ƻ)) return "";return ƻ;}void Save(){if(ǀ||Μ==Κ.п){Storage="";return;}Storage=DATAREV+";";Π(Ѝ(Ɩ),false);Π(Ѝ(Θ.ί));Π(Ѝ(Θ.τ));Π(Ѝ(Θ.β));Π(Ѝ(Θ.ς));Π(Ѝ(Θ.Δ));Π(Ѝ(Θ.о));Π(Θ.α);Π(Ѝ(Ε.Δ));Π(Ѝ(Ε.ς));Π(Ѝ(Ε.ί));
Π(Ѝ(Ε.β));Π(Ѝ(Ε.τ));Π(Ѝ(Ε.о));Π(Ε.α);Π(Ѝ(ǭ));Π(Ѝ(ċ));Π(";");Π((int) Μ,false);Π((int) γ);Π((int) ы);Π(Ǥ);Π(з);Π(Р);Π(г);Π(ǚ);Π(Ȁ);Π(ȃ);if(Μ==Κ.ΰ){Π((int) υ.Ї);Π(υ.і);Π(υ.Ȫ);Π(υ.ǎ);Π(υ.ћ);Π((int) φ.Ї);Π(φ.і);Π(φ.Ȫ);Π(φ.ǎ);Π(φ.ћ);}else{Π((int) Ȃ);Π((int) Я);Π((int) И);Π((int) ќ);Π((int) ǃ);Π(ȡ);
Π(Đ);Π(ı);Π(ĭ);Π(ѐ);Π(э);Π(Ы);Π(ĥ);Π(ļ);Π(ť);Π(İ);Π(Т);Π(й);Π(ρ);Π(π);Π(Ȩ);Π(б);Π(Ċ);Π(ĩ);}Π(";");for(int i=0;i<Ǧ.Count;i++)
Π((i>0?"|":"")+Ǧ[i],false);Π(";");for(int i=0;i<Φ.Count;i++)
Π(Εγ(Φ[i]),i>0);}ȍ ΖΑ(){if(Storage=="") return ȍ.Εε;String[]Ś=Storage.Split(';');if(Ι(Ś,0)!=DATAREV) return ȍ.ΔΓ;int Α=0;try{String[]Ζ=Ι(Ś,1).Split('\n');Ɩ=Д(Ι(Ζ,Α++));Θ.ί=Д(Ι(Ζ,Α++));Θ.τ=Д(Ι(Ζ,Α++));Θ.β=Д(Ι(Ζ,Α++));Θ.ς=Д(Ι(Ζ,Α++));Θ.Δ=Д(Ι(Ζ,Α++));Θ.о=Д(Ι(Ζ,Α++));
Θ.α=bool.Parse(Ι(Ζ,Α++));Ε.Δ=Д(Ι(Ζ,Α++));Ε.ς=Д(Ι(Ζ,Α++));Ε.ί=Д(Ι(Ζ,Α++));Ε.β=Д(Ι(Ζ,Α++));Ε.τ=Д(Ι(Ζ,Α++));Ε.о=Д(Ι(Ζ,Α++));Ε.α=bool.Parse(Ι(Ζ,Α++));ǭ=Д(Ι(Ζ,Α++));ċ=Д(Ι(Ζ,Α++));Ζ=Ι(Ś,2).Split('\n');Α=0;Μ=(Κ) int.Parse(Ι(Ζ,Α++));γ=(Ξ) int.Parse(Ι(Ζ,Α++));ы=(Ξ) int.Parse(Ι(Ζ,Α++));
Ǥ=int.Parse(Ι(Ζ,Α++));з=int.Parse(Ι(Ζ,Α++));Р=int.Parse(Ι(Ζ,Α++));г=int.Parse(Ι(Ζ,Α++));ǚ=float.Parse(Ι(Ζ,Α++));Ȁ=bool.Parse(Ι(Ζ,Α++));ȃ=bool.Parse(Ι(Ζ,Α++));if(Μ==Κ.ΰ){υ.Ї=(δ) int.Parse(Ι(Ζ,Α++));υ.і=float.Parse(Ι(Ζ,Α++));υ.Ȫ=float.Parse(Ι(Ζ,Α++));υ.ǎ=Ι(Ζ,Α++);υ.ћ=Ι(Ζ,Α++);
φ.Ї=(δ) int.Parse(Ι(Ζ,Α++));φ.і=float.Parse(Ι(Ζ,Α++));φ.Ȫ=float.Parse(Ι(Ζ,Α++));φ.ǎ=Ι(Ζ,Α++);φ.ћ=Ι(Ζ,Α++);}else{Ȃ=(Ǜ) int.Parse(Ι(Ζ,Α++));Я=(Ч) int.Parse(Ι(Ζ,Α++));И=(ϋ) int.Parse(Ι(Ζ,Α++));ќ=(њ) int.Parse(Ι(Ζ,Α++));ǃ=(Ǜ) int.Parse(Ι(Ζ,Α++));ȡ=bool.Parse(Ι(Ζ,Α++));Đ=bool.Parse(Ι(Ζ,Α++));
ı=bool.Parse(Ι(Ζ,Α++));ĭ=bool.Parse(Ι(Ζ,Α++));ѐ=int.Parse(Ι(Ζ,Α++));э=int.Parse(Ι(Ζ,Α++));Ы=int.Parse(Ι(Ζ,Α++));ĥ=float.Parse(Ι(Ζ,Α++));ļ=float.Parse(Ι(Ζ,Α++));ť=float.Parse(Ι(Ζ,Α++));İ=float.Parse(Ι(Ζ,Α++));Т=int.Parse(Ι(Ζ,Α++));й=int.Parse(Ι(Ζ,Α++));ρ=int.Parse(Ι(Ζ,Α++));
π=int.Parse(Ι(Ζ,Α++));Ȩ=int.Parse(Ι(Ζ,Α++));б=int.Parse(Ι(Ζ,Α++));Ċ=int.Parse(Ι(Ζ,Α++));ĩ=float.Parse(Ι(Ζ,Α++));}Ζ=Ι(Ś,3).Replace("\n","").Split('|');Ǧ=Ζ.ToList();Ζ=Ι(Ś,4).Split('\n');Φ.Clear();if(Ζ.Count()>=1&&Ζ[0]!="")
for(int i=0;i<Ζ.Length;i++)
Φ.Add(ΖΛ(Ι(Ζ,i)));}catch{return ȍ.ΔΥ;}Ļ=ы;χ();return ȍ.Γθ;}void Δύ(){ė.Clear();for(int i=Г.Count-1;i>=0;i--){String ζ=Г[i].CustomData.ToUpper();bool ΑΪ=false;if(ζ=="INSTRUCTIONS"){ΑΪ=true;Ǌ=true;}if(ζ=="DEBUG") ΑΪ=true;if(ΑΪ){ė.Add(Г[i]);Г.RemoveAt(i);}}ȱ(ė,false,1,false);
}void Δδ(List<IMyTerminalBlock>ΓЋ){ǡ.Clear();for(int i=0;i<ΓЋ.Count;i++){IMyTerminalBlock Σ=ΓЋ[i];try{String Γϋ=pamTag.Substring(0,pamTag.Length-1)+":";int Α=Σ.CustomName.IndexOf(Γϋ);int Ĭ=-1;if(Α<0||!int.TryParse(Σ.CustomName.Substring(Α+Γϋ.Length,1),out Ĭ)) continue;if(Ĭ==-1) continue;
Ĭ--;IMyTextSurfaceProvider ΔЈ=(IMyTextSurfaceProvider) Σ;if(Ĭ<ΔЈ.SurfaceCount&&Ĭ>=0)
ǡ.Add(ΔЈ.GetSurface(Ĭ));}catch{}}}String ƅ="";void ΔΧ(){String Αι="";String Ŕ="";ƅ=ΓЅ(false);Αι+=ƅ;Ŕ+=ƅ;Ŕ+=ΖΩ();for(int i=0;i<Г.Count;i++) Г[i].WriteText(Αι);for(int i=0;i<ǡ.Count;i++) ǡ[i].WriteText(Αι);Echo(Ŕ);for(int i=0;i<ė.Count;i++){IMyTextPanel ȏ=ė[i];String ζ=ȏ.CustomData.ToUpper();
if(ζ=="DEBUG") ȏ.WriteText(""+"\n"+"");if(ζ=="INSTRUCTIONS") ȏ.WriteText(Δζ());}}string Δζ(){String Γ="";try{float ΔЅ=Runtime.MaxInstructionCount;Γ+="Inst: "+Runtime.CurrentInstructionCount+" Time: "+Math.Round(Runtime.LastRunTimeMs,3)+"\n";Γ+="Inst. avg/max: "+(int)(Ň*ΔЅ)+" / "+(int)(ĵ*ΔЅ)+"\n";
Γ+="Inst. avg/max: "+Math.Round(Ň*100f,1)+"% / "+Math.Round(ĵ*100f,1)+"% \n";Γ+="Time avg/max: "+Math.Round(Ŵ,2)+"ms / "+Math.Round(ΒЄ,2)+"ms \n";}catch{}for(int i=0;i<Ȉ.Count;i++)
Γ+=""+Ȉ.Keys.ElementAt(i)+" = "+Math.Round(Ȉ.Values.ElementAt(i)[0],2)+" / "+
Math.Round(Ȉ.Values.ElementAt(i)[1],2)+"%\n";return Γ;}void Εη(){String Γ="Error occurred! \nPlease copy this and paste it \nin the \"Bugs and issues\" discussion.\n"+
"Version: "+VERSION+"\n";ȱ(Г,setLCDFontAndSize,0.9f,false);ȱ(ǡ,setLCDFontAndSize,0.9f,true);for(int i=0;i<Г.Count;i++) Г[i].WriteText(Γ+Ȥ.ToString());for(int i=0;i<ǡ.Count;i++) ǡ[i].WriteText(Γ+Ȥ.ToString());}void Ǭ(){if(!Ǌ) return;try{Αω=Runtime.CurrentInstructionCount;}catch{}
}void Ǳ(String έ){if(!Ǌ) return;if(Αω==0) return;try{float ƴ=(Runtime.CurrentInstructionCount-Αω)/Runtime.MaxInstructionCount*100;if(!Ȉ.ContainsKey(έ))
Ȉ.Add(έ,new float[]{ƴ,ƴ});else{Ȉ[έ][0]=ƴ;Ȉ[έ][1]=Math.Max(ƴ,Ȉ[έ][1]);}}catch{}}const String BROADCAST_TAG="[PAMCMD]";const String BROADCAST_SELF_ID="#";const Char BROADCAST_SEP=';';void ΕΥ(String Ǣ){if(!ņ) return;String Љ=""+BROADCAST_SEP;String κ=VERSION+Љ;κ+=Ľ+Љ;κ+=(int) Μ+Љ;
κ+=Ŋ(θ.X)+""+Љ;κ+=Ŋ(θ.Y)+Љ;κ+=Ŋ(θ.Z)+Љ;if(Μ!=Κ.ΰ)
κ+=ΒЀ(ы)+(ы==Ξ.Ћ?" "+Math.Round(Ũ,1)+"%":"")+Љ;else κ+=ΒЀ(ы)+Љ;κ+=Ρ+Љ;κ+=І+""+Љ;κ+=ƅ+Љ;κ+=ȟ+Љ;κ+=ȣ+Љ;for(int i=0;i<Ǔ.Count;i++){if(Ǔ[i].Ł!=В.Ģ) continue;κ+=Ǔ[i].έ+"/"+Ǔ[i].ν+"/"+Ǔ[i].Ϗ+Љ;}Εψ(κ,Ǣ);}void Εψ(String κ,String Ǣ){ΑΞ(κ,BROADCAST_SELF_ID,Ǣ);}
void ΑΞ(String κ,String Й,String Ǣ){try{if(!ņ) return;κ=BROADCAST_TAG+BROADCAST_SEP+Γπ()+BROADCAST_SEP+Й+BROADCAST_SEP+Ασ+BROADCAST_SEP+Ǣ+BROADCAST_SEP+κ;this.IGC.SendBroadcastMessage(BROADCAST_TAG,κ);}catch(Exception e){Ȥ=e;}}String Γπ(){if(Μ!=Κ.п) return ""+Me.GetId();
return BROADCAST_SELF_ID;}bool ΒΦ(String κ){return κ.StartsWith(BROADCAST_TAG);}bool К(ref String ζ,out string ŗ,Char Љ){int Α=ζ.IndexOf(Љ);ŗ="";if(Α<0) return false;ŗ=ζ.Substring(0,Α);ζ=ζ.Remove(0,Α+1);return true;}bool ΔЉ(ref String κ,out String ǟ,out String Ǣ){ǟ="";Ǣ="";if(!ņ) return false;
String љ="";if(!К(ref κ,out љ,BROADCAST_SEP)||!ΒΦ(љ)) return false;if(!К(ref κ,out ǟ,BROADCAST_SEP)) return false;if(!К(ref κ,out љ,BROADCAST_SEP)||(љ!=Γπ()&&(љ!="*"&&Μ!=Κ.п))) return false;if(!К(ref κ,out љ,BROADCAST_SEP)||(љ!=Ασ)) return false;if(!К(ref κ,out Ǣ,BROADCAST_SEP)) return false;
return true;}void ΓΫ(){bool š=true;if(Δπ){Δπ=false;if(Me.CustomData.Contains("Antenna_Name")){Ρ="Update custom data";Me.CustomData="";}}String Œ=(Μ!=Κ.п?"[PAM-Ship]":"[PAM-Controller]")+" Broadcast-settings";try{if(Me.CustomData.Length==0||Me.CustomData.Split('\n')[0]!=Œ)
ΔЍ(Œ);String[]Ζ=Me.CustomData.Split('\n');ņ=bool.Parse(ƶ(ǉ(Ζ,"Enable_Broadcast",ref š)));bool Βγ=false;bool ΓЀ=true;if(ņ){if(Μ!=Κ.п)
Ľ=ƶ(ǉ(Ζ,"Ship_Name",ref š)).Replace(BROADCAST_SELF_ID,"");Ασ=ƶ(ǉ(Ζ,"Broadcast_Channel",ref š)).ToLower();ΓЀ=false;if(Ǎ==null){Ǎ=this.IGC.RegisterBroadcastListener(BROADCAST_TAG);Ǎ.SetMessageCallback("");}List<IMyRadioAntenna>ň=new List<IMyRadioAntenna>();ω.GetBlocksOfType(ň);bool ΒЃ=false;
for(int i=0;i<ň.Count;i++)
if(ň[i].EnableBroadcasting&&ň[i].Enabled){ΒЃ=true;break;}if(ň.Count==0) Ρ="No Antenna found";else if(!ΒЃ) Ρ="Antenna not ready";Βγ=ň.Count==0||!ΒЃ;if(ΓΥ&&!Βγ&&Μ!=Κ.п) Ρ="Antenna ok";}else if(Μ==Κ.п)
Ρ="Offline - Enable in PB custom data";ΓΥ=Βγ;if(ΓЀ){if(Ǎ!=null) this.IGC.DisableBroadcastListener(Ǎ);Ǎ=null;}}catch{š=false;}if(!š){Ρ="Reset custom data";ΔЍ(Œ);}}void ΔЍ(String Œ){String ζ=Œ+"\n\n"+"Enable_Broadcast="+(Μ==Κ.п?"true":"false")+" \n";ζ+=Μ!=Κ.п?"Ship_Name=Your_ship_name_here\n":"";
Me.CustomData=ζ+"Broadcast_Channel=#default";}String ƶ(String Ė){int Α=Ė.IndexOf("//");if(Α!=-1) Ė=Ė.Substring(0,Α);String[]ι=Ė.Split('=');if(ι.Length<=1) return "";return ι[1].Trim();}String ǉ(String[]Ζ,String ΖБ,ref bool ā){foreach(String Ė in Ζ)
if(Ė.StartsWith(ΖБ)) return Ė;ā=false;return "";}void ΕΡ(string З){if(ț) ǐ=new List<ѕ>();String ǟ="";String Ǣ="";if(!ΒΦ(З)) ΕΠ(З);if(Ǎ!=null&&Ǎ.HasPendingMessage){MyIGCMessage κ=Ǎ.AcceptMessage();String ζ=(string) κ.Data;if(ΔЉ(ref ζ,out ǟ,out Ǣ)&&ǟ!=""&&ǟ!=BROADCAST_SELF_ID)
{ѕ ή=ΔЂ(ǟ,"");if(ή==null){ή=new ѕ(ǟ);ǐ.Add(ή);}ή.Αα(Ǣ,false,false,true);ΕΤ(ή,ζ);ǐ.Sort(delegate(ѕ a,ѕ b){if(a.έ==null&&b.έ==null) return 0;else if(a.έ==null) return-1;else if(b.έ==null) return 1;else return a.έ.CompareTo(b.έ);});}}if(Ȇ||ț){if(Ō<=0||ț){Ρ="";ț=false;
ΕЁ();ΓΫ();Αδ=DateTime.Now;}}ΖΫ();}void ΕΤ(ѕ ή,String ζ){ή.Δφ=DateTime.Now;String ŗ="";К(ref ζ,out ή.Δσ,BROADCAST_SEP);К(ref ζ,out ή.έ,BROADCAST_SEP);if(ή.Δσ!=VERSION) return;String Ţ="";String[]Ī=new string[3];К(ref ζ,out Ţ,BROADCAST_SEP);К(ref ζ,out Ī[0],BROADCAST_SEP);К(ref ζ,out Ī[1],BROADCAST_SEP);
К(ref ζ,out Ī[2],BROADCAST_SEP);К(ref ζ,out ή.Ζν,BROADCAST_SEP);К(ref ζ,out ή.Ρ,BROADCAST_SEP);К(ref ζ,out ŗ,BROADCAST_SEP);К(ref ζ,out ή.ΕЌ,BROADCAST_SEP);String ΓΧ="",ΔΫ="";К(ref ζ,out ΓΧ,BROADCAST_SEP);К(ref ζ,out ΔΫ,BROADCAST_SEP);ή.Ќ.Clear();while(true){String ΔΩ;if(!К(ref ζ,out ΔΩ,BROADCAST_SEP)) break;
String[]Ɣ=ΔΩ.Split('/');if(Ɣ.Count()<3) continue;int Ϗ=0;if(!int.TryParse(Ɣ[2],out Ϗ)) continue;ή.Ќ.Add(new м(Ɣ[0],Ɣ[1],Ϗ,В.Ģ));}int ΔΗ=0;if(!int.TryParse(ŗ,out ή.І)) ή.І=0;if(!int.TryParse(Ţ,out ΔΗ)) ή.Μ=Κ.Ȭ;if(!float.TryParse(Ī[0],out ή.Δ.X)) ή.Δ.X=0;if(!float.TryParse(Ī[1],out ή.Δ.Y)) ή.Δ.Y=0;
if(!float.TryParse(Ī[2],out ή.Δ.Z)) ή.Δ.Z=0;if(!float.TryParse(ΓΧ,out ή.ȟ)) ή.ȟ=0;if(!float.TryParse(ΔΫ,out ή.ȣ)) ή.ȣ=0;ή.Μ=(Κ) ΔΗ;ή.ΕΝ=(int) Math.Round(Vector3.Distance(Me.GetPosition(),ή.Δ));ή.Γο=0;for(int i=0;i<ή.Ќ.Count();i++) ή.Γο+=ή.Ќ[i].Ϗ;}ѕ ΔЂ(String Ǻ,String έ){Ǻ=Ǻ.ToUpper();έ=έ.ToUpper();
for(int i=0;i<ǐ.Count;i++){if(Ǻ!=""&&ǐ[i].Ǻ.ToUpper()==Ǻ) return ǐ[i];if(έ!=""&&ǐ[i].έ.ToUpper()==έ) return ǐ[i];}return null;}void ķ(ѕ ή,String О){if(ή==null){for(int i=0;i<ǐ.Count;i++)
ǐ[i].Αα(О,true,false,false);ΑΞ(О,"*",О);}else{ή.Αα(О,true,false,false);ΑΞ(О,ή.Ǻ,О);}}void ΕΠ(string З){if(З=="") return;var ι=З.ToUpper().Split(' ');ι.DefaultIfEmpty("");var О=ι.ElementAtOrDefault(0);var Ȧ=ι.ElementAtOrDefault(1);String Ǯ="Invalid argument: "+З;if(Ј==Τ.ΓЈ){if(ć!=null)
{switch(О){case "UP":{if(І<2) break;if(ć.І==0){І=1;return;}ķ(ć,"UP");return;}case "DOWN":{if(І<1) break;if(І==1){ķ(ć,"MRES");break;}ķ(ć,"DOWN");break;}case "APPLY":{if(І<2) break;ķ(ć,"APPLY");return;}}}}switch(О){case "UP":this.Βϋ(false);return;case "DOWN":this.ΒΡ(false);return;
case "APPLY":this.Ƨ(true);return;}switch(О){case "CLEAR":Ζζ();return;case "SENDALL":ķ(null,Ȧ);return;case "SEND":ΖЈ(З.Remove(0,"SEND".Length+1));return;}Ρ=Ǯ;}void ΖЈ(String Ş){if(Ş=="") return;var ι=Ş.Split(':');if(ι.Length!=2){Ρ="Missing separator \":\"";return;}ι.DefaultIfEmpty("");
String Ľ=ι.ElementAtOrDefault(0).Trim();ѕ ή=ΔЂ("",Ľ);if(ή!=null) ķ(ή,ι.ElementAtOrDefault(1).Trim());else Ρ="Unknown ship: "+Ľ;}void Ζζ(){ǐ.Clear();ć=null;λ(Τ.Main);І=0;}void ΕЁ(){List<IMyTerminalBlock>ż=new List<IMyTerminalBlock>();ω.GetBlocksOfType(Г,ф);ω.SearchBlocksOfName(pamTag.Substring(0,pamTag.Length-1)+":",ż,
q=>q.CubeGrid==Me.CubeGrid&&q is IMyTextSurfaceProvider);Г=ё(Г,pamTag,true);Δδ(ż);Δύ();ȱ(Г,setLCDFontAndSize,1.15f,false);ȱ(ǡ,setLCDFontAndSize,1.15f,true);}void ΖΫ(){String Ŕ="[PAM]-Controller\n\n"+"Run-arguments: (Type without:[ ])\n"+"———————————————\n"+
"[UP] Menu navigation up\n"+"[DOWN] Menu navigation down\n"+"[APPLY] Apply menu point\n"+
"[CLEAR] Clear miner list\n"+"[SEND ship:cmd] Send to a ship*\n"+"[SENDALL cmd] Send to all ships*\n"+
"———————————————\n\n"+"*[SEND] = Cmd to one ship:\n"+" e.g.: \"SEND Miner 1:homepos\"\n\n"+
"*[SENDALL] = Cmd to all ships:\n"+" e.g.: \"SENDALL homepos\"\n\n";for(int i=0;i<ǡ.Count;i++)
ǡ[i].WriteText(ΔЁ(ј.ΓЌ,"0",false));for(int i=0;i<Г.Count;i++){ј С=ј.Ȭ;String Ĝ="";Ζε(Г[i],out С,out Ĝ);Г[i].WriteText(ΔЁ(С,Ĝ,i==0));}Echo(Ŕ);for(int i=0;i<ė.Count;i++){IMyTextPanel ȏ=ė[i];String ζ=ȏ.CustomData.ToUpper();if(ζ=="DEBUG") ȏ.WriteText(""+"\n"+"");if(ζ=="INSTRUCTIONS") ȏ.WriteText(Δζ());
}}String Ƨ(bool Η){int ΕΪ=0;return Ƨ(Η,0,ref ΕΪ,false,1);}String Ƨ(bool Η,int Ηθ,ref int Ηε,bool Ηκ,int ΒΞ){return "[PAM]-Controller | "+ǐ.Count+" Connected ships\n";}String ΔЁ(ј С,String Ĝ,bool ΗΪ){return Ƨ(false);}void Ζε(IMyTerminalBlock ȏ,out ј С,out String Ĝ){bool ā=true;String Ţ=ƶ(ǉ(ȏ.CustomData.Split('\n'),"mode",ref ā)).ToUpper();
String[]ι=Ţ.Split(':');String ş=ι.Length>0?ι[0].Trim():"";Ĝ=ι.Length>1?ι[1].Trim():"";С=ј.Ȭ;if(ş=="MAIN") С=ј.ΕΖ;else if(ş=="MAINX") С=ј.ΓЌ;else if(ş=="MENU") С=ј.Εβ;else if(ş=="INVENTORY") С=ј.ΗΛ;else if(ş=="DEBUG") С=ј.ΖΜ;if(С==ј.Ȭ) Ĝ=Ţ;}String Δς(int Αβ,String Γ,int ΔΣ,ref int Ȏ)
{String[]Ζ=Γ.Split('\n');if(ΔΣ>=Ȏ+Αβ-1) Ȏ++;Ȏ=Math.Min(Ζ.Count()-1-Αβ,Ȏ);if(ΔΣ<Ȏ+1) Ȏ--;Ȏ=Math.Max(0,Ȏ);String Ω="";for(int i=0;i<Αβ;i++){int ΓЏ=i+Ȏ;if(ΓЏ>=Ζ.Count()) break;Ω+=Ζ[ΓЏ]+"\n";}return Ω;}String ΗΩ(int Ń,int ΒΞ,String Γ){String[]Ζ=Γ.Split('\n');
int ΖΤ=Ń*ΒΞ;int ΗΝ=(Ń+1)*ΒΞ;String Ω="";for(int i=ΖΤ;i<ΗΝ;i++){if(i>=Ζ.Count()) break;Ω+=Ζ[i]+"\n";}return Ω;}String Ζύ(String s){if(s=="") return s;return s.First().ToString().ToUpper()+s.Substring(1).ToLower();}String ΖϏ(String s,int Δν){if(s=="") return s;if(s.Length>Δν) s=s.Substring(0,Δν-1)+".";
return s;}string ΗΦ(String Ĉ,float value,float Αί,int Γά,int ΔІ,int ΕΔ){float Ď=Ѕ(value,Αί)*Γά;String ƈ="[";for(int i=0;i<Γά;i++){if(i<=Ď) ƈ+="|";else ƈ+="'";}ƈ+="]";return ƈ+" "+ΖϏ(Ζύ(Ĉ),ΔІ).PadRight(ΔІ)+"".PadRight(ΕΔ)+ΕΚ(value);}String ΕΚ(float Ϗ){if(Ϗ>=1000000) return Math.Round(Ϗ/1000000f,Ϗ/1000000f<100?1:0)+"M";
if(Ϗ>=1000) return Math.Round(Ϗ/1000f,Ϗ/1000f<100?1:0)+"K";return ""+Math.Round(Ϗ);}String ΒΖ(int Ż){if(Ż>=60*60) return Math.Round(Ż/(60f*60f),1)+" h";if(Ż>=60) return Math.Round(Ż/60f,1)+" min";return ""+Ż+" s";}string Ŋ(float v){return Math.Round(v,2)+" ";}
string Ηγ(Vector3 v){return "X"+Ŋ(v.X)+"Y"+Ŋ(v.Y)+"Z"+Ŋ(v.Z);}